# generated by datamodel-codegen:
#   filename:  action.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class NoopAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['noop'] = 'noop'
    reason: str | None = None


class SwapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['swap'] = 'swap'
    token_in: str = Field(..., alias='tokenIn', min_length=1, pattern='^[A-Z0-9]+$')
    base: str | None = Field(
        None,
        description='market selector: the base asset of the base/USDC market to trade (e.g. "WBTC"). Omit for the default WETH/USDC market. NOT the input token — use tokenIn for that (tokenIn is the base symbol to sell, or "USDC" to buy).',
        min_length=1,
        pattern='^[A-Z0-9]+$',
    )
    amount_in: str = Field(..., alias='amountIn', pattern='^[0-9]+$')
    slippage_bps: int | None = Field(
        None, alias='slippageBps', ge=0, le=9007199254740991
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class MintLiquidityAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['mintLiquidity'] = 'mintLiquidity'
    base: str | None = Field(
        None,
        description='market selector: the base asset of the base/USDC market to trade (e.g. "WBTC"). Omit for the default WETH/USDC market. NOT the input token — use tokenIn for that (tokenIn is the base symbol to sell, or "USDC" to buy).',
        min_length=1,
        pattern='^[A-Z0-9]+$',
    )
    tick_lower: int = Field(
        ..., alias='tickLower', ge=-9007199254740991, le=9007199254740991
    )
    tick_upper: int = Field(
        ..., alias='tickUpper', ge=-9007199254740991, le=9007199254740991
    )
    amount_weth_desired: str = Field(..., alias='amountWethDesired', pattern='^[0-9]+$')
    amount_usdc_desired: str = Field(..., alias='amountUsdcDesired', pattern='^[0-9]+$')
    amount_base_desired: str | None = Field(
        None, alias='amountBaseDesired', pattern='^[0-9]+$'
    )
    amount_quote_desired: str | None = Field(
        None, alias='amountQuoteDesired', pattern='^[0-9]+$'
    )
    slippage_bps: int | None = Field(
        None, alias='slippageBps', ge=0, le=9007199254740991
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class RemoveLiquidityAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['removeLiquidity'] = 'removeLiquidity'
    base: str | None = Field(
        None,
        description='market selector: the base asset of the base/USDC market to trade (e.g. "WBTC"). Omit for the default WETH/USDC market. NOT the input token — use tokenIn for that (tokenIn is the base symbol to sell, or "USDC" to buy).',
        min_length=1,
        pattern='^[A-Z0-9]+$',
    )
    token_id: str = Field(..., alias='tokenId', pattern='^[0-9]+$')
    liquidity: str = Field(..., pattern='^[0-9]+$')
    amount_weth_min: str | None = Field(None, alias='amountWethMin', pattern='^[0-9]+$')
    amount_usdc_min: str | None = Field(None, alias='amountUsdcMin', pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class CollectFeesAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['collectFees'] = 'collectFees'
    base: str | None = Field(
        None,
        description='market selector: the base asset of the base/USDC market to trade (e.g. "WBTC"). Omit for the default WETH/USDC market. NOT the input token — use tokenIn for that (tokenIn is the base symbol to sell, or "USDC" to buy).',
        min_length=1,
        pattern='^[A-Z0-9]+$',
    )
    token_id: str = Field(..., alias='tokenId', pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class CreatePoolAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['createPool'] = 'createPool'
    token_a: str = Field(..., alias='tokenA', pattern='^0x[0-9a-fA-F]{40}$')
    token_b: str = Field(..., alias='tokenB', pattern='^0x[0-9a-fA-F]{40}$')
    fee: int = Field(
        ...,
        description='Uniswap V3 fee in pips: 100, 500, 3000 or 10000',
        ge=-9007199254740991,
        le=9007199254740991,
    )
    sqrt_price_x96: str = Field(
        ...,
        alias='sqrtPriceX96',
        description='initial price as sqrt(token1/token0) * 2^96, computed against the sorted pair (the lower address is token0)',
        pattern='^[0-9]+$',
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class BalancerSwapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['balancerSwap'] = 'balancerSwap'
    token_in: str = Field(..., alias='tokenIn', min_length=1, pattern='^[A-Z0-9]+$')
    base: str | None = Field(
        None,
        description='market selector: the base asset of the base/USDC market to trade (e.g. "WBTC"). Omit for the default WETH/USDC market. NOT the input token — use tokenIn for that (tokenIn is the base symbol to sell, or "USDC" to buy).',
        min_length=1,
        pattern='^[A-Z0-9]+$',
    )
    amount_in: str = Field(..., alias='amountIn', pattern='^[0-9]+$')
    slippage_bps: int | None = Field(
        None, alias='slippageBps', ge=0, le=9007199254740991
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class CurveSwapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['curveSwap'] = 'curveSwap'
    token_in: str = Field(..., alias='tokenIn', min_length=1, pattern='^[A-Z0-9]+$')
    base: str | None = Field(
        None,
        description='market selector: the base asset of the base/USDC market to trade (e.g. "WBTC"). Omit for the default WETH/USDC market. NOT the input token — use tokenIn for that (tokenIn is the base symbol to sell, or "USDC" to buy).',
        min_length=1,
        pattern='^[A-Z0-9]+$',
    )
    amount_in: str = Field(..., alias='amountIn', pattern='^[0-9]+$')
    slippage_bps: int | None = Field(
        None, alias='slippageBps', ge=0, le=9007199254740991
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class StableSwapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['stableSwap'] = 'stableSwap'
    stable: str = Field(..., min_length=1, pattern='^[A-Z0-9]+$')
    token_in: str = Field(..., alias='tokenIn', min_length=1, pattern='^[A-Z0-9]+$')
    amount_in: str = Field(..., alias='amountIn', pattern='^[0-9]+$')
    slippage_bps: int | None = Field(
        None, alias='slippageBps', ge=0, le=9007199254740991
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class GmxIncreaseAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['gmxIncrease'] = 'gmxIncrease'
    is_long: bool = Field(..., alias='isLong')
    base: str | None = Field(
        None,
        description='market selector: the base asset of the base/USDC market to trade (e.g. "WBTC"). Omit for the default WETH/USDC market. NOT the input token — use tokenIn for that (tokenIn is the base symbol to sell, or "USDC" to buy).',
        min_length=1,
        pattern='^[A-Z0-9]+$',
    )
    collateral: str = Field(..., min_length=1, pattern='^[A-Z0-9]+$')
    collateral_amount: str = Field(..., alias='collateralAmount', pattern='^[0-9]+$')
    size_delta_usd: str = Field(..., alias='sizeDeltaUsd', pattern='^[0-9]+$')
    acceptable_price: str | None = Field(
        None, alias='acceptablePrice', pattern='^[0-9]+$'
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class GmxDecreaseAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['gmxDecrease'] = 'gmxDecrease'
    is_long: bool = Field(..., alias='isLong')
    base: str | None = Field(
        None,
        description='market selector: the base asset of the base/USDC market to trade (e.g. "WBTC"). Omit for the default WETH/USDC market. NOT the input token — use tokenIn for that (tokenIn is the base symbol to sell, or "USDC" to buy).',
        min_length=1,
        pattern='^[A-Z0-9]+$',
    )
    collateral: str = Field(..., min_length=1, pattern='^[A-Z0-9]+$')
    collateral_delta_amount: str = Field(
        ..., alias='collateralDeltaAmount', pattern='^[0-9]+$'
    )
    size_delta_usd: str = Field(..., alias='sizeDeltaUsd', pattern='^[0-9]+$')
    acceptable_price: str | None = Field(
        None, alias='acceptablePrice', pattern='^[0-9]+$'
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class AaveSupplyAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['aaveSupply'] = 'aaveSupply'
    asset: str = Field(..., min_length=1, pattern='^[A-Z0-9]+$')
    amount: str = Field(..., pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class Amount(RootModel[str]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: str = Field(..., pattern='^[0-9]+$')


class AaveWithdrawAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['aaveWithdraw'] = 'aaveWithdraw'
    asset: str = Field(..., min_length=1, pattern='^[A-Z0-9]+$')
    amount: Amount | str
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class AaveBorrowAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['aaveBorrow'] = 'aaveBorrow'
    asset: str = Field(..., min_length=1, pattern='^[A-Z0-9]+$')
    amount: str = Field(..., pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class AaveRepayAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['aaveRepay'] = 'aaveRepay'
    asset: str = Field(..., min_length=1, pattern='^[A-Z0-9]+$')
    amount: Amount | str
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LstDepositAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lstDeposit'] = 'lstDeposit'
    amount_weth_wei: str = Field(
        ...,
        alias='amountWethWei',
        description="WETH to stake (wei). Mints LST at the vault's current redemption rate.",
        pattern='^[0-9]+$',
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LstSwapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lstSwap'] = 'lstSwap'
    token_in: Literal['WETH', 'LST'] = Field(
        ...,
        alias='tokenIn',
        description='the token you are sending: "WETH" buys LST from the secondary market, "LST" sells into it (the instant exit, at the pool\'s discount).',
    )
    amount_in: str = Field(
        ...,
        alias='amountIn',
        description='wei of tokenIn (both are 18-decimal)',
        pattern='^[0-9]+$',
    )
    slippage_bps: int | None = Field(
        None, alias='slippageBps', ge=0, le=9007199254740991
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LstRequestWithdrawAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lstRequestWithdraw'] = 'lstRequestWithdraw'
    amount_lst_wei: str = Field(
        ...,
        alias='amountLstWei',
        description='LST shares to queue for redemption at par (wei). Claimable after withdrawalDelayBlocks; this is the slow, full-value exit.',
        pattern='^[0-9]+$',
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LstClaimWithdrawAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lstClaimWithdraw'] = 'lstClaimWithdraw'
    request_id: str | None = Field(
        None,
        alias='requestId',
        description='a specific queued request id. Omit to claim every request that has finalized.',
        pattern='^[0-9]+$',
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LiquityOpenTroveAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['liquityOpenTrove'] = 'liquityOpenTrove'
    collateral_weth_wei: str = Field(
        ...,
        alias='collateralWethWei',
        description='WETH to unwrap and post as collateral (wei). It also has to leave enough native ETH behind to pay for gas.',
        pattern='^[0-9]+$',
    )
    debt_eusd_wei: str = Field(
        ...,
        alias='debtEusdWei',
        description='eUSD to draw (wei). Booked debt is this plus the borrowing fee plus 200 eUSD of gas compensation, and the total must clear MIN_NET_DEBT (1,800 eUSD).',
        pattern='^[0-9]+$',
    )
    max_fee_bps: int | None = Field(
        None,
        alias='maxFeeBps',
        description='slippage bound on the protocol fee, in bps. Both fee curves rise with use, so a bound that is too tight reverts. Default 500 (5%).',
        gt=0,
        le=10000,
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LiquityAdjustTroveAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['liquityAdjustTrove'] = 'liquityAdjustTrove'
    add_collateral_weth_wei: str | None = Field(
        None,
        alias='addCollateralWethWei',
        description='WETH to unwrap and add as collateral (wei).',
        pattern='^[0-9]+$',
    )
    withdraw_collateral_wei: str | None = Field(
        None,
        alias='withdrawCollateralWei',
        description='collateral to take back out, paid in native ETH (wei).',
        pattern='^[0-9]+$',
    )
    debt_change_eusd_wei: str | None = Field(
        None,
        alias='debtChangeEusdWei',
        description='eUSD to draw or repay (wei); set isDebtIncrease to say which.',
        pattern='^[0-9]+$',
    )
    is_debt_increase: bool | None = Field(
        None,
        alias='isDebtIncrease',
        description='true draws more eUSD, false repays. Required with a debt change.',
    )
    max_fee_bps: int | None = Field(
        None,
        alias='maxFeeBps',
        description='slippage bound on the protocol fee, in bps. Both fee curves rise with use, so a bound that is too tight reverts. Default 500 (5%).',
        gt=0,
        le=10000,
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LiquityCloseTroveAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['liquityCloseTrove'] = 'liquityCloseTrove'
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LiquityRedeemAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['liquityRedeem'] = 'liquityRedeem'
    amount_eusd_wei: str = Field(
        ...,
        alias='amountEusdWei',
        description='eUSD to redeem for collateral at the oracle price (wei). Worth doing when eUSD trades below par by more than redemptionRateBps.',
        pattern='^[0-9]+$',
    )
    max_iterations: int | None = Field(
        None,
        alias='maxIterations',
        description='cap on how many Troves the redemption walks. 0 = no cap.',
        ge=0,
        le=9007199254740991,
    )
    max_fee_bps: int | None = Field(
        None,
        alias='maxFeeBps',
        description='slippage bound on the protocol fee, in bps. Both fee curves rise with use, so a bound that is too tight reverts. Default 500 (5%).',
        gt=0,
        le=10000,
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LiquityProvideToSPAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['liquityProvideToSP'] = 'liquityProvideToSP'
    amount_eusd_wei: str = Field(
        ...,
        alias='amountEusdWei',
        description='eUSD to deposit into the Stability Pool (wei). It absorbs liquidated debt and pays out the collateral at a discount.',
        pattern='^[0-9]+$',
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class AmountEusdWei(RootModel[str]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: str = Field(
        ...,
        description='eUSD to withdraw (wei), or "max". "0" claims the accrued ETH gain without touching the deposit.',
        pattern='^[0-9]+$',
    )


class LiquityWithdrawFromSPAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['liquityWithdrawFromSP'] = 'liquityWithdrawFromSP'
    amount_eusd_wei: AmountEusdWei | str = Field(
        ...,
        alias='amountEusdWei',
        description='eUSD to withdraw (wei), or "max". "0" claims the accrued ETH gain without touching the deposit.',
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class Borrower(RootModel[str]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: str = Field(..., pattern='^0x[0-9a-fA-F]*$')


class LiquityLiquidateAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['liquityLiquidate'] = 'liquityLiquidate'
    borrowers: list[Borrower] | None = Field(
        None, description='specific Trove owners to liquidate.'
    )
    max_troves: int | None = Field(
        None,
        alias='maxTroves',
        description='instead of naming owners, sweep this many of the riskiest Troves.',
        gt=0,
        le=9007199254740991,
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LiquitySwapEusdAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['liquitySwapEusd'] = 'liquitySwapEusd'
    token_in: Literal['USDC', 'EUSD'] = Field(
        ...,
        alias='tokenIn',
        description='the token you are sending: "USDC" buys eUSD from the pool, "EUSD" sells into it.',
    )
    amount_in: str = Field(
        ...,
        alias='amountIn',
        description='units of tokenIn (USDC is 6-decimal, eUSD is 18-decimal)',
        pattern='^[0-9]+$',
    )
    slippage_bps: int | None = Field(
        None, alias='slippageBps', ge=0, le=9007199254740991
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class CreateLendingMarketAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['createLendingMarket'] = 'createLendingMarket'
    loan_token: str = Field(..., alias='loanToken', pattern='^0x[0-9a-fA-F]{40}$')
    collateral_token: str = Field(
        ..., alias='collateralToken', pattern='^0x[0-9a-fA-F]{40}$'
    )
    oracle: str = Field(
        ...,
        description='any address implementing price(). It may be one you control -- and a counterparty is expected to read owner() and decide what that means',
        pattern='^0x[0-9a-fA-F]{40}$',
    )
    irm: str = Field(
        ...,
        description='any address implementing borrowRatePerSecond. The zero address means no interest',
        pattern='^0x[0-9a-fA-F]{40}$',
    )
    lltv: str = Field(
        ...,
        description='liquidation LTV in WAD, below 1e18 (0.9e18 = 90%)',
        pattern='^[0-9]+$',
    )
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LendingSupplyAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lendingSupply'] = 'lendingSupply'
    market_id: str = Field(..., alias='marketId', pattern='^0x[0-9a-fA-F]{64}$')
    amount: str = Field(..., pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LendingWithdrawAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lendingWithdraw'] = 'lendingWithdraw'
    market_id: str = Field(..., alias='marketId', pattern='^0x[0-9a-fA-F]{64}$')
    amount: Amount | str
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LendingSupplyCollateralAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lendingSupplyCollateral'] = 'lendingSupplyCollateral'
    market_id: str = Field(..., alias='marketId', pattern='^0x[0-9a-fA-F]{64}$')
    amount: str = Field(..., pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LendingWithdrawCollateralAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lendingWithdrawCollateral'] = 'lendingWithdrawCollateral'
    market_id: str = Field(..., alias='marketId', pattern='^0x[0-9a-fA-F]{64}$')
    amount: str = Field(..., pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LendingBorrowAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lendingBorrow'] = 'lendingBorrow'
    market_id: str = Field(..., alias='marketId', pattern='^0x[0-9a-fA-F]{64}$')
    amount: str = Field(..., pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LendingRepayAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lendingRepay'] = 'lendingRepay'
    market_id: str = Field(..., alias='marketId', pattern='^0x[0-9a-fA-F]{64}$')
    amount: Amount | str
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class LendingLiquidateAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['lendingLiquidate'] = 'lendingLiquidate'
    market_id: str = Field(..., alias='marketId', pattern='^0x[0-9a-fA-F]{64}$')
    borrower: str = Field(..., pattern='^0x[0-9a-fA-F]{40}$')
    seized_assets: str = Field(..., alias='seizedAssets', pattern='^[0-9]+$')
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class BundleAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['bundle'] = 'bundle'
    actions: list[
        SwapAction
        | MintLiquidityAction
        | RemoveLiquidityAction
        | CollectFeesAction
        | CreatePoolAction
        | BalancerSwapAction
        | CurveSwapAction
        | StableSwapAction
        | AaveSupplyAction
        | AaveWithdrawAction
        | AaveBorrowAction
        | AaveRepayAction
        | LstDepositAction
        | LstSwapAction
        | LstRequestWithdrawAction
        | LstClaimWithdrawAction
        | CreateLendingMarketAction
        | LendingSupplyAction
        | LendingWithdrawAction
        | LendingSupplyCollateralAction
        | LendingWithdrawCollateralAction
        | LendingBorrowAction
        | LendingRepayAction
        | LendingLiquidateAction
    ] = Field(..., min_length=1)
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class Tx(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    to: str | None = Field(None, pattern='^0x[0-9a-fA-F]*$')
    data: str = Field(..., pattern='^0x[0-9a-fA-F]*$')
    value: str | None = Field(None, pattern='^[0-9]+$')


class RawTxAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['rawTx'] = 'rawTx'
    tx: Tx
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class RawBundleAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['rawBundle'] = 'rawBundle'
    txs: list[Tx] = Field(..., min_length=1)
    max_priority_fee_per_gas_wei: str | None = Field(
        None, alias='maxPriorityFeePerGasWei', pattern='^[0-9]+$'
    )


class Action(
    RootModel[
        NoopAction
        | SwapAction
        | MintLiquidityAction
        | RemoveLiquidityAction
        | CollectFeesAction
        | CreatePoolAction
        | BalancerSwapAction
        | CurveSwapAction
        | StableSwapAction
        | GmxIncreaseAction
        | GmxDecreaseAction
        | AaveSupplyAction
        | AaveWithdrawAction
        | AaveBorrowAction
        | AaveRepayAction
        | LstDepositAction
        | LstSwapAction
        | LstRequestWithdrawAction
        | LstClaimWithdrawAction
        | LiquityOpenTroveAction
        | LiquityAdjustTroveAction
        | LiquityCloseTroveAction
        | LiquityRedeemAction
        | LiquityProvideToSPAction
        | LiquityWithdrawFromSPAction
        | LiquityLiquidateAction
        | LiquitySwapEusdAction
        | CreateLendingMarketAction
        | LendingSupplyAction
        | LendingWithdrawAction
        | LendingSupplyCollateralAction
        | LendingWithdrawCollateralAction
        | LendingBorrowAction
        | LendingRepayAction
        | LendingLiquidateAction
        | BundleAction
        | RawTxAction
        | RawBundleAction
    ]
):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: (
        NoopAction
        | SwapAction
        | MintLiquidityAction
        | RemoveLiquidityAction
        | CollectFeesAction
        | CreatePoolAction
        | BalancerSwapAction
        | CurveSwapAction
        | StableSwapAction
        | GmxIncreaseAction
        | GmxDecreaseAction
        | AaveSupplyAction
        | AaveWithdrawAction
        | AaveBorrowAction
        | AaveRepayAction
        | LstDepositAction
        | LstSwapAction
        | LstRequestWithdrawAction
        | LstClaimWithdrawAction
        | LiquityOpenTroveAction
        | LiquityAdjustTroveAction
        | LiquityCloseTroveAction
        | LiquityRedeemAction
        | LiquityProvideToSPAction
        | LiquityWithdrawFromSPAction
        | LiquityLiquidateAction
        | LiquitySwapEusdAction
        | CreateLendingMarketAction
        | LendingSupplyAction
        | LendingWithdrawAction
        | LendingSupplyCollateralAction
        | LendingWithdrawCollateralAction
        | LendingBorrowAction
        | LendingRepayAction
        | LendingLiquidateAction
        | BundleAction
        | RawTxAction
        | RawBundleAction
    ) = Field(..., title='Action')
