# generated by datamodel-codegen:
#   filename:  observation.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class OraclePrices(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    weth_usd: float = Field(..., alias='wethUsd')
    usdc_usd: float = Field(..., alias='usdcUsd')


class Stables(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    token: str
    decimals: float
    balance: str
    price_usdc: float = Field(..., alias='priceUsdc')
    market_quoted: bool = Field(..., alias='marketQuoted')


class Balances(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    eth_wei: str = Field(..., alias='ethWei')
    weth_wei: str = Field(..., alias='wethWei')
    usdc_units: str = Field(..., alias='usdcUnits')
    stables: dict[str, Stables] | None = None


class Inventory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    value_usdc: float = Field(..., alias='valueUsdc')
    weth: float
    usdc: float
    eth: float


class HistoryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    round: float
    pool_price_usdc_per_weth: float = Field(..., alias='poolPriceUsdcPerWeth')
    fair_price_usdc_per_weth: float = Field(..., alias='fairPriceUsdcPerWeth')


class Limits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    default_priority_fee_per_gas_wei: str = Field(
        ..., alias='defaultPriorityFeePerGasWei'
    )
    max_priority_fee_per_gas_wei: str = Field(..., alias='maxPriorityFeePerGasWei')
    default_slippage_bps: float = Field(..., alias='defaultSlippageBps')


class Competition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    max_competitor_priority_fee_wei: str = Field(
        ..., alias='maxCompetitorPriorityFeeWei'
    )
    max_block_priority_fee_wei: str = Field(..., alias='maxBlockPriorityFeeWei')
    last_tx_index: float | None = Field(..., alias='lastTxIndex')
    recent_revert_rate: float = Field(..., alias='recentRevertRate')
    recent_sample_size: float = Field(..., alias='recentSampleSize')


class Pool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    pair: Literal['WETH/USDC'] = 'WETH/USDC'
    fee: float
    price_usdc_per_weth: float = Field(..., alias='priceUsdcPerWeth')
    tick: float
    tick_spacing: float = Field(..., alias='tickSpacing')
    liquidity: str | None = None


class LpPositionObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    token_id: str = Field(..., alias='tokenId')
    tick_lower: float = Field(..., alias='tickLower')
    tick_upper: float = Field(..., alias='tickUpper')
    liquidity: str
    tokens_owed_weth_wei: str = Field(..., alias='tokensOwedWethWei')
    tokens_owed_usdc_units: str = Field(..., alias='tokensOwedUsdcUnits')
    uncollected_fees_weth_wei: str = Field(..., alias='uncollectedFeesWethWei')
    uncollected_fees_usdc_units: str = Field(..., alias='uncollectedFeesUsdcUnits')
    amount_weth_wei: str = Field(..., alias='amountWethWei')
    amount_usdc_units: str = Field(..., alias='amountUsdcUnits')
    value_usdc: float = Field(..., alias='valueUsdc')
    market: str | None = None


class UniswapMarketObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    pair: str
    fee: float
    price_usdc_per_weth: float = Field(..., alias='priceUsdcPerWeth')
    tick: float
    tick_spacing: float = Field(..., alias='tickSpacing')
    liquidity: str | None = None


class Reserves(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    weth: str
    usdc: str


class Markets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    price_usdc_per_weth: float = Field(..., alias='priceUsdcPerWeth')
    reserves: Reserves | None = None
    sell_price_usdc_per_weth: float | None = Field(None, alias='sellPriceUsdcPerWeth')
    buy_price_usdc_per_weth: float | None = Field(None, alias='buyPriceUsdcPerWeth')
    effective_half_spread_bps: float | None = Field(
        None, alias='effectiveHalfSpreadBps'
    )


class AmmObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    price_usdc_per_weth: float = Field(..., alias='priceUsdcPerWeth')
    reserves: Reserves | None = None
    markets: dict[str, Markets] | None = None
    sell_price_usdc_per_weth: float | None = Field(None, alias='sellPriceUsdcPerWeth')
    buy_price_usdc_per_weth: float | None = Field(None, alias='buyPriceUsdcPerWeth')
    effective_half_spread_bps: float | None = Field(
        None, alias='effectiveHalfSpreadBps'
    )


class AaveObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    health_factor: str = Field(..., alias='healthFactor')
    total_collateral_base: str = Field(..., alias='totalCollateralBase')
    total_debt_base: str = Field(..., alias='totalDebtBase')
    available_borrows_base: str = Field(..., alias='availableBorrowsBase')
    supplied: dict[str, str]
    borrowed: dict[str, str]
    pool_liquidity: dict[str, str] | None = Field(None, alias='poolLiquidity')


class PoolReserves(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    weth: str
    lst: str


class LstWithdrawalObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: str = Field(..., alias='requestId')
    assets_weth_wei: str = Field(..., alias='assetsWethWei')
    claimable_at_block: str = Field(..., alias='claimableAtBlock')
    claimable: bool


class PoolReserves1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    eusd: str
    usdc: str


class RiskiestTrove(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    owner: str
    icr: float
    net_debt_eusd_wei: str = Field(..., alias='netDebtEusdWei')


class LiquityTroveObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: float
    coll_wei: str = Field(..., alias='collWei')
    debt_eusd_wei: str = Field(..., alias='debtEusdWei')
    net_debt_eusd_wei: str = Field(..., alias='netDebtEusdWei')
    icr: float
    liquidation_price_usd: float = Field(..., alias='liquidationPriceUsd')
    position_from_riskiest: float = Field(..., alias='positionFromRiskiest')
    redeemed_ahead_eusd_wei: str = Field(..., alias='redeemedAheadEusdWei')
    position_known: bool = Field(..., alias='positionKnown')


class LendingPositionObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    market_id: str = Field(..., alias='marketId')
    loan_token: str = Field(..., alias='loanToken')
    collateral_token: str = Field(..., alias='collateralToken')
    oracle: str
    oracle_owner: str | None = Field(None, alias='oracleOwner')
    irm: str
    lltv: str
    liquidation_incentive_factor: str = Field(..., alias='liquidationIncentiveFactor')
    price: str
    supply_assets: str = Field(..., alias='supplyAssets')
    borrow_assets: str = Field(..., alias='borrowAssets')
    collateral: str
    healthy: bool
    total_supply_assets: str = Field(..., alias='totalSupplyAssets')
    total_borrow_assets: str = Field(..., alias='totalBorrowAssets')


class Allowance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    spender: str
    token: str
    symbol: str | None = None
    amount: str
    unlimited: bool


class StrandedHoldingObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    market: str
    token: str
    symbol: str | None = None
    amount_raw: str = Field(..., alias='amountRaw')


class UniswapObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    pool: Pool
    positions: list[LpPositionObservation]
    markets: dict[str, UniswapMarketObservation] | None = None


class GmxPositionObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    is_long: bool = Field(..., alias='isLong')
    size_usd: str = Field(..., alias='sizeUsd')
    size_in_tokens: str = Field(..., alias='sizeInTokens')
    collateral: str
    collateral_amount: str = Field(..., alias='collateralAmount')
    entry_price_usd: float = Field(..., alias='entryPriceUsd')
    pnl_usd: float = Field(..., alias='pnlUsd')
    funding_owed_usd: float | None = Field(None, alias='fundingOwedUsd')


class LstObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    redemption_rate_weth: float = Field(..., alias='redemptionRateWeth')
    market_price_weth: float = Field(..., alias='marketPriceWeth')
    market_sell_price_weth: float | None = Field(None, alias='marketSellPriceWeth')
    market_buy_price_weth: float | None = Field(None, alias='marketBuyPriceWeth')
    discount_bps: float = Field(..., alias='discountBps')
    market_quoted: bool | None = Field(None, alias='marketQuoted')
    apy_bps: float = Field(..., alias='apyBps')
    yield_per_block_bps: float = Field(..., alias='yieldPerBlockBps')
    withdrawal_delay_blocks: float = Field(..., alias='withdrawalDelayBlocks')
    estimated_queue_delay_blocks: float = Field(..., alias='estimatedQueueDelayBlocks')
    queue_delay_per_weth_blocks: float | None = Field(
        None, alias='queueDelayPerWethBlocks'
    )
    queue_throughput_wei_per_block: str | None = Field(
        None, alias='queueThroughputWeiPerBlock'
    )
    queue_length: float = Field(..., alias='queueLength')
    reward_reserve_wei: str = Field(..., alias='rewardReserveWei')
    lst_balance_wei: str = Field(..., alias='lstBalanceWei')
    lst_redemption_value_weth_wei: str = Field(..., alias='lstRedemptionValueWethWei')
    instant_exit_weth_wei: str = Field(..., alias='instantExitWethWei')
    pending_withdrawals: list[LstWithdrawalObservation] = Field(
        ..., alias='pendingWithdrawals'
    )
    pending_withdrawal_weth_wei: str = Field(..., alias='pendingWithdrawalWethWei')
    claimable_withdrawal_weth_wei: str = Field(..., alias='claimableWithdrawalWethWei')
    pool_reserves: PoolReserves | None = Field(None, alias='poolReserves')
    aave_collateral: bool | None = Field(None, alias='aaveCollateral')


class LiquityObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    price_usd: float = Field(..., alias='priceUsd')
    tcr: float
    recovery_mode: bool = Field(..., alias='recoveryMode')
    mcr: float
    ccr: float
    trove_count: float = Field(..., alias='troveCount')
    total_coll_wei: str = Field(..., alias='totalCollWei')
    total_debt_eusd_wei: str = Field(..., alias='totalDebtEusdWei')
    borrowing_rate_bps: float = Field(..., alias='borrowingRateBps')
    redemption_rate_bps: float = Field(..., alias='redemptionRateBps')
    base_rate_bps: float = Field(..., alias='baseRateBps')
    min_net_debt_eusd_wei: str = Field(..., alias='minNetDebtEusdWei')
    gas_compensation_eusd_wei: str = Field(..., alias='gasCompensationEusdWei')
    eusd_balance_wei: str = Field(..., alias='eusdBalanceWei')
    market_price_usdc: float = Field(..., alias='marketPriceUsdc')
    market_sell_price_usdc: float | None = Field(None, alias='marketSellPriceUsdc')
    market_buy_price_usdc: float | None = Field(None, alias='marketBuyPriceUsdc')
    market_quoted: bool = Field(..., alias='marketQuoted')
    discount_bps: float = Field(..., alias='discountBps')
    redemption_edge_bps: float = Field(..., alias='redemptionEdgeBps')
    pool_reserves: PoolReserves1 | None = Field(None, alias='poolReserves')
    trove: LiquityTroveObservation | None = None
    riskiest_trove: RiskiestTrove | None = Field(None, alias='riskiestTrove')
    sp_deposit_eusd_wei: str = Field(..., alias='spDepositEusdWei')
    sp_eth_gain_wei: str = Field(..., alias='spEthGainWei')
    sp_lqty_gain_wei: str = Field(..., alias='spLqtyGainWei')
    sp_total_deposits_eusd_wei: str = Field(..., alias='spTotalDepositsEusdWei')
    sp_share_bps: float = Field(..., alias='spShareBps')
    eth_balance_wei: str = Field(..., alias='ethBalanceWei')
    suggested_gas_reserve_wei: str = Field(..., alias='suggestedGasReserveWei')


class LendingObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    singleton: str
    markets: list[LendingPositionObservation]
    dropped: float


class RegistryEntryObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    market: str
    kind: Literal[
        'unknown',
        'uniswapV3Pool',
        'balancerWeightedPool',
        'curvePlainPool',
        'curveTwocryptoPool',
        'lendingMarket',
        'erc20',
    ]
    creator: str
    mine: bool
    token0: str | None = None
    token1: str | None = None
    oracle: str | None = None
    oracle_owner: str | None = Field(None, alias='oracleOwner')
    codehash_at_registration: str = Field(..., alias='codehashAtRegistration')
    codehash_now: str | None = Field(None, alias='codehashNow')
    verified: bool
    registered_at_block: str = Field(..., alias='registeredAtBlock')
    extra: str | None = None


class DiscoveredPool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    address: str = Field(..., description='TypeScript type to use for `address` values')
    token0: str = Field(..., description='TypeScript type to use for `address` values')
    token1: str = Field(..., description='TypeScript type to use for `address` values')
    token0_decimals: float = Field(..., alias='token0Decimals')
    token1_decimals: float = Field(..., alias='token1Decimals')
    fee_bps: float = Field(..., alias='feeBps')
    created_at_block: float = Field(..., alias='createdAtBlock')
    reserve0: str
    reserve1: str
    implied_price_token1_per_token0: float | None = Field(
        ..., alias='impliedPriceToken1PerToken0'
    )
    codehash: str


class GmxMarketObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    market_price_usd: float = Field(..., alias='marketPriceUsd')
    position: GmxPositionObservation | None = None
    long_oi_usd: float | None = Field(None, alias='longOiUsd')
    short_oi_usd: float | None = Field(None, alias='shortOiUsd')
    funding_per_hour_bps: float | None = Field(None, alias='fundingPerHourBps')
    funding_modeled: bool | None = Field(None, alias='fundingModeled')


class RegistryObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    address: str
    entries: list[RegistryEntryObservation]
    allowances: list[Allowance]
    stranded_unknown: list[StrandedHoldingObservation] = Field(
        ..., alias='strandedUnknown'
    )
    dropped: float


class GmxObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    markets: dict[str, GmxMarketObservation] | None = None
    market_price_usd: float = Field(..., alias='marketPriceUsd')
    position: GmxPositionObservation | None = None
    long_oi_usd: float | None = Field(None, alias='longOiUsd')
    short_oi_usd: float | None = Field(None, alias='shortOiUsd')
    funding_per_hour_bps: float | None = Field(None, alias='fundingPerHourBps')
    funding_modeled: bool | None = Field(None, alias='fundingModeled')


class ProtocolObservations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    uniswap: UniswapObservation | None = None
    balancer: AmmObservation | None = None
    curve: AmmObservation | None = None
    gmx: GmxObservation | None = None
    aave: AaveObservation | None = None
    lst: LstObservation | None = None
    liquity: LiquityObservation | None = None
    lending: LendingObservation | None = None


class AgentObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Literal['observation'] = 'observation'
    run_id: str = Field(..., alias='runId')
    round: float
    block_number: str = Field(..., alias='blockNumber')
    agent_address: str = Field(..., alias='agentAddress')
    fair_price_usdc_per_weth: float = Field(..., alias='fairPriceUsdcPerWeth')
    oracle_prices: OraclePrices = Field(..., alias='oraclePrices')
    fair_prices_usd: dict[str, float] | None = Field(None, alias='fairPricesUsd')
    base_balances: dict[str, str] | None = Field(None, alias='baseBalances')
    base_decimals: dict[str, float] | None = Field(None, alias='baseDecimals')
    markets: list[str] | None = None
    blocks_remaining: float | None = Field(None, alias='blocksRemaining')
    enabled_protocols: list[
        Literal[
            'uniswap', 'balancer', 'curve', 'gmx', 'aave', 'lst', 'liquity', 'lending'
        ]
    ] = Field(..., alias='enabledProtocols')
    balances: Balances
    inventory: Inventory
    history: list[HistoryItem]
    limits: Limits
    protocols: ProtocolObservations
    registry: RegistryObservation | None = None
    discovered_pools: list[DiscoveredPool] | None = Field(None, alias='discoveredPools')
    competition: Competition | None = None


class Model(RootModel[AgentObservation]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: AgentObservation
