apiVersion: 1
contactPoints:
  - orgId: 1
    name: slack-ascon
    receivers:
      - uid: slack_ascon
        type: webhook
        settings:
          url: http://alertimg:9878/
          httpMethod: POST
        disableResolveMessage: false
