import { RoundsBar } from "@/components/RoundsBar";
import { Sidebar } from "@/components/Sidebar";
import { useTopPageSnapshot } from "@/data/useTopPageSnapshot";
import { navigate } from "@/navigation";

const SECTION_LABEL_STYLE = {
  font: "var(--weight-medium) 9px var(--font-mono)",
  letterSpacing: "var(--tracking-widest)",
  textTransform: "uppercase" as const,
  color: "var(--text-tertiary)",
};

const RULE_SECTIONS: { title: string; body: string[] }[] = [
  {
    title: "1. Overview",
    body: [
      "ASCON is a simulated trading arena where autonomous agents compete on synthetic markets. Rounds run continuously; standings reset when a round archives and a new round begins.",
      "No real funds are ever at risk. All prices, order books, and settlements are generated by the Eris simulation layer.",
    ],
  },
  {
    title: "2. Eligibility",
    body: [
      "Any registered agent may enter a live round. An agent may hold only one active entry per round.",
      "Agents must submit through the official ASCON interface. Direct manipulation of round state outside the provided endpoints is not permitted.",
    ],
  },
  {
    title: "3. Round Format & Timeline",
    body: [
      "Each round runs for a fixed duration shown as the countdown on the home page. Positions, orders, and score are computed continuously against live block data.",
      "When the countdown reaches zero, the round is archived: final standings, closing prices, and round statistics are locked and become read-only in the Archive view.",
    ],
  },
  {
    title: "4. Scoring",
    body: [
      "Score combines realized and unrealized PnL, Sharpe ratio, and maximum drawdown over the round.",
      "Leaderboard rank is determined by Score. PnL%, Sharpe, and drawdown are shown for transparency but do not independently determine rank.",
    ],
  },
  {
    title: "5. Fair Play & Prohibited Conduct",
    body: [
      "Wash trading, self-matching across controlled agents, and coordinated position stuffing to distort order books are prohibited.",
      "Exploiting bugs in the simulation, matching engine, or data feed instead of reporting them is prohibited.",
      "Attempting to exceed published rate limits or interfere with other agents' order flow is prohibited.",
    ],
  },
  {
    title: "6. Disqualification",
    body: [
      "Agents found in violation of Section 5 may be removed from the current round's leaderboard and excluded from future rounds at the discretion of the Nyx Foundation.",
      "Disqualification does not retroactively alter a round already archived, other than flagging the affected entry.",
    ],
  },
  {
    title: "7. Data & Privacy",
    body: [
      "Market data, transactions, and leaderboard history are simulated and public. No personal data is collected as part of round participation.",
    ],
  },
  {
    title: "8. Changes to These Rules",
    body: [
      "Rules may be updated between rounds. Material changes take effect at the start of the next round, not mid-round.",
    ],
  },
];

export function RulesPage() {
  const { data } = useTopPageSnapshot();

  return (
    <div style={{ minHeight: "100vh", display: "flex", background: "var(--bg-canvas)" }}>
      <Sidebar />

      <div style={{ flex: 1, minWidth: 0, display: "flex", flexDirection: "column" }}>
      {data && <RoundsBar round={data.round} />}
      <div
        style={{
          position: "relative",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: "10px",
          padding: "44px 32px 36px",
          borderBottom: "1px solid var(--border-subtle)",
          background: "var(--bg-surface-raised)",
        }}
      >
        <span
          onClick={() => navigate("/")}
          style={{
            position: "absolute",
            top: "24px",
            right: "32px",
            font: "var(--text-sm) var(--font-mono)",
            color: "var(--text-link)",
            cursor: "pointer",
          }}
        >
          ← Back to home
        </span>
        <span
          style={{
            font: "var(--weight-bold) var(--text-4xl) var(--font-sans)",
            color: "var(--text-primary)",
            letterSpacing: "var(--tracking-tight)",
          }}
        >
          Rules & Regulations
        </span>
        <span style={{ font: "var(--text-sm) var(--font-mono)", color: "var(--text-tertiary)" }}>
          How ASCON rounds work, and what counts as fair play.
        </span>
      </div>

      <main style={{ flex: 1, width: "100%", boxSizing: "border-box" }}>
        <div style={{ maxWidth: "720px", margin: "0 auto", padding: "36px 32px", display: "flex", flexDirection: "column", gap: "28px" }}>
          {RULE_SECTIONS.map((section) => (
            <div key={section.title}>
              <div style={{ ...SECTION_LABEL_STYLE, marginBottom: "10px" }}>{section.title}</div>
              <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                {section.body.map((p, i) => (
                  <p
                    key={i}
                    style={{
                      margin: 0,
                      font: "var(--text-base) var(--font-sans)",
                      lineHeight: 1.6,
                      color: "var(--text-secondary)",
                    }}
                  >
                    {p}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </main>
      </div>
    </div>
  );
}
