// Contract layer for run config (ADR 0015). Placing the SimConfig type and the env→SimConfig
// loadConfig in the sdk lets both the environment (core) and the agent runtime
// (example/agents/runtime) rebuild identical config from the same YAML (ERIS_CONFIG).
//
// Environment-only config (stress/vuln event schedule definitions, the agent roster) is extended on
// the core side (RealtimeConfig / validateAgentsFile in core/src/config.ts).
import { keccak256, stringToBytes, type Hex } from "viem";
import {
  CHAIN_ID,
  DEFAULT_ANVIL_PRIVATE_KEYS,
  MAX_BUNDLE_ACTIONS,
} from "./constants.js";
import type { ProtocolId } from "./types.js";
import { baseTokens } from "./markets.js";

const ALL_PROTOCOLS: ProtocolId[] = [
  "uniswap",
  "balancer",
  "curve",
  "gmx",
  "aave",
];

export type SimConfig = {
  rpcUrl: string;
  chainId: number;
  // Upstream RPC to fork from (ARB_RPC_URL). When set, resetFork calls anvil_reset with a forking
  // config to rebuild the fork state clean each time (avoiding the anvil_reset [] problem where
  // positions such as Aave persist across runs/seeds). If unset, falls back to the legacy
  // anvil_reset [].
  forkUrl?: string;
  // Re-fork target block (FORK_BLOCK_NUMBER). Pinning it makes reruns fully reproducible.
  // If unset, the first resetFork captures latest and reuses it for subsequent resets.
  forkBlockNumber?: number;
  // Liquidation demo (GitHub #1). When ERIS_LIQUIDATION_DEMO=1, the coordinator has a victim wallet
  // open an over-leveraged Aave position, then from shockRound onward lowers the Aave WETH oracle to
  // push HF<1 and create a situation the liquidator agent can liquidate. Default off (existing runs/tests unchanged).
  liquidationDemo: boolean;
  liquidationShockBps: number; // WETH oracle drop amount (bps, default 1500=15%)
  liquidationShockRound: number; // round at which the drop begins (default 3)
  liquidationVictimSupplyWethWei: bigint; // WETH the victim supplies (default 5)
  // Seed-derived victim cohort that makes liquidations possible (WETH supply + USDC borrow, HF≈H0). Not scored.
  // count=0 (default) disables it. When >0, aave enabled + full re-fork (ARB_RPC_URL required) is a precondition (ADR 0009 §4).
  stressVictimCount: number; // ERIS_STRESS_VICTIM_COUNT
  stressVictimHf0: number; // ERIS_STRESS_VICTIM_HF0 (target initial HF. default 1.10. must exceed LT/(0.97·LTV)≈1.08)
  stressVictimSupplyWethWei: bigint; // ERIS_STRESS_VICTIM_WETH_WEI (supply per victim. default 5)
  // Approximate one-sided liquidity to seed each vuln pool with (in USDC-denominated units). The deeper it is,
  // the less an agent's trade moves the price, so the bait becomes realized profit. ERIS_VULN_POOL_LIQUIDITY_USDC_UNITS (default 2,000,000 USDC).
  vulnPoolLiquidityUsdcUnits: bigint;
  // Trading fee of the vuln pool (bps). Small enough that fees do not cancel out an honest pool's bait.
  // ERIS_VULN_POOL_FEE_BPS (default 30 = 0.3%).
  vulnPoolFeeBps: number;
  // Enables the pre-trade LLM source audit (ADR 0014 §4-2). "0" (default off) / "1" (real LLM) / "mock"
  // (a stub that scans source for keywords). The coordinator distributes it to discovery-arb-verify via ERIS_VULN_LLM.
  // Scoring uses the environment's ground truth, so the LLM is auxiliary (its verdict is a reference log). The dry-run is the primary check.
  vulnLlm: string;
  // Flash arb demo (GitHub #3). With ERIS_FLASH_ARB=1 the coordinator deploys the FlashArb contract
  // and makes it available to the flash-arb agent. Requires uniswap+balancer+aave enabled. Default off.
  flashArbDemo: boolean;
  rounds: number;
  roundTimeSeconds: number;
  // Real-time mode (core/src/realtime/coordinator.ts). The interval-mining block interval (seconds)
  // and the run's stop condition (wall-clock time or block count).
  blockTimeSec: number;
  runSeconds: number;
  runBlocks: number;
  // Skip the resetFork at run start (default false). Preserves anvil's fork fetch cache from the
  // previous run for diagnostics that isolate cold-fetch latency (upstream fetches during mining).
  // State persists from the previous run, so do not use for evaluation (ERIS_SKIP_RESET=1).
  skipReset: boolean;
  // Mode that uses a locally (non-fork) deployed anvil (ERIS_LOCAL_DEPLOY=1). With no fork, inter-run
  // reset uses evm_snapshot/evm_revert instead of anvil_reset. Addresses overlay
  // constants.local.ts (generated by gen:local-constants). With no fork upstream, pinning
  // FORK_BLOCK_NUMBER, whales, etc. are unnecessary.
  localDeploy: boolean;
  // Persistence file for the local-mode snapshot ID (shares the clean cross-section cross-process).
  localSnapshotFile: string;
  // The run's execution mode (a label stamped into summary.json's mode. ADR 0016 §6). The backtest CLI
  // injects ERIS_RUN_MODE=backtest. Does not affect scoring or behavior.
  runMode: "realtime" | "backtest";
  // Before the competition starts, run a market loop of N blocks with only the flow bot to warm the
  // protocols' working set (ADR 0006 Risks anvil cold-fetch mitigation). The competition-phase mine
  // then avoids hitting upstream fetches. 0 disables it (ERIS_PREWARM_BLOCKS).
  prewarmBlocks: number;
  seed: number;
  runDirRoot: string;
  agentTimeoutMs: number;
  agentsConfigPath: string;
  // Root of the agent directory convention (ADR 0015 §2/§6). A roster id corresponds to a directory
  // name directly under this, and spawn is always <agentsDir>/runtime/bot.ts (explicit command overrides).
  agentsDir: string;
  initialEthWei: bigint;
  flowEthWei: bigint;
  // Initial base inventory for the flow wallet (non-spread). Lets flow post "sells" (price down)
  // even under USDC-only = enables two-way drift. Not granted to agents (agents stay USDC-only/no-beta).
  // Default 0 = as before (flow also has no base).
  flowWethWei: bigint;
  flowBaseAmounts: Record<string, bigint>;
  initialWethWei: bigint;
  // ADR 0013: base symbol -> initial distribution amount (token units). WETH equals initialWethWei
  // for compatibility. Additional bases are read from INITIAL_<SYM>_<UNIT> (e.g. INITIAL_WBTC_SATS),
  // defaulting to 0 (USDC-only policy = additional bases granted none by default). Under the fork default (WETH only) it is the single entry {WETH:...}.
  initialBaseAmounts: Record<string, bigint>;
  initialUsdcUnits: bigint;
  defaultPriorityFeeWei: bigint;
  maxPriorityFeeWei: bigint;
  // Turn gas into an economic cost (ADR 0011, supersedes ADR 0010). When true, retire priority-fee
  // cap enforcement and move the environment's price finalization from mempool txs (cap+premium
  // ordering) to a direct storage write of the PriceFeed/Aave oracles (cheatcode), making it
  // cap-independent. Agents freely stack priority fee per their opportunity assessment, and whoever
  // values it highest fills first (realistic priority gas auction). Default false fully reproduces
  // the ADR 0010 profile (the rollback target). Per-run switch (ERIS_ECONOMIC_GAS).
  economicGas: boolean;
  maxAgentWethInWei: bigint;
  maxAgentUsdcInUnits: bigint;
  // ADR 0013: base symbol -> per-round swap cap (token units). WETH equals maxAgentWethInWei for
  // compatibility. Additional bases are MAX_AGENT_<SYM>_<UNIT> (e.g. MAX_AGENT_WBTC_IN_SATS).
  // Unset is 0 (= no per-round cap on that base; limits work is out of scope for Phase 8).
  maxAgentBaseIn: Record<string, bigint>;
  maxBundleActions: number;
  maxLpWethWei: bigint;
  maxLpUsdcUnits: bigint;
  // ADR 0013: base symbol -> LP mint cap. WETH equals maxLpWethWei for compatibility.
  // Additional bases are MAX_LP_<SYM>_<UNIT> (e.g. MAX_LP_WBTC_SATS). Unset is 0.
  maxLpBase: Record<string, bigint>;
  maxOpenPositions: number;
  uninformedFlowMaxWethWei: bigint;
  // Uninformed flow count per block per venue (default 1). >1 gives hybrid alpha.
  uninformedFlowCount: number;
  // How many blocks the uninformed direction persists (default 1). >1 mimics order-flow imbalance and naturally produces a spread.
  uninformedFlowPersistBlocks: number;
  informedFlowMaxWethWei: bigint;
  enabledProtocols: ProtocolId[];
  maxGmxSizeUsd: bigint;
  maxAaveSupplyWethWei: bigint;
  // ADR 0013: base symbol -> Aave supply cap. WETH equals maxAaveSupplyWethWei for compatibility.
  // Additional bases are MAX_AAVE_SUPPLY_<SYM>_<UNIT> (e.g. MAX_AAVE_SUPPLY_WBTC_SATS). Unset is 0.
  maxAaveSupplyBase: Record<string, bigint>;
  maxAaveBorrowUsdcUnits: bigint;
  balancerFlowMaxWethWei: bigint;
  curveFlowMaxWethWei: bigint;
  gmxFlowMaxSizeUsd: bigint;
  // Per-block probability of emitting gmx flow (0..1, default 0.5). Sent sporadically.
  gmxFlowActivityProb: number;
  // Max number of gmx orders emitted on a firing block (>=1, default 2). >1 bursts 1..N randomly.
  gmxFlowMaxBurst: number;
  aaveFlowMaxWethWei: bigint;
  // Per-block probability each aave flow actor acts (0..1, default 0.5). <1 makes it intermittent.
  aaveFlowActivityProb: number;
  // Number of independent actors in the aave borrower pool (>=1, default 4). Max simultaneous borrows per block = this value.
  // Each actor keeps a persistent position at its own address, and debt remains into subsequent blocks.
  aaveFlowActorCount: number;
  // ADR 0015 Notes / amm-challenge: threshold (bps) that makes informed (arbitrage) flow fee-aware.
  // Default 30bps = on (emit informed flow only when the gap exceeds the fee band, and only for the
  // excess; the remainder = fee. Same economics as real arbitrage, so the market is not over-tightened).
  // 0 reverts to the legacy gap-linear informed flow.
  informedArbFeeBps: number;
  // ADR 0015 Notes / amm-challenge retail: Poisson(λ) uninformed arrivals with lognormal sizes.
  // Default λ=0.9 = on (count per block is Poisson(λ), each size is lognormal (mean = uninformedMax×0.5,
  // σ=uninformedFlowSizeSigma) = bursty, heavy-tailed realistic flow). 0 reverts to the legacy fixed count + uniform.
  // Note: variance rises, so read run comparisons as an aggregate over multiple seeds.
  uninformedFlowArrivalRate: number;
  uninformedFlowSizeSigma: number;
  // Extends amm-challenge retail to GMX/Aave.
  // gmxFlowArrivalRate: >0 makes GMX open counts Poisson(λ) and sizes lognormal (default 0.75=on). 0 = legacy.
  // gmxFlowSizeSigma: σ of the GMX lognormal size (default 1.0).
  // aaveFlowActorSizeSigma: >0 makes each Aave actor's target collateral lognormal-heterogeneous (whale/minnow. default 1.0).
  gmxFlowArrivalRate: number;
  gmxFlowSizeSigma: number;
  aaveFlowActorSizeSigma: number;
  // ADR 0013: per-leg AMM flow cap for non-WETH bases (base units). Empty/0 default = WBTC flow off.
  baseFlowMax: Record<string, bigint>;
  // Launch command and deterministic seed for the orderflow bot (a separate process).
  flowBotCommand: string;
  flowBotArgs: string[];
  flowSeed: number;
  privateKeys: {
    agent0: Hex;
    agent1: Hex;
    agent2: Hex;
    agent3: Hex;
    agent4: Hex;
    agent5: Hex;
    agent6: Hex;
    uninformedFlow: Hex;
    informedFlow: Hex;
    setup: Hex;
    admin: Hex;
    keeper: Hex;
  };
};

export function loadConfig(env = process.env): SimConfig {
  const anvilPort = env.ANVIL_PORT ?? "8545";
  // Under economization (ADR 0011), squeeze the endowment to make gas a real cost. If INITIAL_ETH_WEI
  // is unset, default to a modest placeholder (3 ETH) (makes gas a meaningful cost against opportunity
  // value while the runtime gas manager + lower-bound validation prevent running out of gas). The final
  // value is decided by calibration measurement (ADR "not yet decided"). The default 0010 profile
  // (economicGas=false) stays at 100 ETH unchanged.
  const economicGas = env.ERIS_ECONOMIC_GAS === "1";
  const initialEthWeiDefault = economicGas
    ? 3_000_000_000_000_000_000n
    : 100_000_000_000_000_000_000n;
  // Existing WETH env value (read once here for compatibility and reused for the per-base map's WETH entry).
  const initialWethWei = bigintEnv(
    env.INITIAL_WETH_WEI,
    10_000_000_000_000_000_000n,
  );
  const maxAgentWethInWei = bigintEnv(
    env.MAX_AGENT_WETH_IN_WEI,
    1_000_000_000_000_000_000n,
  );
  const maxLpWethWei = bigintEnv(
    env.MAX_LP_WETH_WEI,
    1_000_000_000_000_000_000n,
  );
  const maxAaveSupplyWethWei = bigintEnv(
    env.MAX_AAVE_SUPPLY_WETH_WEI,
    5_000_000_000_000_000_000n,
  );
  return {
    rpcUrl: env.ANVIL_RPC_URL ?? `http://127.0.0.1:${anvilPort}`,
    chainId: intEnv(env.CHAIN_ID, CHAIN_ID),
    forkUrl:
      env.ARB_RPC_URL && env.ARB_RPC_URL.trim() !== ""
        ? env.ARB_RPC_URL.trim()
        : undefined,
    forkBlockNumber:
      env.FORK_BLOCK_NUMBER && env.FORK_BLOCK_NUMBER.trim() !== ""
        ? intEnv(env.FORK_BLOCK_NUMBER, 0)
        : undefined,
    liquidationDemo: env.ERIS_LIQUIDATION_DEMO === "1",
    liquidationShockBps: intEnv(env.ERIS_LIQUIDATION_SHOCK_BPS, 1500),
    liquidationShockRound: intEnv(env.ERIS_LIQUIDATION_SHOCK_ROUND, 3),
    liquidationVictimSupplyWethWei: bigintEnv(
      env.ERIS_LIQUIDATION_VICTIM_WETH_WEI,
      5_000_000_000_000_000_000n,
    ),
    stressVictimCount: intEnv(env.ERIS_STRESS_VICTIM_COUNT, 0),
    stressVictimHf0: floatEnv(env.ERIS_STRESS_VICTIM_HF0, 1.1),
    stressVictimSupplyWethWei: bigintEnv(
      env.ERIS_STRESS_VICTIM_WETH_WEI,
      5_000_000_000_000_000_000n,
    ),
    vulnPoolLiquidityUsdcUnits: bigintEnv(
      env.ERIS_VULN_POOL_LIQUIDITY_USDC_UNITS,
      2_000_000_000_000n,
    ),
    vulnPoolFeeBps: intEnv(env.ERIS_VULN_POOL_FEE_BPS, 30),
    vulnLlm: env.ERIS_VULN_LLM ?? "0",
    flashArbDemo: env.ERIS_FLASH_ARB === "1",
    rounds: intEnv(env.ROUNDS, 50),
    // EVM time to advance per round (seconds). Passed to evm_increaseTime in the round loop so that
    // Aave variable-rate accrual and GMX funding occur at a realistic scale.
    roundTimeSeconds: intEnv(env.ROUND_TIME_SECONDS, 3600),
    // Real-time mode settings.
    blockTimeSec: intEnv(env.ERIS_BLOCK_TIME_SEC, 2),
    runSeconds: intEnv(env.ERIS_RUN_SECONDS, 20),
    runBlocks: intEnv(env.ERIS_RUN_BLOCKS, 0),
    skipReset: env.ERIS_SKIP_RESET === "1",
    localDeploy: env.ERIS_LOCAL_DEPLOY === "1",
    localSnapshotFile: env.ERIS_LOCAL_SNAPSHOT_FILE ?? ".local-snapshot",
    runMode: env.ERIS_RUN_MODE === "backtest" ? "backtest" : "realtime",
    prewarmBlocks: intEnv(env.ERIS_PREWARM_BLOCKS, 0),
    seed: intEnv(env.SEED, 1),
    runDirRoot: env.REPORT_DIR ?? "./runs",
    agentTimeoutMs: intEnv(env.AGENT_TIMEOUT_MS, 5000),
    agentsConfigPath: env.AGENTS_CONFIG ?? "config/example.yaml",
    agentsDir: env.ERIS_AGENTS_DIR ?? "example/agents",
    initialEthWei: bigintEnv(env.INITIAL_ETH_WEI, initialEthWeiDefault),
    // Background orderflow is environment machinery, not a competitor. Give it
    // ample gas so long runs do not silently lose market flow as wallets run dry.
    flowEthWei: bigintEnv(
      env.ERIS_FLOW_ETH_WEI,
      1_000_000_000_000_000_000_000n,
    ),
    flowWethWei: bigintEnv(env.FLOW_WETH_WEI, 0n),
    flowBaseAmounts: readBaseAmounts(env, "FLOW_BASE", {}),
    initialWethWei,
    initialBaseAmounts: readBaseAmounts(env, "INITIAL", {
      WETH: initialWethWei,
    }),
    initialUsdcUnits: bigintEnv(env.INITIAL_USDC_UNITS, 25_000_000_000n),
    defaultPriorityFeeWei: bigintEnv(
      env.DEFAULT_PRIORITY_FEE_WEI,
      100_000_000n,
    ),
    maxPriorityFeeWei: bigintEnv(env.MAX_PRIORITY_FEE_WEI, 5_000_000_000n),
    economicGas,
    maxAgentWethInWei,
    maxAgentUsdcInUnits: bigintEnv(env.MAX_AGENT_USDC_IN_UNITS, 5_000_000_000n),
    // The per-round swap cap for additional bases is MAX_AGENT_<SYM>_IN_<UNIT> (WETH reuses the existing WEI value).
    maxAgentBaseIn: readBaseAmounts(
      env,
      "MAX_AGENT",
      { WETH: maxAgentWethInWei },
      "IN",
    ),
    maxBundleActions: intEnv(env.MAX_BUNDLE_ACTIONS, MAX_BUNDLE_ACTIONS),
    maxLpWethWei,
    maxLpUsdcUnits: bigintEnv(env.MAX_LP_USDC_UNITS, 5_000_000_000n),
    maxLpBase: readBaseAmounts(env, "MAX_LP", { WETH: maxLpWethWei }),
    maxOpenPositions: intEnv(env.MAX_OPEN_POSITIONS, 10),
    uninformedFlowMaxWethWei: bigintEnv(
      env.UNINFORMED_FLOW_MAX_WETH_WEI,
      1_000_000_000_000_000_000n,
    ),
    uninformedFlowCount: intEnv(env.UNINFORMED_FLOW_COUNT, 1),
    uninformedFlowPersistBlocks: intEnv(env.UNINFORMED_FLOW_PERSIST_BLOCKS, 1),
    informedFlowMaxWethWei: bigintEnv(
      env.INFORMED_FLOW_MAX_WETH_WEI,
      2_000_000_000_000_000_000n,
    ),
    enabledProtocols: parseEnabledProtocols(env.ENABLED_PROTOCOLS),
    maxGmxSizeUsd: bigintEnv(env.MAX_GMX_SIZE_USD, 50_000n * 10n ** 30n),
    maxAaveSupplyWethWei,
    maxAaveSupplyBase: readBaseAmounts(env, "MAX_AAVE_SUPPLY", {
      WETH: maxAaveSupplyWethWei,
    }),
    maxAaveBorrowUsdcUnits: bigintEnv(
      env.MAX_AAVE_BORROW_USDC_UNITS,
      5_000_000_000n,
    ),
    balancerFlowMaxWethWei: bigintEnv(
      env.BALANCER_FLOW_MAX_WETH_WEI,
      1_000_000_000_000_000_000n,
    ),
    curveFlowMaxWethWei: bigintEnv(
      env.CURVE_FLOW_MAX_WETH_WEI,
      1_000_000_000_000_000_000n,
    ),
    gmxFlowMaxSizeUsd: bigintEnv(
      env.GMX_FLOW_MAX_SIZE_USD,
      20_000n * 10n ** 30n,
    ),
    // Per-block probability of emitting gmx flow (default 0.5). Decided each block via rng, sent sporadically.
    gmxFlowActivityProb: floatEnv(env.GMX_FLOW_ACTIVITY_PROB, 0.5),
    // Max number of gmx orders emitted on a firing block (default 2). Bursts 1..N randomly.
    gmxFlowMaxBurst: intEnv(env.GMX_FLOW_MAX_BURST, 2),
    aaveFlowMaxWethWei: bigintEnv(
      env.AAVE_FLOW_MAX_WETH_WEI,
      2_000_000_000_000_000_000n,
    ),
    // Per-block probability each aave flow actor acts (default 0.5). <1 makes it intermittent.
    aaveFlowActivityProb: floatEnv(env.AAVE_FLOW_ACTIVITY_PROB, 0.5),
    // Number of independent actors in the aave borrower pool (default 4). Max simultaneous borrows per block = this value.
    aaveFlowActorCount: Math.max(1, intEnv(env.AAVE_FLOW_ACTOR_COUNT, 4)),
    // amm-challenge arbitrage fee boundary (default 30bps = on. Real arbitrage does not take a gap
    // below the fee; matched to the venue fee ~30bps). 0 disables it = revert to the legacy gap-linear informed flow.
    informedArbFeeBps: Math.max(0, intEnv(env.ERIS_INFORMED_ARB_FEE_BPS, 30)),
    // amm-challenge retail arrivals (default λ=0.9 = on. Poisson arrivals + lognormal sizes = bursty,
    // heavy-tailed realistic flow. Calibrated to roughly the same mean as the legacy fixed count). 0 disables it = revert to fixed count + uniform.
    uninformedFlowArrivalRate: Math.max(
      0,
      floatEnv(env.ERIS_UNINFORMED_ARRIVAL_RATE, 0.9),
    ),
    uninformedFlowSizeSigma: Math.max(
      0,
      floatEnv(env.ERIS_UNINFORMED_SIZE_SIGMA, 1),
    ),
    // Extends amm-challenge retail to GMX/Aave (default on. 0 reverts to legacy behavior).
    gmxFlowArrivalRate: Math.max(0, floatEnv(env.ERIS_GMX_ARRIVAL_RATE, 0.75)),
    gmxFlowSizeSigma: Math.max(0, floatEnv(env.ERIS_GMX_SIZE_SIGMA, 1)),
    aaveFlowActorSizeSigma: Math.max(
      0,
      floatEnv(env.ERIS_AAVE_ACTOR_SIZE_SIGMA, 1),
    ),
    // ADR 0013: per-leg AMM flow cap for non-WETH bases (base units). env FLOW_MAX_<SYM>_<UNIT>
    // (e.g. FLOW_MAX_WBTC_SATS). Default 0 = flow off for WBTC etc. → extraBases do not consume RNG = byte-compatible.
    // WETH flow keeps using uninformed/balancer/curve FlowMaxWethWei (not listed here).
    baseFlowMax: readBaseAmounts(env, "FLOW_MAX", { WETH: 0n }),
    flowBotCommand: env.FLOW_BOT_COMMAND ?? "node",
    flowBotArgs:
      env.FLOW_BOT_ARGS && env.FLOW_BOT_ARGS.trim() !== ""
        ? env.FLOW_BOT_ARGS.trim().split(/\s+/)
        : ["--import", "tsx", "core/src/flow/market-maker.ts"],
    // Seed for the flow bot. If unset, use the same as SEED so a single SEED determines the whole run.
    flowSeed: intEnv(env.FLOW_SEED, intEnv(env.SEED, 1)),
    privateKeys: {
      agent0: hexEnv(env.AGENT0_PRIVATE_KEY, DEFAULT_ANVIL_PRIVATE_KEYS[0]),
      agent1: hexEnv(env.AGENT1_PRIVATE_KEY, DEFAULT_ANVIL_PRIVATE_KEYS[1]),
      agent2: hexEnv(env.AGENT2_PRIVATE_KEY, DEFAULT_ANVIL_PRIVATE_KEYS[2]),
      agent3: hexEnv(env.AGENT3_PRIVATE_KEY, DEFAULT_ANVIL_PRIVATE_KEYS[3]),
      agent4: hexEnv(env.AGENT4_PRIVATE_KEY, DEFAULT_ANVIL_PRIVATE_KEYS[4]),
      agent5: hexEnv(env.AGENT5_PRIVATE_KEY, DEFAULT_ANVIL_PRIVATE_KEYS[5]),
      agent6: hexEnv(env.AGENT6_PRIVATE_KEY, DEFAULT_ANVIL_PRIVATE_KEYS[6]),
      uninformedFlow: hexEnv(
        env.FLOW_UNINFORMED_PRIVATE_KEY,
        DEFAULT_ANVIL_PRIVATE_KEYS[7],
      ),
      informedFlow: hexEnv(
        env.FLOW_INFORMED_PRIVATE_KEY,
        DEFAULT_ANVIL_PRIVATE_KEYS[8],
      ),
      setup: hexEnv(env.SETUP_PRIVATE_KEY, DEFAULT_ANVIL_PRIVATE_KEYS[9]),
      admin: hexEnv(env.ADMIN_PRIVATE_KEY, deriveRoleKey("admin")),
      keeper: hexEnv(env.KEEPER_PRIVATE_KEY, deriveRoleKey("keeper")),
    },
  };
}

function parseEnabledProtocols(value: string | undefined): ProtocolId[] {
  if (!value || value.trim() === "") return [...ALL_PROTOCOLS];
  const ids = value
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean) as ProtocolId[];
  const invalid = ids.filter((id) => !ALL_PROTOCOLS.includes(id));
  if (invalid.length > 0)
    throw new Error(
      `unknown protocol in ENABLED_PROTOCOLS: ${invalid.join(", ")}`,
    );
  return ids;
}

function deriveRoleKey(role: string): Hex {
  return keccak256(stringToBytes(`eris-role:${role}`));
}

function intEnv(value: string | undefined, fallback: number): number {
  if (value === undefined || value === "") return fallback;
  const parsed = Number(value);
  if (!Number.isInteger(parsed))
    throw new Error(`Expected integer env value, got ${value}`);
  return parsed;
}

function floatEnv(value: string | undefined, fallback: number): number {
  if (value === undefined || value === "") return fallback;
  const parsed = Number(value);
  if (!Number.isFinite(parsed))
    throw new Error(`Expected numeric env value, got ${value}`);
  return parsed;
}

function bigintEnv(value: string | undefined, fallback: bigint): bigint {
  if (value === undefined || value === "") return fallback;
  return BigInt(value);
}

// ADR 0013: unit suffix (derived from decimals) for a base symbol's "amount env".
// WETH(18)=WEI / WBTC(8)=SATS / otherwise=UNITS. New tokens are determined automatically by their decimals.
export function unitSuffixFor(decimals: number): string {
  if (decimals === 18) return "WEI";
  if (decimals === 8) return "SATS";
  return "UNITS";
}

// ADR 0013: build a base symbol -> amount Record from env (for per-base distribution / per-base limits).
// WETH uses wethSeed's value directly and does not read env (the existing WETH env is already read once
// on the caller side = keeps byte compatibility). Additional bases are read from the env key
//   <prefix>[_<SYM>]<_INFIX?>_<UNIT>   e.g. INITIAL_WBTC_SATS / MAX_AGENT_WBTC_IN_SATS
// defaulting to 0n (USDC-only policy = additional bases granted none / capped none by default).
// Under the fork default (WETH only) it is the single entry {WETH: wethSeed.WETH}, matching the old behavior exactly.
function readBaseAmounts(
  env: NodeJS.ProcessEnv,
  prefix: string,
  wethSeed: Record<string, bigint>,
  infix?: string,
): Record<string, bigint> {
  const out: Record<string, bigint> = {};
  for (const t of baseTokens()) {
    if (t.symbol === "WETH") {
      out.WETH = wethSeed.WETH ?? 0n;
      continue;
    }
    const unit = unitSuffixFor(t.decimals);
    const key = [prefix, t.symbol, infix, unit].filter(Boolean).join("_");
    out[t.symbol] = bigintEnv(env[key], 0n);
  }
  return out;
}

function hexEnv(value: string | undefined, fallback: string): Hex {
  const result = value && value.length > 0 ? value : fallback;
  if (!/^0x[0-9a-fA-F]{64}$/.test(result))
    throw new Error("Private key must be a 0x-prefixed 32-byte hex string");
  return result as Hex;
}
