// AUTO-GENERATED by scripts/genLocalConstants.ts — do not edit by hand.
// Input: deployer/deployments/deployments.json
// Deterministic addresses from deploying all protocols to a local (non-fork) anvil.
// constants.ts overlays these only when ERIS_LOCAL_DEPLOY=1.
import type { Address } from "viem";
import type { MarketLegs } from "./types.js";

// Canonical fingerprint of the source deployments.json (ADR 0016 §2). The backtest CLI
// compares it against the state dump manifest and, on mismatch, regenerates from the manifest's bundled deployments.
export const DEPLOYMENTS_FINGERPRINT = "sha256:597e433f9db6d7da4daa89155b4dfff7d5c1de7d27e0edd3903747c83d840bcd";

export type LocalDeployment = {
  CHAIN_ID: number;
  TOKENS: {
    WETH: { address: Address; decimals: number };
    USDC: { address: Address; decimals: number };
    WBTC?: { address: Address; decimals: number };
    DAI?: { address: Address; decimals: number };
  };
  USDC_VARIANTS: { native: Address; bridged: Address; usdt: Address };
  // Issue #27 (c): stables the deploy gave a market, so the scorer prices them from it instead of
  // asserting $1. Keyed by registry symbol. eUSD is not here -- its market comes from LIQUITY.
  STABLE_MARKETS?: Record<
    string,
    { pool: Address; stableIndex: number; quoteIndex: number }
  >;
  UNISWAP: {
    poolWethUsdc500: Address;
    swapRouter: Address;
    nonfungiblePositionManager: Address;
    quoterV2: Address;
    fee: number;
    tickSpacing: number;
  };
  MULTICALL3: Address;
  BALANCER: {
    vault: Address;
    queries: Address;
    pool: Address;
    poolId: `0x${string}`;
    tokens: Address[];
    usdcToken: Address;
    seedWethWei: bigint;
  };
  CURVE: { pool: Address; wethIndex: number; usdtIndex: number; usdcToken: Address };
  GMX: {
    RoleStore: Address; DataStore: Address; Oracle: Address; EventEmitter: Address;
    Router: Address; ExchangeRouter: Address; OrderHandler: Address; OrderVault: Address;
    LiquidationHandler: Address; Reader: Address; Config: Address;
  };
  GMX_MARKETS: { ETH_USD: Address };
  AAVE: {
    PoolAddressesProvider: Address; Pool: Address; AaveOracle: Address;
    AclAdmin: Address; AclManager: Address; PoolDataProvider: Address;
  };
  // ADR 0013: multi-asset market legs (WBTC etc.). Includes the WBTC leg if WBTC is in deployments.json.
  MARKET_LEGS?: MarketLegs;
  // Issue #38: present only when the deploy included the lst venue.
  LST?: {
    vault: Address;
    lstToken: Address;
    asset: Address;
    pool: Address;
    poolLstIndex: number;
    poolWethIndex: number;
    simulatedSecondsPerBlock: number;
    targetApyBps: number;
    withdrawalDelayBlocks: number;
    aaveAggregator?: Address;
    aaveAToken?: Address;
    aaveVariableDebtToken?: Address;
  };
  // Issue #39: present only when the deploy included the liquity venue.
  LIQUITY?: {
    troveManager: Address;
    borrowerOperations: Address;
    stabilityPool: Address;
    sortedTroves: Address;
    activePool: Address;
    defaultPool: Address;
    collSurplusPool: Address;
    gasPool: Address;
    hintHelpers: Address;
    priceFeed: Address;
    redemptionHelper?: Address;
    eusd: Address;
    lqtyToken: Address;
    lqtyStaking: Address;
    communityIssuance: Address;
    eusdUsdcPool?: Address;
    eusdIndex?: number;
    usdcIndex?: number;
    stable?: Address;
  };
};

export const LOCAL_DEPLOYMENT: LocalDeployment | null = {
  CHAIN_ID: 31337,
  TOKENS: {
    WETH: { address: "0x4806ddDB48da9285EED230C907075861a50A75f4" as Address, decimals: 18 },
    USDC: { address: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address, decimals: 6 },
    WBTC: { address: "0x1645E05b9061D79D47f208D1f3A6E8DA20800e07" as Address, decimals: 8 },
    DAI: { address: "0xF02dd180B9a072c84C5e34207307c7cbD4Ec4D43" as Address, decimals: 18 },
  },
  STABLE_MARKETS: {
    DAI: { pool: "0x84a0Ed603A6E58EE30A7B458E199384F22Df7E8F" as Address, stableIndex: 1, quoteIndex: 0 },
  },
  // Local uses a single USDC/USDT. native/bridged are the same USDC; usdt maps to USDT.
  USDC_VARIANTS: {
    native: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
    bridged: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
    usdt: "0x40436167B0f97399d2B786fE5f054A586707dd1C" as Address,
  },
  UNISWAP: {
    poolWethUsdc500: "0x24f7f1744a9fF6Da261bd6FCa8Ceda8cdbbCd73d" as Address,
    swapRouter: "0x0f958dC97eabC0774006E45781dCbCEaCBCBdF2f" as Address,
    nonfungiblePositionManager: "0xa7A0a6aC6d14f4965D4474bb269f290383e5642d" as Address,
    quoterV2: "0x9B7e0263A354329AA97eAc09A6843EC3191d93E8" as Address,
    // The deployer's WETH/USDC pool is fee=3000 (0.3%) / tickSpacing=60.
    fee: 3000,
    tickSpacing: 60,
  },
  MULTICALL3: "0x138dcaD3D08FdfC3C8652955b8c29DD02Ea070BC" as Address,
  BALANCER: {
    vault: "0x648Bff5787113E9930b9d033A65F0522b52486Bd" as Address,
    queries: "0x16fBf19Bb2429D2D93CB22646A7401E0D67b15eE" as Address,
    pool: "0x238A6a17807cfd8a5ccB231e43f8CC446ecB679d" as Address,
    poolId: "0x238a6a17807cfd8a5ccb231e43f8cc446ecb679d000200000000000000000000" as `0x${string}`,
    // The deployer pool is 2 tokens [WETH, USDC] (80/20). There is no USDT leg.
    tokens: ["0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address, "0x4806ddDB48da9285EED230C907075861a50A75f4" as Address],
    usdcToken: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
    seedWethWei: 100_000_000_000_000_000_000n,
  },
  // Curve: twocrypto-ng's WETH/USDC crypto pool (uint256 index get_dy/exchange).
  // coin0=USDC(stable)=0, coin1=WETH=1. usdcToken is the pool's stable=USDC.
  CURVE: {
    pool: "0x276BB5F80718eE31A29e75c7247ff455e719565A" as Address,
    wethIndex: 1,
    usdtIndex: 0,
    usdcToken: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
  },
  GMX: {
    RoleStore: "0x32C310A5Aaf599C5F2d716B51407a5DDDf8964BD" as Address,
    DataStore: "0xF51a10A191Ba0b1857478F905be65A9d2DD12696" as Address,
    Oracle: "0xFe7B33310992e658D7791758839D3460F85187Ef" as Address,
    EventEmitter: "0x7c6F8b352B4f6844DdbdA01AdBEE825ec6C94649" as Address,
    Router: "0xd9109d6891fC320F8D49E7887453F11efB504306" as Address,
    ExchangeRouter: "0xcd907E3C54D2f2824c3DC22516fF0c7a6b171e64" as Address,
    OrderHandler: "0xcA189BaC851f04a4A73a3750d2f66B68193d53C7" as Address,
    OrderVault: "0x463254070D3f1618286767dca64C8E9336cBa776" as Address,
    LiquidationHandler: "0xfa1dd08a5597C87b19D664959aecdC60D843887f" as Address,
    Reader: "0x4116C64494b4C359Ee3209f6C8ACde257432f9B6" as Address,
    Config: "0x44e78b4FEcfF638Fda37d737Bd08C3843007608B" as Address,
  },
  GMX_MARKETS: { ETH_USD: "0x20B275813A9048bE8B29A8dC73FCD9EdC7b2A10F" as Address },
  AAVE: {
    PoolAddressesProvider: "0x313147967b7E6753BE7D732A3a69C7a8832962Fc" as Address,
    Pool: "0x2978556fFBF5946f3A6e08174FCB29939206157F" as Address,
    AaveOracle: "0xc83C05e35DE2d621f1AB332ECe7b0F14a9f3F3c3" as Address,
    AclAdmin: "0x3d05E3979a2dB7E8980B3A5Aa0D535c442676fBF" as Address,
    AclManager: "0x2D79fb26DD50395B06bCCdF17D1F5fBF7E4dB538" as Address,
    PoolDataProvider: "0x28Cf22d66CbABbf622e00aBB140fF152C3FFF1D7" as Address,
  },
  // Issue #38: the LST venue (wstETH-style vault + LST/WETH stableswap-ng secondary market).
  LST: {
    vault: "0x1917f4727A7Cc440B0AB2ac55A87c0Bd4A0C265c" as Address,
    lstToken: "0x1917f4727A7Cc440B0AB2ac55A87c0Bd4A0C265c" as Address,
    asset: "0x4806ddDB48da9285EED230C907075861a50A75f4" as Address,
    pool: "0x31125021cdB3978C3d60e546Ad4C36c7BCDDA3E3" as Address,
    poolLstIndex: 1,
    poolWethIndex: 0,
    simulatedSecondsPerBlock: 3600,
    targetApyBps: 300,
    withdrawalDelayBlocks: 24,
    aaveAggregator: "0xcB6AC54Fa67cab9040168456c062A0B47a084F67" as Address,
    aaveAToken: "0xD2255a60e1741C1f589dCCd331B369AD37CeeB76" as Address,
    aaveVariableDebtToken: "0x098dA64fDCCFF6a9aEd6f5FaF869DAE13b8B5689" as Address,
  },
  // Issue #39: Liquity V1 as the CDP stablecoin venue (eUSD). priceFeed is the adapter Liquity holds
  // forever, which each run repoints at its own PriceFeed -- not the run's feed itself.
  LIQUITY: {
    troveManager: "0x580a815b04ebfb9CC2d5840046d0b31f3BEc469d" as Address,
    borrowerOperations: "0xA2a8d1cFf69ea6279199C678C1977d8c5F882650" as Address,
    stabilityPool: "0x471157c23dE505D6Bcc7708B72B858F1719f94bD" as Address,
    sortedTroves: "0x2026283B8acB4419e325e639841B23c0dBb7153E" as Address,
    activePool: "0xd1edeA127D1bd9FCA6d291dDF543E4d3DE9A27E4" as Address,
    defaultPool: "0xdF2Fa95A51060FF34a9464B8E1A004Bd3fbb3845" as Address,
    collSurplusPool: "0x0Ef27DF1F5d7B8Dfde6E92bc34f8b59C4D7f52DA" as Address,
    gasPool: "0x5d09ccD6E6aD250E81d1D7AE70F5dA49f52f273F" as Address,
    hintHelpers: "0xeb33828d2640e183709e79f03F2bb48c65742C22" as Address,
    priceFeed: "0x1ea9Fa5faf998C144d86bd1436E433E5ebe3c348" as Address,
    redemptionHelper: "0xd34B0AaE77a55F6F58AD76292Ff7B1Dd0C0226C8" as Address,
    eusd: "0x1473b34f6feDBe32818Af2b61736F4dc347465e5" as Address,
    lqtyToken: "0x74bA59d93701ebEDbA85a3adAd70Ef77004Ac1A1" as Address,
    lqtyStaking: "0x642002a1a7D516fFB66AdFA9933f5c531140823e" as Address,
    communityIssuance: "0x982F3b800bA59e6aF7a6B60a2807AeA382A18442" as Address,
    eusdUsdcPool: "0x7c4a04d249D48f09861C18c491F83E7f40553De9" as Address,
    eusdIndex: 0,
    usdcIndex: 1,
    stable: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
  },
  MARKET_LEGS: {
    uniswap: {
      WETH: { pool: "0x24f7f1744a9fF6Da261bd6FCa8Ceda8cdbbCd73d" as Address, fee: 3000, tickSpacing: 60 },
      WBTC: { pool: "0x4778Ff4D4aa83eBf9826AE607a73df31b50CAC30" as Address, fee: 3000, tickSpacing: 60 },
    },
    balancer: {
      WETH: { poolId: "0x238a6a17807cfd8a5ccb231e43f8cc446ecb679d000200000000000000000000" as `0x${string}`, tokens: ["0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address, "0x4806ddDB48da9285EED230C907075861a50A75f4" as Address], stable: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address },
      WBTC: { poolId: "0xba3a907b7b11b7758c70f742ef3a175afe69bcda000200000000000000000001" as `0x${string}`, tokens: ["0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address, "0x1645E05b9061D79D47f208D1f3A6E8DA20800e07" as Address], stable: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address },
    },
    curve: {
      WETH: { pool: "0x276BB5F80718eE31A29e75c7247ff455e719565A" as Address, baseIndex: 1, quoteIndex: 0, stable: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address },
      WBTC: { pool: "0x9515781BA89F19875BC514838684ff48A0d8C872" as Address, baseIndex: 1, quoteIndex: 0, stable: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address },
    },
    gmx: {
      WETH: { market: "0x20B275813A9048bE8B29A8dC73FCD9EdC7b2A10F" as Address },
      WBTC: { market: "0xF61d8b8D80208E72B716bD405C9a25AF361B4A18" as Address },
    },
    aave: {
      WETH: {},
      WBTC: {},
    },
  },
};
