// AUTO-GENERATED by scripts/genLocalConstants.ts — 手で編集しない。
// 入力: /Users/tomo/nyx/eris-competition-poc/deployer/deployments/deployments.json
// ローカル(非fork)anvil に全 protocol をデプロイした際の決定論アドレス。
// constants.ts が ERIS_LOCAL_DEPLOY=1 のときだけ overlay する。
import type { Address } from "viem";
import type { MarketLegs } from "./types.js";

export type LocalDeployment = {
  CHAIN_ID: number;
  TOKENS: {
    WETH: { address: Address; decimals: number };
    USDC: { address: Address; decimals: number };
    WBTC?: { address: Address; decimals: number };
  };
  USDC_VARIANTS: { native: Address; bridged: Address; usdt: Address };
  UNISWAP: {
    poolWethUsdc500: Address;
    swapRouter: Address;
    nonfungiblePositionManager: Address;
    quoterV2: Address;
    fee: number;
    tickSpacing: number;
  };
  MULTICALL3: Address;
  BALANCER: {
    vault: Address;
    queries: Address;
    pool: Address;
    poolId: `0x${string}`;
    tokens: Address[];
    usdcToken: Address;
    seedWethWei: bigint;
    seedUsdcUnits: bigint;
    seedUsdtUnits: bigint;
  };
  CURVE: { pool: Address; wethIndex: number; usdtIndex: number; usdcToken: Address };
  GMX: {
    RoleStore: Address; DataStore: Address; Oracle: Address; EventEmitter: Address;
    Router: Address; ExchangeRouter: Address; OrderHandler: Address; OrderVault: Address;
    LiquidationHandler: Address; Reader: Address; Config: Address;
  };
  GMX_MARKETS: { ETH_USD: Address };
  AAVE: {
    PoolAddressesProvider: Address; Pool: Address; AaveOracle: Address;
    AclAdmin: Address; AclManager: Address; PoolDataProvider: Address;
  };
  // ADR 0013: マルチアセット market leg（WBTC 等）。WBTC が deployments.json にあれば WBTC leg を含む。
  MARKET_LEGS?: MarketLegs;
};

export const LOCAL_DEPLOYMENT: LocalDeployment | null = {
  CHAIN_ID: 31337,
  TOKENS: {
    WETH: { address: "0x5FbDB2315678afecb367f032d93F642f64180aa3" as Address, decimals: 18 },
    USDC: { address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address, decimals: 6 },
    WBTC: { address: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853" as Address, decimals: 8 },
  },
  // ローカルは単一 USDC/USDT。native/bridged は同一 USDC、usdt は USDT に対応。
  USDC_VARIANTS: {
    native: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
    bridged: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
    usdt: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9" as Address,
  },
  UNISWAP: {
    poolWethUsdc500: "0xe35086d02782CEC7D20b1a164dE141aa39CEe723" as Address,
    swapRouter: "0x0B306BF915C4d645ff596e518fAf3F9669b97016" as Address,
    nonfungiblePositionManager: "0x9A676e781A523b5d0C0e43731313A708CB607508" as Address,
    quoterV2: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1" as Address,
    // deployer の WETH/USDC プールは fee=3000(0.3%) / tickSpacing=60。
    fee: 3000,
    tickSpacing: 60,
  },
  MULTICALL3: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788" as Address,
  BALANCER: {
    vault: "0x09635F643e140090A9A8Dcd712eD6285858ceBef" as Address,
    queries: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933" as Address,
    pool: "0xf0D7de80A1C242fA3C738b083C422d65c6c7ABF1" as Address,
    poolId: "0xf0d7de80a1c242fa3c738b083c422d65c6c7abf1000200000000000000000000" as `0x${string}`,
    // deployer プールは [WETH, USDC] の 2 トークン (80/20)。USDT leg は無い。
    tokens: ["0x5FbDB2315678afecb367f032d93F642f64180aa3" as Address, "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address],
    usdcToken: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
    seedWethWei: 100_000_000_000_000_000_000n,
    seedUsdcUnits: 50_000_000_000n,
    seedUsdtUnits: 0n,
  },
  // Curve: twocrypto-ng の WETH/USDC crypto pool (uint256 index get_dy/exchange)。
  // coin0=USDC(stable)=0, coin1=WETH=1。usdcToken は pool の stable=USDC。
  CURVE: {
    pool: "0x9FA5072032B7a7DCc49533401cec1C47bfcf350d" as Address,
    wethIndex: 1,
    usdtIndex: 0,
    usdcToken: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
  },
  GMX: {
    RoleStore: "0x0000000000000000000000000000000000000000" as Address,
    DataStore: "0x0000000000000000000000000000000000000000" as Address,
    Oracle: "0x0000000000000000000000000000000000000000" as Address,
    EventEmitter: "0x0000000000000000000000000000000000000000" as Address,
    Router: "0x0000000000000000000000000000000000000000" as Address,
    ExchangeRouter: "0x0000000000000000000000000000000000000000" as Address,
    OrderHandler: "0x0000000000000000000000000000000000000000" as Address,
    OrderVault: "0x0000000000000000000000000000000000000000" as Address,
    LiquidationHandler: "0x0000000000000000000000000000000000000000" as Address,
    Reader: "0x0000000000000000000000000000000000000000" as Address,
    Config: "0x0000000000000000000000000000000000000000" as Address,
  },
  GMX_MARKETS: { ETH_USD: "0x0000000000000000000000000000000000000000" as Address },
  AAVE: {
    PoolAddressesProvider: "0x367761085BF3C12e5DA2Df99AC6E1a824612b8fb" as Address,
    Pool: "0x985ab7E0663EbfF2E0F523f975D7D5A81bB9E42d" as Address,
    AaveOracle: "0x22753E4264FDDc6181dc7cce468904A80a363E44" as Address,
    AclAdmin: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" as Address,
    AclManager: "0xc96304e3c037f81dA488ed9dEa1D8F2a48278a75" as Address,
    PoolDataProvider: "0x49fd2BE640DB2910c2fAb69bB8531Ab6E76127ff" as Address,
  },
  MARKET_LEGS: {
    uniswap: {
      WETH: { pool: "0xe35086d02782CEC7D20b1a164dE141aa39CEe723" as Address, fee: 3000, tickSpacing: 60 },
      WBTC: { pool: "0x1B99e1798C19F366b750819eDdfA27d77476cdaC" as Address, fee: 3000, tickSpacing: 60 },
    },
    balancer: {
      WETH: { poolId: "0xf0d7de80a1c242fa3c738b083c422d65c6c7abf1000200000000000000000000" as `0x${string}`, tokens: ["0x5FbDB2315678afecb367f032d93F642f64180aa3" as Address, "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address], stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address },
      WBTC: { poolId: "0x1a7a3e29c3c4b3c858f2ded8be6ed51a07589ecf000200000000000000000001" as `0x${string}`, tokens: ["0xa513E6E4b8f2a923D98304ec87F64353C4D5C853" as Address, "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address], stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address },
    },
    curve: {
      WETH: { pool: "0x9FA5072032B7a7DCc49533401cec1C47bfcf350d" as Address, baseIndex: 1, quoteIndex: 0, stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address },
      WBTC: { pool: "0x37B37064d97eADAcc4d7A0cbC673b5C2932b673c" as Address, baseIndex: 1, quoteIndex: 0, stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address },
    },
    gmx: {
      WETH: { market: "0x0000000000000000000000000000000000000000" as Address },
    },
    aave: {
      WETH: {},
      WBTC: {},
    },
  },
};
