import type { Address } from "viem";
import type { MarketLegs, ProtocolId, TokenSymbol } from "./types.js";
import { LOCAL_DEPLOYMENT } from "./constants.local.js";

// ---------------------------------------------------------------------------
// Arbitrum One. Runs all protocols on a single fork.
// Addresses ported from anvil-oracle-fork/bot/src/config.ts and bot/src/aave/config.ts.
//
// When ERIS_LOCAL_DEPLOY=1, overlay the locally deployed addresses from the bundled deployer/
// (constants.local.ts generated by scripts/genLocalConstants.ts).
// Otherwise (fork), use the Arbitrum defaults below.
// ---------------------------------------------------------------------------

const L = process.env.ERIS_LOCAL_DEPLOY === "1" ? LOCAL_DEPLOYMENT : null;

export const CHAIN_ID = L?.CHAIN_ID ?? 42161;

// TokenSymbol is unified to the single definition in types.ts (=string, ADR 0013). Re-exported for
// existing code that imports it via constants.
export type { TokenSymbol };

// ADR 0013: token registry. The Record<symbol,...> type annotation permits index access by
// TokenSymbol (=string). Under local-deploy the overlay adds WBTC etc.
export const TOKENS: Record<string, { address: Address; decimals: number }> = {
  ...(L?.TOKENS ?? {
    WETH: {
      address: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1" as Address,
      decimals: 18,
    },
    USDC: {
      address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831" as Address,
      decimals: 6,
    },
  }),
  // Issue #27 (b): eUSD is a registry stable, priced from its own market rather than at $1. It is
  // issued by a venue instead of deployed as a run token, so it is picked up from the liquity
  // deployment rather than from the deployer's token table. #39 kept it out of the registry only
  // because the registry priced stables at par -- STABLE_MARKET_LEGS below is what dissolves that.
  // The symbol is uppercase like every other one: it is an action field (`stableSwap.stable`), and
  // actionSchema's tokenSymbol rejects mixed case so a prompt-mode typo comes back as a validation
  // error instead of dying at send time. `liquitySwapEusd` already spells it "EUSD".
  ...(L?.LIQUITY?.eusd
    ? { EUSD: { address: L.LIQUITY.eusd, decimals: 18 } }
    : {}),
};

// Unified stable accounting: native USDC / USDC.e / USDT(USD₮0) are all treated as 6-decimal "USDC-equivalent" worth $1.
// On Arbitrum the deep Balancer/Curve WETH/stable pools are USDC.e / USDT pairs, so we use a
// different stable per venue while summing balances and PnL.
export const USDC_VARIANTS = L?.USDC_VARIANTS ?? {
  native: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831" as Address,
  bridged: "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8" as Address, // USDC.e
  usdt: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9" as Address, // USD₮0
};

export function tokenAddress(symbol: TokenSymbol): Address {
  return TOKENS[symbol].address;
}

export function tokenDecimals(symbol: TokenSymbol): number {
  return TOKENS[symbol].decimals;
}

export function oppositeToken(symbol: TokenSymbol): TokenSymbol {
  return symbol === "WETH" ? "USDC" : "WETH";
}

// Look up the per-venue stable balance. Falls back to usdcUnits when there is no stables map, which
// is the right answer for the fork's USDC-equivalents and the only one available for a snapshot
// assembled without one.
export function stableBalanceOf(
  balances: { usdcUnits: bigint; stables?: Record<string, bigint> },
  token: Address,
): bigint {
  return balances.stables?.[token.toLowerCase()] ?? balances.usdcUnits;
}

// ---------------------------------------------------------------------------
// Market-priced stables (issue #27). A stable listed here is worth what its pool pays, not $1; the
// pricing rules live in stables.ts. A stable *not* listed is the USDC-equivalent dollar -- USDC by
// definition (the numéraire), and the fork's USDC.e / USD₮0 for want of a pool to quote them.
// ---------------------------------------------------------------------------
export type StableMarketLeg = {
  pool: Address; // curve stableswap-ng
  stableIndex: number;
  quoteIndex: number;
  // The protocol whose being enabled brings this stable into the run. A stable nobody can trade is
  // worse than absent: it would be swept, probed and reported every block while no action could
  // touch it. eUSD comes with the CDP that issues it; a plain stable comes with the venue that owns
  // its pool, which is where `stableSwap` lives.
  venue: ProtocolId;
};

function buildStableMarketLegs(): Record<TokenSymbol, StableMarketLeg> {
  const out: Record<TokenSymbol, StableMarketLeg> = {};
  // eUSD's market is part of the liquity deployment, not a standalone venue leg.
  const liquity = L?.LIQUITY;
  if (
    liquity?.eusdUsdcPool &&
    liquity.eusdIndex !== undefined &&
    liquity.usdcIndex !== undefined
  ) {
    out.EUSD = {
      pool: liquity.eusdUsdcPool,
      stableIndex: liquity.eusdIndex,
      quoteIndex: liquity.usdcIndex,
      venue: "liquity",
    };
  }
  // Issue #27 (c): stables the deployer seeded a stableswap pool for. Those pools come off the
  // Curve factory, and the curve adapter is what can trade them.
  for (const [symbol, leg] of Object.entries(L?.STABLE_MARKETS ?? {})) {
    out[symbol] = { ...leg, venue: "curve" };
  }
  return out;
}

export const STABLE_MARKET_LEGS: Record<TokenSymbol, StableMarketLeg> =
  buildStableMarketLegs();

export function symbolForAddress(addr: Address): TokenSymbol | undefined {
  const lower = addr.toLowerCase();
  if (lower === TOKENS.WETH.address.toLowerCase()) return "WETH";
  if (lower === TOKENS.USDC.address.toLowerCase()) return "USDC";
  return undefined;
}

// ---------------------------------------------------------------------------
// Uniswap V3 (Arbitrum). SwapRouter(v1)/NPM/QuoterV2 share the same addresses as mainnet.
// WETH/USDC(native) 0.05% pool. Confirm it exists at the fork block.
// Note: on Arbitrum WETH(0x82aF) < USDC(0xaf88), so token0=WETH, token1=USDC.
// ---------------------------------------------------------------------------
export const UNISWAP = L?.UNISWAP ?? {
  poolWethUsdc500: "0xC6962004f452bE9203591991D15f6b388e09E8D0" as Address,
  swapRouter: "0xE592427A0AEce92De3Edee1F18E0157C05861564" as Address,
  nonfungiblePositionManager:
    "0xC36442b4a4522E871399CD717aBDD847Ab11FE88" as Address,
  quoterV2: "0x61fFE014bA17989E743c5F6cB21bF9697530B21e" as Address,
  fee: 500,
  tickSpacing: 10,
};

// Multicall3. On the fork (Arbitrum) it is the standard deployment shared across all chains. Locally,
// overlay the address the deployer placed. Used for batched reads of a historical block cross-section (ADR 0006 §4).
export const MULTICALL3 =
  L?.MULTICALL3 ?? ("0xcA11bde05977b3631167028862bE2a173976CA11" as Address);

export const WETH_USDC_FEE = UNISWAP.fee;
export const WETH_USDC_TICK_SPACING = UNISWAP.tickSpacing;
export const WETH_DECIMALS = 18;
export const USDC_DECIMALS = 6;

// ---------------------------------------------------------------------------
// Balancer v2. 33/33/34 weighted pool [WETH, native USDC, USDT] (poolId confirmed).
// It is depleted at the fork block, so setupGlobal has admin joinPool to seed it.
// The stable used is native USDC (which is in the pool).
// ---------------------------------------------------------------------------
export const BALANCER = L?.BALANCER ?? {
  vault: "0xBA12222222228d8Ba445958a75a0704d566BF2C8" as Address,
  queries: "0xE39B5e3B6D74016b2F6A9673D7d7493B6DF549d5" as Address,
  pool: "0x3b106b7ae88c3f8869b5221d2bbae398afc26737" as Address,
  poolId:
    "0x3b106b7ae88c3f8869b5221d2bbae398afc26737000100000000000000000534" as `0x${string}`,
  // Token order as registered in the Vault (per getPoolTokens)
  tokens: [
    "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1", // WETH
    "0xaf88d065e77c8cC2239327C5EDb3A432268e5831", // native USDC
    "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9", // USDT
  ] as Address[],
  usdcToken: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831" as Address,
  // Depth of the admin join, on the WETH leg only. The stable legs used to be constants too, which
  // pinned the seeded pool at ETH~$2100 and made every fork run fail the startup no-arb check as
  // spot drifted away from it (issue #43); they are now derived from the live price at setup.
  seedWethWei: 200_000_000_000_000_000_000n, // 200 WETH
};

// ---------------------------------------------------------------------------
// Curve (Arbitrum) tricrypto 0x960ea3: coins [USDT(0), WBTC(1), WETH(2)] (deep).
// Only the WETH<->USDT leg is used. The stable is USDT.
// ---------------------------------------------------------------------------
export const CURVE = L?.CURVE ?? {
  pool: "0x960ea3e3C7FB317332d990873d354E18d7645590" as Address,
  wethIndex: 2,
  usdtIndex: 0,
  usdcToken: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9" as Address, // USDT
};

// ---------------------------------------------------------------------------
// GMX v2 (gmx-synthetics) Arbitrum One deployment addresses
// ---------------------------------------------------------------------------
export const GMX = L?.GMX ?? {
  RoleStore: "0x3c3d99FD298f679DBC2CEcd132b4eC4d0F5e6e72" as Address,
  DataStore: "0xFD70de6b91282D8017aA4E741e9Ae325CAb992d8" as Address,
  Oracle: "0x7F01614cA5198Ec979B1aAd1DAF0DE7e0a215BDF" as Address,
  EventEmitter: "0xC8ee91A54287DB53897056e12D9819156D3822Fb" as Address,
  Router: "0x7452c558d45f8afC8c83dAe62C3f8A5BE19c71f6" as Address,
  ExchangeRouter: "0x1C3fa76e6E1088bCE750f23a5BFcffa1efEF6A41" as Address,
  OrderHandler: "0x63492B775e30a9E6b4b4761c12605EB9d071d5e9" as Address,
  OrderVault: "0x31eF83a530Fde1B38EE9A18093A333D8Bbbc40D5" as Address,
  LiquidationHandler: "0xaf157Eb8e2398A8E1Fc1dA929974652b9ba9BC25" as Address,
  Reader: "0x470fbC46bcC0f16532691Df360A07d8Bf5ee0789" as Address,
  Config: "0x0BBbbF9D0cbdE8069e926c859E530B00Bfe90072" as Address,
};

export const GMX_MARKETS = L?.GMX_MARKETS ?? {
  ETH_USD: "0x70d95587d40A2caf56bd97485aB3Eec10Bee6336" as Address, // ETH/USD [WETH-USDC]
};

// ---------------------------------------------------------------------------
// Aave v3 (Arbitrum)
// ---------------------------------------------------------------------------
export const AAVE = L?.AAVE ?? {
  PoolAddressesProvider:
    "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb" as Address,
  Pool: "0x794a61358D6845594F94dc1DB02A252b5b4814aD" as Address,
  AaveOracle: "0xb56c2F0B653B2e0b10C9b928C8580Ac5Df02C7C7" as Address,
  AclAdmin: "0xFF1137243698CaA18EE364Cc966CF0e02A4e6327" as Address,
  AclManager: "0xa72636CbcAa8F5FF95B2cc47F3CDEe83F3294a0B" as Address,
  PoolDataProvider: "0x243Aa95cAC2a25651eda86e80bEe66114413c43b" as Address,
};

// ---------------------------------------------------------------------------
// LST venue (issue #38). A wstETH-style vault plus its LST/WETH stableswap-ng secondary market.
//
// Unlike the other venues there is no Arbitrum counterpart to point at: the vault is ours, deployed
// by the bundled deployer and baked into the ADR 0016 state dump. So this is null on a fork, and a
// run that enables the lst protocol without local deploy fails fast rather than reading zeros.
// ---------------------------------------------------------------------------
export type LstDeployment = {
  vault: Address;
  // The vault is its own share token (non-rebasing wstETH model), so this equals `vault`. Kept
  // separate because nothing else should have to know that.
  lstToken: Address;
  asset: Address; // WETH
  pool: Address; // LST/WETH stableswap-ng
  poolLstIndex: number;
  poolWethIndex: number;
  // Deploy-time economic clock, reported so a run can say what it inherited (a run may retune it).
  simulatedSecondsPerBlock: number;
  targetApyBps: number;
  withdrawalDelayBlocks: number;
  // Issue #38 phase 3: present when the LST is listed as Aave collateral. Absent when the deploy
  // had no Aave, in which case the venue still works and only leverage is unavailable.
  aaveAggregator?: Address;
  aaveAToken?: Address;
  aaveVariableDebtToken?: Address;
};

export const LST: LstDeployment | null = L?.LST ?? null;

export function requireLst(): LstDeployment {
  if (!LST)
    throw new Error(
      "the lst venue is not deployed in this environment: it exists only under local deploy " +
        "(run.localDeploy: true with a state dump / deployer that includes lst). Drop lst from run.protocols to use a fork.",
    );
  return LST;
}

// ---------------------------------------------------------------------------
// Liquity V1 as the CDP stablecoin venue, issuing eUSD (issue #39).
//
// Like the LST vault this has no Arbitrum counterpart to point at -- the core is deployed by the
// bundled deployer and baked into the ADR 0016 state dump -- so it is null on a fork and a run that
// enables the liquity protocol without local deploy fails fast rather than reading zeros.
//
// eUSD is deliberately absent from TOKENS. Registering it as a stable would price it at $1 in the
// scorer's spot sweep, which is exactly the phantom value a depegged CDP stablecoin must not be
// credited with; the adapter marks it at what the market would pay instead (see TokenKind).
// ---------------------------------------------------------------------------
export type LiquityDeployment = {
  troveManager: Address;
  borrowerOperations: Address;
  stabilityPool: Address;
  sortedTroves: Address;
  activePool: Address;
  defaultPool: Address;
  collSurplusPool: Address;
  gasPool: Address;
  hintHelpers: Address;
  // Computes a redemption's hints inside the transaction that uses them. Liquity checks a partial
  // redemption against a hint derived from the execution price, and this environment moves the
  // oracle every block, so an off-chain hint is stale before it lands (see the contract's notes).
  // Absent on a deployment that predates it, in which case redemption is unavailable rather than
  // silently reverting.
  redemptionHelper?: Address;
  // The LiquityPriceFeedAdapter, not the run's PriceFeed: Liquity renounces ownership, so the
  // address baked into TroveManager is permanent and each run repoints this one at its own feed.
  priceFeed: Address;
  eusd: Address;
  lqtyToken: Address;
  lqtyStaking: Address;
  communityIssuance: Address;
  // The eUSD/USDC stableswap-ng market. Absent when the deploy had no curve factory to host it, in
  // which case the venue still works and only the peg has nowhere to trade.
  eusdUsdcPool?: Address;
  eusdIndex?: number;
  usdcIndex?: number;
  // The pool's stable leg, which is the run's USDC.
  stable?: Address;
};

export const LIQUITY: LiquityDeployment | null = L?.LIQUITY ?? null;

export function requireLiquity(): LiquityDeployment {
  if (!LIQUITY)
    throw new Error(
      "the liquity venue is not deployed in this environment: it exists only under local deploy " +
        "(issue #39). Drop liquity from run.protocols to use a fork.",
    );
  return LIQUITY;
}

// The redemption helper, or a fail-fast naming what to do about it. Redemption is the venue's
// headline trade, so "the deployment has no helper" must not read as "the redemption failed".
export function requireRedemptionHelper(): Address {
  const l = requireLiquity();
  if (!l.redemptionHelper) {
    throw new Error(
      "this liquity deployment has no LiquityRedemptionHelper: redemptions need their hints " +
        "computed at execution (the oracle moves every block), so redeem it through a deployment " +
        "that includes it — redeploy with `cd deployer && npm run deploy -- --keep-fresh`.",
    );
  }
  return l.redemptionHelper;
}

// The eUSD market, or a fail-fast when the deploy produced none. Kept separate from the deployment
// because a Trove and the Stability Pool work without a market -- only the peg needs one.
export function requireEusdMarket(): {
  pool: Address;
  eusdIndex: number;
  usdcIndex: number;
  stable: Address;
} {
  const l = requireLiquity();
  if (
    !l.eusdUsdcPool ||
    l.eusdIndex === undefined ||
    l.usdcIndex === undefined ||
    !l.stable
  ) {
    throw new Error(
      "the liquity deployment has no eUSD/USDC market: the deploy ran without a curve factory to " +
        "host it (deployer/src/protocols/liquity.ts seedEusdPool). Redeploy with curve enabled.",
    );
  }
  return {
    pool: l.eusdUsdcPool,
    eusdIndex: l.eusdIndex,
    usdcIndex: l.usdcIndex,
    stable: l.stable,
  };
}

// ---------------------------------------------------------------------------
// Market leg registry (ADR 0013). Venue-specific leg per protocol × base.
// The fork default is WETH/USDC only (built from the existing venue constants). Under local-deploy,
// genLocalConstants overlays a MARKET_LEGS that adds WBTC etc. (L?.MARKET_LEGS).
// markets.ts assembles this into MarketConfig, which the adapters drive. New tokens are added by adding a leg.
// ---------------------------------------------------------------------------
export const MARKET_LEGS: MarketLegs = L?.MARKET_LEGS ?? {
  uniswap: {
    WETH: {
      pool: UNISWAP.poolWethUsdc500,
      fee: UNISWAP.fee,
      tickSpacing: UNISWAP.tickSpacing,
    },
  },
  balancer: {
    WETH: {
      poolId: BALANCER.poolId,
      tokens: BALANCER.tokens,
      stable: BALANCER.usdcToken,
    },
  },
  curve: {
    WETH: {
      pool: CURVE.pool,
      baseIndex: CURVE.wethIndex,
      quoteIndex: CURVE.usdtIndex,
      stable: CURVE.usdcToken,
    },
  },
  gmx: {
    WETH: { market: GMX_MARKETS.ETH_USD },
  },
  aave: {
    WETH: {},
  },
};

// ---------------------------------------------------------------------------
// Whales for sourcing USDC (tried in order for whichever has a balance at the fork block)
// ---------------------------------------------------------------------------
export const WHALES = {
  USDC: [
    "0x47c031236e19d024b42f8AE6780E44A573170703",
    "0x8b8149dd385955DC1cE77a4bE7700CCD6a212e65",
    "0x489ee077994B6658eAfA855C308275EAd8097C4A",
  ] as Address[],
} as const;

export const DEFAULT_ANVIL_PRIVATE_KEYS = [
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
  "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
  "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
  "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6",
  "0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a",
  "0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba",
  "0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e",
  "0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356",
  "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97",
  "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6",
] as const;
