// participant backtest CLI + competition scenario runner (ADR 0016 B1 realtime replay, ADR 0017 §3).
//
//   npm run backtest -- --regime <name> --seed <N> [--agents <roster>] [--repeat N]
//   npm run backtest -- --scenarios config/scenarios/public.yaml [--agents <roster>] [--metric ...]
//                       [--port 8547] [--state backtest/state] [--keep-anvil]
//                       [--blocks N] [--seconds N] [--protocols a,b] [--score-every N]
//
// Starts one anvil with the distributed state dump loaded (generated by gen:state-dump) and replays
// scenarios through the existing coordinator. A scenario is (regime, seed): the regime YAML holds the
// market conditions and the seed picks the realization, so the seed is passed in rather than baked
// into the regime (ADR 0017 §1).
//
// Every scenario is snapshot -> run -> reconstruct -> revert on that same anvil, which is what makes
// "no forking, many runs a day on one devnet" work: resetFork's evm_snapshot/evm_revert gives each
// run a clean slice, and scoring reconstruction finishes before the next revert erases the history
// it reads.
//
// With --scenarios the whole matrix is replayed and two artifacts are written:
//   matrix.json    raw per-scenario, per-agent scores (both netPnlUsdc and alphaUsdc)
//   standings.json the ranking derived from them (regime-internal z-score, equal weight per regime)
// The ranking is a derived view on purpose: the scoring rule is expected to change, and matrix.json
// is what lets it be recomputed without re-running anything (ADR 0017 §4).
//
// Dependency-light for the same reason as sim-realtime.ts: before importing sdk/constants we must set
// ERIS_LOCAL_DEPLOY=1 and finish syncing the constants.local.ts fingerprint. The coordinator is
// dynamically imported last.
import { spawn, type ChildProcess } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, join, resolve } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import {
  computeStandings,
  scenarioId,
  type AgentScore,
  type ScenarioResult,
} from "../backtest/standings.js";
import {
  gitHead,
  isAnvilUp,
  missingVenues,
  parseFlags,
  readConstantsFingerprint,
  readStateManifest,
  resolveRegimePath,
  rpc,
  STATE_DIR_DEFAULT,
  waitUntilAnvilUp,
} from "../backtest/shared.js";
import {
  AGENT_STATE_ROOT_ENV,
  restoreAllAgentState,
  snapshotAllAgentState,
} from "../realtime/agentState.js";

const ROOT = process.cwd(); // npm scripts run at the repo root

const USAGE = `usage: npm run backtest -- (--regime <name|path> --seed <N> | --scenarios <path>) [options]
  --regime <name|path>   config/regimes/<name>.yaml (or a YAML path). requires --seed
  --seed <N>             the scenario's seed. regimes no longer carry one (ADR 0017 §1)
  --scenarios <path>     scenario set to replay as a matrix, in one of two shapes:
                           { regimes: [...], seeds: [...] }         the cartesian product, run in that order
                           { k?: N, epochs: [{ s?, regime, seed }] }  an ordered plan (npm run competition -- plan)
                         each scenario is one epoch of the rules; the standings are the deviation score (§4.4)
  --agents <roster>      replace the regime's default agents with a roster file (YAML/JSON)
  --repeat <N>           repeat each scenario N times (calibration diagnostic; standings take the median P. default 1)
  --port <N>             port for the backtest-only anvil (default 8547)
  --state <dir>          state dump directory (default ${STATE_DIR_DEFAULT})
  --keep-anvil           keep anvil running after exit (for debugging)
  --agent-sandbox <process|docker>
                         how agents are launched. The official regimes say docker (the rules §2.3 caps live there);
                         pass process for a local run without docker
  --agent-state-root <d> carry each agent's persistent state across the scenarios of the run, in the
                         order they are listed — which for a plan from npm run competition -- plan
                         is the competition's own epoch order (issue #77). Off by default; without
                         it every scenario restarts each agent at version 0
  --blocks/--seconds/--protocols/--economic-gas/--score-every
                         one-off overrides of regime values (for smoke tests. runs you read results from use regime defaults)`;

type AgentSummary = {
  id: string;
  baseline?: boolean;
  // Rules §4.4.1's P, off the epoch boundaries (coordinator; absent on a run recorded before it).
  pnlUsdc?: number;
  alphaUsdc?: number;
  netPnlUsdc?: number;
  initialValueUsdc?: number;
  finalValueUsdc?: number;
  processExitedEarly?: string;
  unloggedTxCount?: number;
};
type RunSummary = {
  runDir: string;
  blocksProcessed?: number;
  agents: AgentSummary[];
  violations: Array<{ ownerId?: string }>;
};

function readRunSummary(runDir: string): RunSummary | undefined {
  const path = join(runDir, "summary.json");
  if (!existsSync(path)) return undefined;
  const parsed = JSON.parse(readFileSync(path, "utf8")) as {
    blocksProcessed?: number;
    agents?: AgentSummary[];
    violations?: Array<{ ownerId?: string }>;
  };
  return {
    runDir,
    blocksProcessed: parsed.blocksProcessed,
    agents: parsed.agents ?? [],
    violations: parsed.violations ?? [],
  };
}

// summary.json -> one epoch's P per agent (rules §4.4.1), plus the facts a reader should see next
// to it. Nothing here disqualifies: after the 2026-09-06 amendment a stopped agent is scored on what
// it left behind (§2.3, §4.4.2), and a §8 matter is the operator's to judge. An agent the summary
// does not know at all was not placed in the epoch, so it carries no P and is not in the population.
function scoresFromSummary(
  summary: RunSummary,
  expectedAgentIds: string[],
): AgentScore[] {
  const offenders = new Set(
    summary.violations
      .map((v) => v.ownerId)
      .filter((id): id is string => typeof id === "string"),
  );
  const reported = new Map(summary.agents.map((a) => [a.id, a]));
  const ids =
    expectedAgentIds.length > 0 ? expectedAgentIds : [...reported.keys()];
  return ids.map((id) => {
    const agent = reported.get(id);
    if (!agent)
      return { id, flags: ["absent from summary.json (was not placed)"] };
    const flags: string[] = [];
    if (offenders.has(id))
      flags.push("priority fee cap violation (rules §8; for the operator to judge)");
    if (agent.processExitedEarly !== undefined)
      flags.push(`process exited early: ${agent.processExitedEarly}`);
    if ((agent.unloggedTxCount ?? 0) > 0)
      flags.push(
        `${agent.unloggedTxCount} on-chain tx(s) absent from the agent's submitted log`,
      );
    // P off the epoch boundaries when the run recorded it; a run from before that field marks both
    // ends at the final prices, which differs by a per-run constant and is said so.
    const pnl: Pick<AgentScore, "pnlUsdc" | "pnlSource"> =
      agent.pnlUsdc !== undefined
        ? { pnlUsdc: agent.pnlUsdc, pnlSource: "epoch-boundaries" }
        : agent.netPnlUsdc !== undefined
          ? { pnlUsdc: agent.netPnlUsdc, pnlSource: "endpoints" }
          : {};
    if (pnl.pnlUsdc === undefined) flags.push("no P in summary.json");
    return {
      id,
      ...pnl,
      netPnlUsdc: agent.netPnlUsdc,
      alphaUsdc: agent.alphaUsdc,
      baseline: agent.baseline ?? false,
      // The endpoints behind P, so a stored matrix can be rescored after the run directory is gone.
      ...(agent.initialValueUsdc !== undefined
        ? { initialValueUsdc: agent.initialValueUsdc }
        : {}),
      ...(agent.finalValueUsdc !== undefined
        ? { finalValueUsdc: agent.finalValueUsdc }
        : {}),
      ...(flags.length > 0 ? { flags } : {}),
    };
  });
}

// Fold N repeats of one scenario into a single per-agent record by picking, for each agent, the
// repeat whose ranking metric is the median and reporting *that repeat's whole record*.
//
// Not a per-metric median: taking the median of netPnlUsdc and of alphaUsdc independently can report
// a pair that no single run produced, and then the run directory recorded alongside explains
// neither. Since --repeat exists so a calibration number can be traced back to a run, the reported
// numbers have to come from one.
function foldRepeats(runs: AgentScore[][]): AgentScore[] {
  if (runs.length === 1) return runs[0];
  const ids: string[] = [];
  for (const run of runs)
    for (const a of run) if (!ids.includes(a.id)) ids.push(a.id);
  return ids.map((id) => {
    const entries = runs
      .map((run) => run.find((a) => a.id === id))
      .filter((a): a is AgentScore => a !== undefined);
    // A flag raised in any repeat is kept: the failure is a property of the agent, and letting a
    // lucky repeat wash it out would defeat the point of recording it.
    const flags = [...new Set(entries.flatMap((a) => a.flags ?? []))];
    const scored = entries.filter(
      (a) => typeof a.pnlUsdc === "number" && Number.isFinite(a.pnlUsdc),
    );
    const chosen =
      scored.length > 0
        ? scored.sort((a, b) => (a.pnlUsdc as number) - (b.pnlUsdc as number))[
            Math.floor((scored.length - 1) / 2)
          ]
        : entries[0];
    return {
      ...chosen,
      id,
      ...(flags.length > 0 ? { flags } : {}),
    };
  });
}

// Sync constants.local.ts with the deployments bundled in the state manifest (ADR 0016 §2).
// On mismatch, extract deployments from the manifest and regenerate; if it still doesn't match,
// the state dump and repo version are a mismatched combination -> fail-fast.
async function syncConstants(
  manifestFingerprint: string,
  deployments: Record<string, unknown>,
  stateDirAbs: string,
): Promise<void> {
  const constantsPath = resolve(ROOT, "sdk", "src", "constants.local.ts");
  const current = readConstantsFingerprint(constantsPath);
  if (current === manifestFingerprint) return;
  console.error(
    `[backtest] constants.local.ts fingerprint does not match the state manifest ` +
      `(${current ?? "(none)"} != ${manifestFingerprint}). Regenerating from the deployments bundled in the manifest`,
  );
  const extracted = join(stateDirAbs, "deployments.extracted.json");
  writeFileSync(extracted, `${JSON.stringify(deployments, null, 2)}\n`);
  // genLocalConstants depends only on node builtins + viem + backtest/shared (it doesn't evaluate
  // sdk/constants), so it's fine to import before the coordinator.
  const { generateLocalConstants } =
    await import("../../../scripts/genLocalConstants.js");
  const { fingerprint } = generateLocalConstants(extracted);
  if (fingerprint !== manifestFingerprint)
    throw new Error(
      `fingerprint still doesn't match after regenerating constants.local.ts ` +
        `(${fingerprint} != ${manifestFingerprint}). Check the combination of the state dump and repo ` +
        `versions (ADR 0016 §2 fail-fast)`,
    );
}

// One cell of the evaluation matrix. `<regime>#<seed>` is the address used in every report
// (ADR 0017 §1); the regime supplies the market conditions and the seed picks the realization.
// `s` is the scheduled ordinal (rules §4.4.1): the epoch's weight is a function of it.
type Scenario = { s: number; regime: string; seed: number; regimePath: string };

// --scenarios <path>, in one of two shapes:
//   { regimes: string[], seeds: number[] }         the cartesian product, ordinals in that order
//   { k?: number, epochs: [{ s?, regime, seed }] }  an ordered plan (core/src/competition/schedule.ts)
// Both resolve every regime now rather than at run time: a typo in the set should fail before anvil
// starts, not three hours into a matrix.
function loadScenarioSet(
  root: string,
  path: string,
): { scenarios: Scenario[]; k: number } {
  const abs = resolve(root, path);
  if (!existsSync(abs))
    throw new Error(`scenario set not found: ${abs} (--scenarios)`);
  const doc = parseYaml(readFileSync(abs, "utf8")) as {
    regimes?: unknown;
    seeds?: unknown;
    epochs?: unknown;
    k?: unknown;
  };
  const out: Scenario[] = [];
  if (Array.isArray(doc?.epochs)) {
    if (doc.epochs.length === 0)
      throw new Error(`${abs}: "epochs" must be a non-empty array`);
    doc.epochs.forEach((entry, i) => {
      const e = entry as { s?: unknown; regime?: unknown; seed?: unknown };
      if (typeof e?.regime !== "string" || !Number.isInteger(e?.seed))
        throw new Error(
          `${abs}: epochs[${i}] needs a string "regime" and an integer "seed"`,
        );
      const s = e.s === undefined ? i + 1 : e.s;
      if (!Number.isInteger(s) || (s as number) < 1)
        throw new Error(`${abs}: epochs[${i}].s must be a positive integer`);
      out.push({
        s: s as number,
        regime: e.regime,
        seed: e.seed as number,
        regimePath: resolveRegimePath(root, e.regime),
      });
    });
    const ordinals = new Set(out.map((x) => x.s));
    if (ordinals.size !== out.length)
      throw new Error(`${abs}: epoch ordinals "s" must be unique`);
  } else {
    const regimes = doc?.regimes;
    const seeds = doc?.seeds;
    if (!Array.isArray(regimes) || regimes.length === 0)
      throw new Error(
        `${abs} must contain a non-empty "regimes" array (or an "epochs" plan)`,
      );
    if (!Array.isArray(seeds) || seeds.length === 0)
      throw new Error(`${abs} must contain a non-empty "seeds" array`);
    for (const regime of regimes) {
      if (typeof regime !== "string")
        throw new Error(`${abs}: every entry of "regimes" must be a string`);
      const regimePath = resolveRegimePath(root, regime);
      for (const seed of seeds) {
        if (!Number.isInteger(seed))
          throw new Error(`${abs}: every entry of "seeds" must be an integer`);
        out.push({ s: out.length + 1, regime, seed: seed as number, regimePath });
      }
    }
  }
  // k: the schedule's length (§4.4.1). A plan may state it explicitly -- a partial rehearsal of a
  // 40-epoch schedule still weights its epochs on the 40 -- otherwise it is the set's size.
  const maxS = Math.max(...out.map((x) => x.s));
  const k = doc?.k === undefined ? maxS : doc.k;
  if (!Number.isInteger(k) || (k as number) < maxS)
    throw new Error(
      `${abs}: "k" must be an integer >= the largest ordinal (${maxS}); got ${String(doc?.k)}`,
    );
  return { scenarios: out, k: k as number };
}

async function main(): Promise<void> {
  const flags = parseFlags(process.argv);
  if (flags.config)
    throw new Error(
      "for backtest use --regime, not --config (the regime YAML is the run config itself)",
    );
  if (flags.regime && flags.scenarios)
    throw new Error("--regime and --scenarios are mutually exclusive");
  if (!flags.regime && !flags.scenarios) {
    console.error(USAGE);
    throw new Error("one of --regime or --scenarios is required");
  }
  if (flags.scenarios && flags.seed !== undefined)
    throw new Error(
      "--seed does not apply to --scenarios (the set supplies the seeds)",
    );

  if (flags.metric !== undefined)
    throw new Error(
      "--metric is retired: the standings are the rules' deviation score (§4.4, ADR 0023) and " +
        "there is no second metric to rank by",
    );

  const repeat = Number(flags.repeat ?? "1");
  if (!Number.isInteger(repeat) || repeat < 1)
    throw new Error(
      `--repeat must be a positive integer (got ${flags.repeat})`,
    );
  const port = Number(flags.port ?? "8547");
  const rpcUrl = `http://127.0.0.1:${port}`;
  const stateDirAbs = resolve(ROOT, flags.state ?? STATE_DIR_DEFAULT);
  // Issue #77. Off by default, so every stored matrix stays comparable with the ones before it.
  // The scenarios of a matrix run in list order and the coordinator runs in this process, so
  // exporting the root once is enough for the state to travel from one scenario to the next --
  // which is exactly the ordering the live competition has, one epoch after another.
  const agentStateRoot =
    flags["agent-state-root"] === undefined
      ? undefined
      : resolve(ROOT, flags["agent-state-root"]);
  if (agentStateRoot !== undefined) {
    mkdirSync(agentStateRoot, { recursive: true });
    process.env[AGENT_STATE_ROOT_ENV] = agentStateRoot;
    console.error(
      `[backtest] agents keep state across scenarios in ${agentStateRoot} ` +
        `(issue #77; a frozen control ignores it)`,
    );
  }

  const matrixMode = flags.scenarios !== undefined;
  let scenarios: Scenario[];
  let k = 1;
  if (matrixMode) {
    ({ scenarios, k } = loadScenarioSet(ROOT, flags.scenarios));
  } else {
    // Regimes no longer carry a seed (ADR 0017 §1), so an omitted --seed used to mean "silently
    // score seed 1". Fail instead: a scenario without a seed is not a scenario.
    if (flags.seed === undefined)
      throw new Error(
        "--seed is required with --regime (regimes no longer carry run.seed; ADR 0017 §1). " +
          "For a whole set use --scenarios config/scenarios/public.yaml",
      );
    const seed = Number(flags.seed);
    if (!Number.isInteger(seed))
      throw new Error(`--seed must be an integer (got ${flags.seed})`);
    const regimePath = resolveRegimePath(ROOT, flags.regime);
    scenarios = [
      {
        s: 1,
        regime: basename(regimePath).replace(/\.ya?ml$/, ""),
        seed,
        regimePath,
      },
    ];
  }

  // ---- Validate the state manifest + sync constants (done before importing the coordinator) ----
  const { manifest, statePath } = readStateManifest(stateDirAbs);
  const head = gitHead(ROOT);
  if (
    head &&
    manifest.sourceCommit !== "unknown" &&
    head !== manifest.sourceCommit
  )
    console.error(
      `[backtest] note: the state dump's generating commit (${manifest.sourceCommit.slice(0, 12)}) ` +
        `differs from the current HEAD (${head.slice(0, 12)}). If you changed deployer/constants, ` +
        `rebuild it with npm run gen:state-dump`,
    );
  await syncConstants(
    manifest.deploymentsFingerprint,
    manifest.deployments,
    stateDirAbs,
  );

  // ---- Lightweight regime read + applying one-off overrides (the effective regime) ----
  // Run overrides (--protocols, etc.) aren't enough via the coordinator's cliOverrides alone: the
  // agent process reads the ERIS_CONFIG YAML directly, so we write out an "effective regime YAML" with
  // the overrides merged in, making the coordinator and agent read the same config (otherwise the agent
  // tries to observe a venue not in the state and dies on a zero-address read). The --agents roster is
  // baked into the effective YAML's inline agents for the same reason (don't add a priority branch to
  // core's roster resolution).
  type RegimeDoc = {
    run?: Record<string, unknown> & {
      seed?: number;
      protocols?: string[];
    };
    agents?: unknown;
  } & Record<string, unknown>;

  const runOverrides: Record<string, unknown> = {};
  if (flags.protocols)
    runOverrides.protocols = flags.protocols.split(",").map((s) => s.trim());
  if (flags.blocks !== undefined) runOverrides.blocks = Number(flags.blocks);
  if (flags.seconds !== undefined) runOverrides.seconds = Number(flags.seconds);
  if (flags["score-every"] !== undefined)
    runOverrides.scoreEvery = Number(flags["score-every"]);
  if (flags["economic-gas"] !== undefined)
    runOverrides.economicGas =
      flags["economic-gas"] === "1" || flags["economic-gas"] === "true";
  if (flags["agent-sandbox"] !== undefined) {
    if (flags["agent-sandbox"] !== "process" && flags["agent-sandbox"] !== "docker")
      throw new Error(`--agent-sandbox must be process or docker (got ${flags["agent-sandbox"]})`);
    runOverrides.agentSandbox = flags["agent-sandbox"];
  }

  let rosterAgents: unknown;
  if (flags.agents !== undefined) {
    const rosterPath = resolve(ROOT, flags.agents);
    if (!existsSync(rosterPath))
      throw new Error(`agents roster not found: ${rosterPath} (--agents)`);
    // JSON is a subset of YAML 1.2, so parseYaml can read a .json roster too.
    // Leave content validation to the coordinator's validateAgentsFile.
    const roster = parseYaml(readFileSync(rosterPath, "utf8")) as {
      agents?: unknown;
    };
    if (!roster || !Array.isArray(roster.agents))
      throw new Error(`${rosterPath} must contain an "agents" array`);
    rosterAgents = roster.agents;
  }

  // The effective regime is always written now, because the seed is no longer in the regime file and
  // has to reach the agent processes too: they read the ERIS_CONFIG YAML directly, so an override
  // that only reaches the coordinator leaves the agent observing a different world (ADR 0016 §2).
  const regimeDocs = new Map<string, RegimeDoc>();
  const rosterOf = (doc: RegimeDoc): string[] => {
    const agents = (rosterAgents ?? doc.agents) as
      Array<{ id?: unknown }> | undefined;
    return Array.isArray(agents)
      ? agents
          .map((a) => a?.id)
          .filter((id): id is string => typeof id === "string")
      : [];
  };
  // Parse (and cache) a regime file. Separated from writing the effective YAML so the pre-flight
  // checks below can read a regime without also producing a file that the run loop immediately
  // overwrites.
  const loadRegimeDoc = (scenario: Scenario): RegimeDoc => {
    let doc = regimeDocs.get(scenario.regimePath);
    if (!doc) {
      doc = parseYaml(readFileSync(scenario.regimePath, "utf8")) as RegimeDoc;
      if (doc?.run?.seed !== undefined)
        console.error(
          `[backtest] note: ${scenario.regimePath} still carries run.seed=${doc.run.seed}; ` +
            `the scenario seed overrides it. Remove it (ADR 0017 §1: the seed is not part of the regime)`,
        );
      regimeDocs.set(scenario.regimePath, doc);
    }
    return doc;
  };
  const effectivePathFor = (scenario: Scenario): string => {
    const doc = loadRegimeDoc(scenario);
    const effective: RegimeDoc = {
      ...doc,
      run: { ...(doc.run ?? {}), ...runOverrides, seed: scenario.seed },
      ...(rosterAgents !== undefined ? { agents: rosterAgents } : {}),
    };
    const path = join(
      stateDirAbs,
      `.effective-${scenario.regime}-${scenario.seed}.yaml`,
    );
    writeFileSync(
      path,
      `# AUTO-GENERATED by backtest CLI — ${scenario.regimePath} + seed ${scenario.seed}` +
        ` + CLI overrides. Do not edit by hand.\n` +
        stringifyYaml(effective),
    );
    return path;
  };

  // Whether the venues each regime requires are all present in the state dump. If some are missing,
  // an eth_call to a zero address gives a cryptic error, so fail-fast first -- and do it for the
  // whole set before anvil starts, not lazily per scenario. Once per regime, not once per scenario:
  // the protocol list is a property of the regime, so re-checking it per seed just repeats itself.
  const checkedRegimes = new Set<string>();
  for (const scenario of scenarios) {
    if (checkedRegimes.has(scenario.regimePath)) continue;
    checkedRegimes.add(scenario.regimePath);
    const doc = loadRegimeDoc(scenario);
    const effectiveProtocols =
      (runOverrides.protocols as string[] | undefined) ??
      doc?.run?.protocols ??
      [];
    const missing = missingVenues(effectiveProtocols, manifest.deployments);
    if (missing.length > 0)
      throw new Error(
        `regime ${scenario.regime}: state dump is missing venues: ${missing.join(", ")}. ` +
          `Either rebuild it from a full deploy with npm run gen:state-dump, or narrow the target ` +
          `venues with --protocols (e.g. --protocols ${effectiveProtocols
            .filter((p) => !missing.includes(p))
            .join(",")})`,
      );
  }

  // A roster that differs between regimes makes the standings incomparable: `total` averages only
  // the regimes an agent appeared in, so an agent present in one regime is ranked on a fraction of
  // the evidence, against a differently sized z-pool. The competition always passes one roster via
  // --agents; the per-regime defaults exist for solo verification and do differ (lending-incident
  // carries a liquidator), so say so rather than silently producing a lopsided ranking.
  if (matrixMode && rosterAgents === undefined) {
    const rosters = new Map<string, string>();
    for (const scenario of scenarios)
      rosters.set(
        scenario.regime,
        rosterOf(loadRegimeDoc(scenario)).sort().join(","),
      );
    if (new Set(rosters.values()).size > 1)
      console.error(
        `[backtest] warning: the regimes in this set have different default rosters, so agents ` +
          `appear in different numbers of regimes and their totals are not comparable ` +
          `(${[...rosters].map(([r, ids]) => `${r}:[${ids}]`).join(" ")}). ` +
          `Pass --agents <roster> to score one field across every regime`,
      );
  }
  if (Object.keys(runOverrides).length > 0 || rosterAgents !== undefined)
    console.error(
      `[backtest] overrides present (${[
        ...Object.keys(runOverrides),
        ...(rosterAgents !== undefined ? ["agents"] : []),
      ].join(
        ", ",
      )}). Runs you read results from should use regime default values (ADR 0016 §3)`,
    );

  // ---- Backtest-only anvil (--load-state) ----
  if (await isAnvilUp(rpcUrl))
    throw new Error(
      `port ${port} is in use (fail-fast to avoid dragging in the deployer anvil, etc.). ` +
        `Specify a different port with --port`,
    );
  console.error(
    `[backtest] starting anvil (--load-state ${statePath} / port ${port})`,
  );
  const anvil: ChildProcess = spawn(
    "anvil",
    [
      "--port",
      String(port),
      // Same calibration as the deployer's anvil (deployer/src/anvil.ts startAnvil) for
      // code-size and base-fee. When you change those there, match them here.
      // Two deliberate differences: --order fees aligns with production realtime, and the
      // gas limit is the competition's, not the deployer's. The deployer runs at 3,000,000,000
      // because deploying GMX needs it; this anvil loads a finished state dump and never
      // deploys, so it runs at the block size the rules publish (§2.6: 30,000,000, the value
      // Ethereum L1 and OP Mainnet ran for years and anvil's own default). Sizing it to fit
      // every agent's every transaction would remove the priority-fee auction §2.6 describes.
      "--code-size-limit",
      "50000",
      "--base-fee",
      "0",
      "--gas-limit",
      "30000000",
      "--accounts",
      "10",
      "--balance",
      "1000000",
      "--order",
      "fees",
      "--load-state",
      statePath,
    ],
    { stdio: ["ignore", "ignore", "inherit"] },
  );
  const keepAnvil = flags["keep-anvil"] === "1";
  const stopAnvil = (): void => {
    if (!anvil.killed) anvil.kill("SIGTERM");
  };
  process.on("SIGINT", () => {
    stopAnvil();
    process.exit(130);
  });

  try {
    await waitUntilAnvilUp(rpcUrl);
    // Detect a state mix-up: whether the genesis hash matches the manifest's generator (ADR 0016 §2)
    const genesis = await rpc<{ hash: string }>(
      rpcUrl,
      "eth_getBlockByNumber",
      ["0x0", false],
    );
    if (genesis.hash !== manifest.genesisHash)
      throw new Error(
        `loaded state's genesis (${genesis.hash.slice(0, 12)}…) does not match the manifest ` +
          `(${manifest.genesisHash.slice(0, 12)}…). The state dump is corrupt or a different one`,
      );

    // ---- Repeated coordinator runs ----
    // The snapshot file is backtest-anvil only (doesn't pollute the deployer anvil's .local-snapshot).
    // Each start is from a fresh anvil, so clear any leftover from last time first.
    const snapshotFile = join(stateDirAbs, `.snapshot-${port}`);
    rmSync(snapshotFile, { force: true });

    process.env.ERIS_LOCAL_DEPLOY = "1";
    // Evaluate after the constants sync (dynamically, since static imports are hoisted; same as sim-realtime.ts).
    const { runRealtimeSimulation } =
      await import("../realtime/coordinator.js");

    // ---- The scenario matrix ----
    // One long-lived anvil; every scenario is snapshot -> run -> reconstruct -> revert (ADR 0017 §3).
    // Scoring reconstruction finishes inside runRealtimeSimulation, i.e. before the next revert
    // erases the history it reads.
    const results: ScenarioResult[] = [];
    // Kept alongside `results` only for the --repeat spread report below; the folded record is what
    // reaches matrix.json.
    const repeatsByScenario: AgentScore[][][] = [];
    const blocksByScenario: Array<Array<number | undefined>> = [];
    // Prepared before the loop, and rewritten after every scenario. A full private matrix is ~6 h;
    // holding the results in memory until the end means an OOM, an anvil death or a Ctrl-C at
    // scenario 29 of 30 throws away everything already computed.
    const outDir = matrixMode
      ? resolve(
          ROOT,
          "runs",
          `matrix-${new Date().toISOString().replace(/[:.]/g, "-")}`,
        )
      : undefined;
    if (outDir) mkdirSync(outDir, { recursive: true });
    const flush = (): void => {
      if (!outDir) return;
      writeFileSync(
        join(outDir, "matrix.json"),
        `${JSON.stringify(
          {
            // schema 2 (ADR 0023): scenarios carry the ordinal `s` and per-agent P (`pnlUsdc`);
            // the M4/M9 fields and `metric` are gone with the metric they belonged to.
            schema: 2,
            createdAt: new Date().toISOString(),
            sourceCommit: gitHead(ROOT) ?? "unknown",
            scenarioSet: flags.scenarios,
            // A matrix is a scenario-mode run by construction (ADR 0020 §1). Written out so a later
            // comparison against a continuous run is refused rather than silently averaged.
            resetUnit: "scenario",
            // The schedule length the weights are taken over (rules §4.4.1).
            k,
            repeat,
            // Complete only once every scenario has run; until then this is a partial matrix.
            scenariosPlanned: scenarios.length,
            // Both metrics are stored regardless of which one ranks, so the standings can be
            // recomputed under a different scoring rule without re-running anything (ADR 0017 §4).
            scenarios: results,
          },
          null,
          2,
        )}\n`,
      );
      writeFileSync(
        join(outDir, "standings.json"),
        `${JSON.stringify(computeStandings(results, k), null, 2)}\n`,
      );
    };
    let index = 0;
    for (const scenario of scenarios) {
      index++;
      const label = scenarioId(scenario.regime, scenario.seed);
      const expectedAgents = rosterOf(loadRegimeDoc(scenario));
      // Have both the coordinator and the agent processes read this scenario's effective regime.
      process.env.ERIS_CONFIG = effectivePathFor(scenario);

      const perRepeat: AgentScore[][] = [];
      const runDirs: string[] = [];
      const blocksPerRepeat: Array<number | undefined> = [];
      let lastError: string | undefined;
      // With state carrying, the repeats of one scenario are not repeats unless each starts from
      // the same place: repeat 2 would otherwise begin from what repeat 1 left behind, and the
      // spread across repeats -- the reason the flag exists -- would be measuring a sequence.
      // Keyed by the epoch ordinal, not by (regime, seed): a plan may schedule the same pair twice
      // and the two are different epochs with different state behind them.
      const repeatLabel = `repeat-base-s${scenario.s}`;
      for (let i = 0; i < repeat; i++) {
        if (agentStateRoot !== undefined && repeat > 1) {
          if (i === 0) snapshotAllAgentState(agentStateRoot, repeatLabel);
          else restoreAllAgentState(agentStateRoot, repeatLabel);
        }
        console.error(
          `[backtest] scenario ${index}/${scenarios.length} ${label}` +
            (repeat > 1 ? ` (repeat ${i + 1}/${repeat})` : ""),
        );
        try {
          const { runDir } = await runRealtimeSimulation({
            ANVIL_RPC_URL: rpcUrl,
            // Guarantee config.localDeploy even for an arbitrary regime file (one that forgot to write run.localDeploy).
            ERIS_LOCAL_DEPLOY: "1",
            ERIS_LOCAL_SNAPSHOT_FILE: snapshotFile,
            ERIS_RUN_MODE: "backtest",
            // ADR 0020 §1: the matrix is the only thing that resets the world between runs, so it is
            // the only thing allowed to declare the mode. A single --regime replay stays `continuous`
            // -- it is one world, whatever the snapshot/revert around it does for the *next* scenario.
            ...(matrixMode ? { ERIS_RESET_UNIT: "scenario" } : {}),
          });
          runDirs.push(runDir);
          const summary = readRunSummary(runDir);
          if (summary) {
            perRepeat.push(scoresFromSummary(summary, expectedAgents));
            blocksPerRepeat.push(summary.blocksProcessed);
          } else {
            lastError = `summary.json not found (${runDir})`;
            console.error(`[backtest] warning: ${lastError}`);
          }
        } catch (error) {
          // One scenario blowing up must not abandon the rest of the matrix. It is recorded as an
          // excluded scenario, which keeps it out of the aggregation instead of scoring everyone
          // zero for an environment failure (ADR 0017 §4).
          lastError = error instanceof Error ? error.message : String(error);
          console.error(`[backtest] scenario ${label} failed: ${lastError}`);
        }
      }
      repeatsByScenario.push(perRepeat);
      blocksByScenario.push(blocksPerRepeat);
      results.push({
        s: scenario.s,
        regime: scenario.regime,
        seed: scenario.seed,
        ...(perRepeat.length > 0 ? { agents: foldRepeats(perRepeat) } : {}),
        ...(runDirs.length > 0 ? { runDir: runDirs[runDirs.length - 1] } : {}),
        ...(perRepeat.length === 0 && lastError !== undefined
          ? { error: lastError }
          : {}),
      });
      flush();
    }

    // ---- Report ----
    const standings = computeStandings(results, k);
    console.log("");
    // With --repeat, show each run rather than only the fold. The point of repeating a scenario is
    // to see how far it moves run to run (ADR 0005 says to read results as a distribution), and a
    // single folded line hides both the spread and a run that ended early on fewer blocks.
    if (repeat > 1) {
      for (const [s, scenario] of scenarios.entries()) {
        const runs = repeatsByScenario[s] ?? [];
        if (runs.length === 0) continue;
        console.log(
          `  ${scenarioId(scenario.regime, scenario.seed)} — ${runs.length}/${repeat} runs:`,
        );
        for (const [i, run] of runs.entries())
          console.log(
            `    run ${i + 1} (${blocksByScenario[s]?.[i] ?? "?"} blocks): ` +
              run
                .map(
                  (a) =>
                    `${a.id}=${a.pnlUsdc?.toFixed(2) ?? "-"}${a.flags ? "(!)" : ""}`,
                )
                .join("  "),
          );
      }
      console.log("");
    }
    for (const result of results) {
      const label = scenarioId(result.regime, result.seed);
      if (!result.agents) {
        console.log(`  ${label}: FAILED (${result.error})`);
        continue;
      }
      const epoch = standings.epochs.find((e) => e.s === result.s);
      const line = result.agents
        .map(
          (a) =>
            `${a.id}=${a.pnlUsdc?.toFixed(2) ?? "-"}` +
            (epoch?.tByAgent[a.id] !== undefined
              ? `(T ${epoch.tByAgent[a.id].toFixed(1)})`
              : "") +
            (a.flags ? "(!)" : ""),
        )
        .join("  ");
      console.log(
        `  s=${result.s} ${label}${epoch?.excluded ? ` [out of S: ${epoch.excluded}]` : ""}: ${line}`,
      );
    }

    if (matrixMode && outDir) {
      // Already written incrementally by flush(); this is the final, complete pass.
      flush();
      console.log("");
      console.log(
        `standings (rules §4.4 deviation score, k=${standings.k}, S=[${standings.S.join(",")}]):`,
      );
      for (const agent of standings.agents)
        console.log(
          `  ${String(agent.rank).padStart(2)}${agent.tied ? "=" : "."} ${agent.id.padEnd(20)} ` +
            `${agent.score === null ? "-" : agent.score.toFixed(2)}` +
            `  [${agent.epochs.map((e) => `s${e.s}:${e.t.toFixed(1)}`).join(" ")}]` +
            (agent.flags.length > 0 ? `  ! ${agent.flags.length} flag(s)` : ""),
        );
      const excluded = standings.epochs.filter((e) => e.excluded !== undefined);
      if (excluded.length > 0)
        console.log(
          `  out of S: ` +
            excluded
              .map((e) => `s=${e.s} ${scenarioId(e.regime, e.seed)} (${e.excluded})`)
              .join(", "),
        );
      for (const b of standings.benchmarks)
        console.log(
          `  benchmark ${b.id}: ` +
            Object.entries(b.pnlByEpoch)
              .map(([s, p]) => `s${s}:${p.toFixed(2)}`)
              .join(" "),
        );
      console.log("");
      console.log(`wrote ${outDir}/matrix.json and standings.json`);
    }
  } finally {
    if (keepAnvil) {
      // Detach so the child handle doesn't hold the event loop and prevent the CLI from exiting.
      anvil.unref();
      console.error(
        `[backtest] --keep-anvil: anvil stays running at ${rpcUrl} (stop it manually)`,
      );
    } else stopAnvil();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
