// participant backtest CLI + competition scenario runner (ADR 0016 B1 realtime replay, ADR 0017 §3).
//
//   npm run backtest -- --regime <name> --seed <N> [--agents <roster>] [--repeat N]
//   npm run backtest -- --scenarios config/scenarios/public.yaml [--agents <roster>]
//                       [--resume runs/matrix-<id>] [--follow-schedule]
//                       [--port 8547] [--state backtest/state] [--keep-anvil]
//                       [--blocks N] [--seconds N] [--protocols a,b] [--score-every N]
//
// Starts one anvil with the distributed state dump loaded (generated by gen:state-dump) and replays
// scenarios through the existing coordinator. A scenario is (regime, seed): the regime YAML holds the
// market conditions and the seed picks the realization, so the seed is passed in rather than baked
// into the regime (ADR 0017 §1).
//
// Every scenario is snapshot -> run -> reconstruct -> revert on that same anvil, which is what makes
// "no forking, many runs a day on one devnet" work: resetFork's evm_snapshot/evm_revert gives each
// run a clean slice, and scoring reconstruction finishes before the next revert erases the history
// it reads.
//
// With --scenarios the whole matrix is replayed and two artifacts are written:
//   matrix.json    raw per-scenario, per-agent scores (both netPnlUsdc and alphaUsdc)
//   standings.json the ranking derived from them (regime-internal z-score, equal weight per regime)
// The ranking is a derived view on purpose: the scoring rule is expected to change, and matrix.json
// is what lets it be recomputed without re-running anything (ADR 0017 §4).
//
// Dependency-light for the same reason as sim-realtime.ts: before importing sdk/constants we must set
// ERIS_LOCAL_DEPLOY=1 and finish syncing the constants.local.ts fingerprint. The coordinator is
// dynamically imported last.
import { spawn, type ChildProcess } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, join, resolve } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import {
  computeStandings,
  scenarioId,
  type AgentScore,
  type ScenarioResult,
} from "../backtest/standings.js";
import {
  installScenarioKey,
  resolveScenarioKey,
  SCENARIO_KEY_FILE_ENV,
  scenarioKeyRecord,
} from "../scenarioKey.js";
import {
  foldRepeats,
  readRunSummary,
  scenarioFlags,
  scoresFromSummary,
} from "../backtest/scenarioScores.js";
import {
  assertResumable,
  mergeStoredResults,
  readStoredMatrix,
  rosterFingerprint,
  type StoredMatrix,
  STATE_LABEL_INITIAL,
  stateLabelAfter,
  stateLabelBefore,
} from "../backtest/resume.js";
import {
  gitHead,
  isAnvilUp,
  missingVenues,
  parseFlags,
  readConstantsFingerprint,
  readStateManifest,
  resolveRegimePath,
  rpc,
  STATE_DIR_DEFAULT,
  waitUntilAnvilUp,
} from "../backtest/shared.js";
import {
  assertFollowable,
  describeStart,
  sleep,
  startDelay,
} from "../backtest/timetable.js";
import { matrixEpochOverrides } from "../backtest/epochOrdinal.js";
import {
  AGENT_STATE_ROOT_ENV,
  restoreAllAgentState,
  snapshotAllAgentState,
} from "../realtime/agentState.js";

const ROOT = process.cwd(); // npm scripts run at the repo root

// A checkpoint of the state root leaves out an agent directory that cannot be copied (issue #214
// item 2: a pipe, a symlink, a sparse file past the cap). Said on stderr at the time, because a
// later restore of that label puts the agent back to nothing and the reason has to be findable.
function checkpointAgentState(root: string, label: string): void {
  for (const { agentId, reason } of snapshotAllAgentState(root, label))
    console.error(
      `[backtest] state checkpoint ${label}: ${agentId} left out (${reason}); a restore of this ` +
        "label starts that agent empty",
    );
}

const USAGE = `usage: npm run backtest -- (--regime <name|path> --seed <N> | --scenarios <path>) [options]
  --regime <name|path>   config/regimes/<name>.yaml (or a YAML path). requires --seed
  --seed <N>             the scenario's seed. regimes no longer carry one (ADR 0017 §1)
  --scenarios <path>     scenario set to replay as a matrix, in one of two shapes:
                           { regimes: [...], seeds: [...] }         the cartesian product, run in that order
                           { k?: N, epochs: [{ s?, regime, seed }] }  an ordered plan (npm run competition -- plan)
                         each scenario is one epoch of the rules; the standings are the deviation score (§4.4)
  --agents <roster>      replace the regime's default agents with a roster file (YAML/JSON)
  --resume <matrix-dir>  continue a stored matrix (runs/matrix-<id>/) instead of opening a new one: scenarios
                         already complete there are skipped, the missing and failed ones run, and matrix.json /
                         standings.json are rewritten in place. The live week is k epochs across several
                         invocations (rules §4.7.1); refused when scenarioSet / k / resetUnit / repeat /
                         agent-state-root differ. With --agent-state-root, each re-run starts from the
                         state the latest complete ordinal before it ended with (checkpoints under
                         <root>/.snapshots/end-s<N>), not from whatever ran last
  --scenario-key <file|public>
                         the key every scenario is realized under (ADR 0027): a key file
                         (npm run competition -- keygen) or "public". Default: ERIS_SCENARIO_KEY_FILE, else the
                         public key. Required for an ordered plan (the live-week form), so the live week cannot
                         silently run under the public key
  --follow-schedule      wait for each epoch's planned start (the plan's startsAt, from npm run competition --
                         plan --starts-at … --every-minutes|--ends-at) instead of running the epochs back to
                         back, so one unattended process runs the live week (ADR 0026). An epoch whose start
                         has passed starts at once and says how late; later epochs still wait for their own
                         times. Composes with --resume: complete epochs are skipped without waiting, so a
                         restart runs the missed and failed ones at once and then waits for the next. Refused
                         when an epoch has no startsAt or the starts are out of list order
  --repeat <N>           repeat each scenario N times (calibration diagnostic; standings take the median P. default 1)
  --port <N>             port for the backtest-only anvil (default 8547)
  --state <dir>          state dump directory (default ${STATE_DIR_DEFAULT})
  --keep-anvil           keep anvil running after exit (for debugging)
  --agent-sandbox <process|docker>
                         how agents are launched. The official regimes say docker (the rules §2.3 caps live there);
                         pass process for a local run without docker
  --agent-state-root <d> carry each agent's persistent state across the scenarios of the run, in the
                         order they are listed — which for a plan from npm run competition -- plan
                         is the competition's own epoch order (issue #77). Off by default; without
                         it every scenario restarts each agent at version 0
  --blocks/--seconds/--protocols/--economic-gas/--score-every
                         one-off overrides of regime values (for smoke tests. runs you read results from use regime defaults)`;

// Sync constants.local.ts with the deployments bundled in the state manifest (ADR 0016 §2).
// On mismatch, extract deployments from the manifest and regenerate; if it still doesn't match,
// the state dump and repo version are a mismatched combination -> fail-fast.
async function syncConstants(
  manifestFingerprint: string,
  deployments: Record<string, unknown>,
  stateDirAbs: string,
): Promise<void> {
  const constantsPath = resolve(ROOT, "sdk", "src", "constants.local.ts");
  const current = readConstantsFingerprint(constantsPath);
  if (current === manifestFingerprint) return;
  console.error(
    `[backtest] constants.local.ts fingerprint does not match the state manifest ` +
      `(${current ?? "(none)"} != ${manifestFingerprint}). Regenerating from the deployments bundled in the manifest`,
  );
  const extracted = join(stateDirAbs, "deployments.extracted.json");
  writeFileSync(extracted, `${JSON.stringify(deployments, null, 2)}\n`);
  // genLocalConstants depends only on node builtins + viem + backtest/shared (it doesn't evaluate
  // sdk/constants), so it's fine to import before the coordinator.
  const { generateLocalConstants } =
    await import("../../../scripts/genLocalConstants.js");
  const { fingerprint } = generateLocalConstants(extracted);
  if (fingerprint !== manifestFingerprint)
    throw new Error(
      `fingerprint still doesn't match after regenerating constants.local.ts ` +
        `(${fingerprint} != ${manifestFingerprint}). Check the combination of the state dump and repo ` +
        `versions (ADR 0016 §2 fail-fast)`,
    );
}

// One cell of the evaluation matrix. `<regime>#<seed>` is the address used in every report
// (ADR 0017 §1); the regime supplies the market conditions and the seed picks the realization.
// `s` is the scheduled ordinal (rules §4.4.1): the epoch's weight is a function of it.
type Scenario = {
  s: number;
  regime: string;
  seed: number;
  regimePath: string;
  /** The plan's intended start (ISO 8601), when it states one. Shown, never scored. */
  startsAt?: string;
};

// --scenarios <path>, in one of two shapes:
//   { regimes: string[], seeds: number[] }         the cartesian product, ordinals in that order
//   { k?: number, epochs: [{ s?, regime, seed }] }  an ordered plan (core/src/competition/schedule.ts)
// Both resolve every regime now rather than at run time: a typo in the set should fail before anvil
// starts, not three hours into a matrix.
function loadScenarioSet(
  root: string,
  path: string,
): { scenarios: Scenario[]; k: number; plan: boolean } {
  const abs = resolve(root, path);
  if (!existsSync(abs))
    throw new Error(`scenario set not found: ${abs} (--scenarios)`);
  const doc = parseYaml(readFileSync(abs, "utf8")) as {
    regimes?: unknown;
    seeds?: unknown;
    epochs?: unknown;
    k?: unknown;
  };
  const out: Scenario[] = [];
  if (Array.isArray(doc?.epochs)) {
    if (doc.epochs.length === 0)
      throw new Error(`${abs}: "epochs" must be a non-empty array`);
    doc.epochs.forEach((entry, i) => {
      const e = entry as {
        s?: unknown;
        regime?: unknown;
        seed?: unknown;
        startsAt?: unknown;
      };
      if (typeof e?.regime !== "string" || !Number.isInteger(e?.seed))
        throw new Error(
          `${abs}: epochs[${i}] needs a string "regime" and an integer "seed"`,
        );
      const s = e.s === undefined ? i + 1 : e.s;
      if (!Number.isInteger(s) || (s as number) < 1)
        throw new Error(`${abs}: epochs[${i}].s must be a positive integer`);
      if (
        e.startsAt !== undefined &&
        (typeof e.startsAt !== "string" || Number.isNaN(Date.parse(e.startsAt)))
      )
        throw new Error(
          `${abs}: epochs[${i}].startsAt must be an ISO 8601 date`,
        );
      out.push({
        s: s as number,
        regime: e.regime,
        seed: e.seed as number,
        regimePath: resolveRegimePath(root, e.regime),
        ...(typeof e.startsAt === "string" ? { startsAt: e.startsAt } : {}),
      });
    });
    const ordinals = new Set(out.map((x) => x.s));
    if (ordinals.size !== out.length)
      throw new Error(`${abs}: epoch ordinals "s" must be unique`);
  } else {
    const regimes = doc?.regimes;
    const seeds = doc?.seeds;
    if (!Array.isArray(regimes) || regimes.length === 0)
      throw new Error(
        `${abs} must contain a non-empty "regimes" array (or an "epochs" plan)`,
      );
    if (!Array.isArray(seeds) || seeds.length === 0)
      throw new Error(`${abs} must contain a non-empty "seeds" array`);
    for (const regime of regimes) {
      if (typeof regime !== "string")
        throw new Error(`${abs}: every entry of "regimes" must be a string`);
      const regimePath = resolveRegimePath(root, regime);
      for (const seed of seeds) {
        if (!Number.isInteger(seed))
          throw new Error(`${abs}: every entry of "seeds" must be an integer`);
        out.push({
          s: out.length + 1,
          regime,
          seed: seed as number,
          regimePath,
        });
      }
    }
  }
  // k: the schedule's length (§4.4.1). A plan may state it explicitly -- a partial rehearsal of a
  // 60-epoch schedule still weights its epochs on the 60 -- otherwise it is the set's size.
  const maxS = Math.max(...out.map((x) => x.s));
  const k = doc?.k === undefined ? maxS : doc.k;
  if (!Number.isInteger(k) || (k as number) < maxS)
    throw new Error(
      `${abs}: "k" must be an integer >= the largest ordinal (${maxS}); got ${String(doc?.k)}`,
    );
  return { scenarios: out, k: k as number, plan: Array.isArray(doc?.epochs) };
}

async function main(): Promise<void> {
  const flags = parseFlags(process.argv);
  if (flags.config)
    throw new Error(
      "for backtest use --regime, not --config (the regime YAML is the run config itself)",
    );
  if (flags.regime && flags.scenarios)
    throw new Error("--regime and --scenarios are mutually exclusive");
  if (!flags.regime && !flags.scenarios) {
    console.error(USAGE);
    throw new Error("one of --regime or --scenarios is required");
  }
  if (flags.scenarios && flags.seed !== undefined)
    throw new Error(
      "--seed does not apply to --scenarios (the set supplies the seeds)",
    );

  if (flags.metric !== undefined)
    throw new Error(
      "--metric is retired: the standings are the rules' deviation score (§4.4, ADR 0023) and " +
        "there is no second metric to rank by",
    );

  const repeat = Number(flags.repeat ?? "1");
  if (!Number.isInteger(repeat) || repeat < 1)
    throw new Error(
      `--repeat must be a positive integer (got ${flags.repeat})`,
    );
  const port = Number(flags.port ?? "8547");
  const rpcUrl = `http://127.0.0.1:${port}`;
  const stateDirAbs = resolve(ROOT, flags.state ?? STATE_DIR_DEFAULT);
  // Issue #77. Off by default, so every stored matrix stays comparable with the ones before it.
  // The scenarios of a matrix run in list order and the coordinator runs in this process, so
  // exporting the root once is enough for the state to travel from one scenario to the next --
  // which is exactly the ordering the live competition has, one epoch after another.
  const agentStateRoot =
    flags["agent-state-root"] === undefined
      ? undefined
      : resolve(ROOT, flags["agent-state-root"]);
  if (agentStateRoot !== undefined) {
    mkdirSync(agentStateRoot, { recursive: true });
    process.env[AGENT_STATE_ROOT_ENV] = agentStateRoot;
    console.error(
      `[backtest] agents keep state across scenarios in ${agentStateRoot} ` +
        `(issue #77; a frozen control ignores it)`,
    );
  }

  const matrixMode = flags.scenarios !== undefined;
  // --resume: continue an existing matrix directory (rules §4.7.1). Only a matrix can be resumed;
  // a single --regime replay writes no matrix.json to continue.
  if (flags.resume !== undefined && !matrixMode)
    throw new Error(
      "--resume applies to --scenarios only (it continues a matrix.json)",
    );
  if (flags.resume === "1")
    throw new Error(
      "--resume needs the matrix directory: --resume runs/matrix-<id>",
    );
  const resumeDir =
    flags.resume !== undefined ? resolve(ROOT, flags.resume) : undefined;
  // --follow-schedule: wait for each epoch's planned start (ADR 0026). A bare flag; parseFlags
  // gives "1", so any other value is a following token it swallowed, said rather than ignored.
  const followSchedule = flags["follow-schedule"] !== undefined;
  if (followSchedule && flags["follow-schedule"] !== "1")
    throw new Error(
      `--follow-schedule takes no value (got "${flags["follow-schedule"]}")`,
    );
  if (followSchedule && !matrixMode)
    throw new Error(
      "--follow-schedule applies to --scenarios only (it follows a plan's timetable)",
    );
  let scenarios: Scenario[];
  let k = 1;
  let plan = false;
  if (matrixMode) {
    ({ scenarios, k, plan } = loadScenarioSet(ROOT, flags.scenarios));
    // Before anvil starts, like every other check on the set: a plan the runner cannot follow
    // should fail now, not after the first epoch.
    if (followSchedule) assertFollowable(scenarios);
  } else {
    // Regimes no longer carry a seed (ADR 0017 §1), so an omitted --seed used to mean "silently
    // score seed 1". Fail instead: a scenario without a seed is not a scenario.
    if (flags.seed === undefined)
      throw new Error(
        "--seed is required with --regime (regimes no longer carry run.seed; ADR 0017 §1). " +
          "For a whole set use --scenarios config/scenarios/public.yaml",
      );
    const seed = Number(flags.seed);
    if (!Number.isInteger(seed))
      throw new Error(`--seed must be an integer (got ${flags.seed})`);
    const regimePath = resolveRegimePath(ROOT, flags.regime);
    scenarios = [
      {
        s: 1,
        regime: basename(regimePath).replace(/\.ya?ml$/, ""),
        seed,
        regimePath,
      },
    ];
  }

  // ---- The scenario key (ADR 0027) ----
  // Installed here, before any scenario draws; the embedded coordinator finds it installed. An
  // ordered plan is the live-week form, and the live week runs under the operator's secret key: a
  // plan with no key named anywhere is refused rather than realized under the public one.
  if (
    plan &&
    flags["scenario-key"] === undefined &&
    !process.env[SCENARIO_KEY_FILE_ENV]
  )
    throw new Error(
      "an ordered plan (epochs:) is the live-week form: name its scenario key with " +
        "--scenario-key <file> (npm run competition -- keygen), or --scenario-key public to run " +
        "it under the public key on purpose (ADR 0027)",
    );
  const scenarioKey = resolveScenarioKey(flags["scenario-key"]);
  installScenarioKey(scenarioKey);
  console.error(
    `[backtest] scenario key: ${scenarioKey.source} ${scenarioKey.commitment}`,
  );
  // The same form the key check above reads, and the same way out: a plan under a key file is the
  // live week, and its posture is refused rather than warned about (core/src/realtime/liveWeek.ts).
  const liveWeek = plan && scenarioKey.source === "file";
  if (liveWeek)
    console.error(
      "[backtest] live week: an ordered plan under a key file. Public environment keys and " +
        "unisolated agents are refused (core/src/realtime/liveWeek.ts)",
    );

  // ---- Validate the state manifest + sync constants (done before importing the coordinator) ----
  const { manifest, statePath } = readStateManifest(stateDirAbs);
  const head = gitHead(ROOT);
  if (
    head &&
    manifest.sourceCommit !== "unknown" &&
    head !== manifest.sourceCommit
  )
    console.error(
      `[backtest] note: the state dump's generating commit (${manifest.sourceCommit.slice(0, 12)}) ` +
        `differs from the current HEAD (${head.slice(0, 12)}). If you changed deployer/constants, ` +
        `rebuild it with npm run gen:state-dump`,
    );
  await syncConstants(
    manifest.deploymentsFingerprint,
    manifest.deployments,
    stateDirAbs,
  );

  // ---- Lightweight regime read + applying one-off overrides (the effective regime) ----
  // The regime file + this scenario's seed + the one-off overrides (--protocols, etc.), written out as
  // one "effective regime YAML" that the coordinator runs from. The --agents roster is baked into its
  // inline agents (don't add a priority branch to core's roster resolution). This file is the
  // coordinator's: the agents it launches get their own config, derived from what the coordinator
  // resolved (core/src/realtime/agentView.ts), which carries the overrides and no seed.
  type RegimeDoc = {
    run?: Record<string, unknown> & {
      seed?: number;
      protocols?: string[];
    };
    agents?: unknown;
  } & Record<string, unknown>;

  const runOverrides: Record<string, unknown> = {};
  if (flags.protocols)
    runOverrides.protocols = flags.protocols.split(",").map((s) => s.trim());
  if (flags.blocks !== undefined) runOverrides.blocks = Number(flags.blocks);
  if (flags.seconds !== undefined) runOverrides.seconds = Number(flags.seconds);
  if (flags["score-every"] !== undefined)
    runOverrides.scoreEvery = Number(flags["score-every"]);
  if (flags["economic-gas"] !== undefined)
    runOverrides.economicGas =
      flags["economic-gas"] === "1" || flags["economic-gas"] === "true";
  if (flags["agent-sandbox"] !== undefined) {
    if (
      flags["agent-sandbox"] !== "process" &&
      flags["agent-sandbox"] !== "docker"
    )
      throw new Error(
        `--agent-sandbox must be process or docker (got ${flags["agent-sandbox"]})`,
      );
    runOverrides.agentSandbox = flags["agent-sandbox"];
  }

  let rosterAgents: unknown;
  if (flags.agents !== undefined) {
    const rosterPath = resolve(ROOT, flags.agents);
    if (!existsSync(rosterPath))
      throw new Error(`agents roster not found: ${rosterPath} (--agents)`);
    // JSON is a subset of YAML 1.2, so parseYaml can read a .json roster too.
    // Leave content validation to the coordinator's validateAgentsFile.
    const roster = parseYaml(readFileSync(rosterPath, "utf8")) as {
      agents?: unknown;
    };
    if (!roster || !Array.isArray(roster.agents))
      throw new Error(`${rosterPath} must contain an "agents" array`);
    rosterAgents = roster.agents;
  }

  // The effective regime is always written now, because the seed is no longer in the regime file
  // (ADR 0017 §1). Overrides reach the agents through the agent config the coordinator writes from
  // this run's resolved values, so an override cannot leave an agent observing a different world
  // (ADR 0016 §2).
  const regimeDocs = new Map<string, RegimeDoc>();
  const rosterOf = (doc: RegimeDoc): string[] => {
    const agents = (rosterAgents ?? doc.agents) as
      Array<{ id?: unknown }> | undefined;
    return Array.isArray(agents)
      ? agents
          .map((a) => a?.id)
          .filter((id): id is string => typeof id === "string")
      : [];
  };
  // Parse (and cache) a regime file. Separated from writing the effective YAML so the pre-flight
  // checks below can read a regime without also producing a file that the run loop immediately
  // overwrites.
  const loadRegimeDoc = (scenario: Scenario): RegimeDoc => {
    let doc = regimeDocs.get(scenario.regimePath);
    if (!doc) {
      doc = parseYaml(readFileSync(scenario.regimePath, "utf8")) as RegimeDoc;
      if (doc?.run?.seed !== undefined)
        console.error(
          `[backtest] note: ${scenario.regimePath} still carries run.seed=${doc.run.seed}; ` +
            `the scenario seed overrides it. Remove it (ADR 0017 §1: the seed is not part of the regime)`,
        );
      regimeDocs.set(scenario.regimePath, doc);
    }
    return doc;
  };
  const effectivePathFor = (scenario: Scenario): string => {
    const doc = loadRegimeDoc(scenario);
    const effective: RegimeDoc = {
      ...doc,
      run: { ...(doc.run ?? {}), ...runOverrides, seed: scenario.seed },
      ...(rosterAgents !== undefined ? { agents: rosterAgents } : {}),
    };
    const path = join(
      stateDirAbs,
      `.effective-${scenario.regime}-${scenario.seed}.yaml`,
    );
    writeFileSync(
      path,
      `# AUTO-GENERATED by backtest CLI — ${scenario.regimePath} + seed ${scenario.seed}` +
        ` + CLI overrides. Do not edit by hand.\n` +
        stringifyYaml(effective),
    );
    return path;
  };

  // Whether the venues each regime requires are all present in the state dump. If some are missing,
  // an eth_call to a zero address gives a cryptic error, so fail-fast first -- and do it for the
  // whole set before anvil starts, not lazily per scenario. Once per regime, not once per scenario:
  // the protocol list is a property of the regime, so re-checking it per seed just repeats itself.
  const checkedRegimes = new Set<string>();
  for (const scenario of scenarios) {
    if (checkedRegimes.has(scenario.regimePath)) continue;
    checkedRegimes.add(scenario.regimePath);
    const doc = loadRegimeDoc(scenario);
    const effectiveProtocols =
      (runOverrides.protocols as string[] | undefined) ??
      doc?.run?.protocols ??
      [];
    const missing = missingVenues(effectiveProtocols, manifest.deployments);
    if (missing.length > 0)
      throw new Error(
        `regime ${scenario.regime}: state dump is missing venues: ${missing.join(", ")}. ` +
          `Either rebuild it from a full deploy with npm run gen:state-dump, or narrow the target ` +
          `venues with --protocols (e.g. --protocols ${effectiveProtocols
            .filter((p) => !missing.includes(p))
            .join(",")})`,
      );
  }

  // A roster that differs between regimes makes the standings incomparable: `total` averages only
  // the regimes an agent appeared in, so an agent present in one regime is ranked on a fraction of
  // the evidence, against a differently sized z-pool. The competition always passes one roster via
  // --agents; the per-regime defaults exist for solo verification and do differ (lending-incident
  // carries a liquidator), so say so rather than silently producing a lopsided ranking.
  if (matrixMode && rosterAgents === undefined) {
    const rosters = new Map<string, string>();
    for (const scenario of scenarios)
      rosters.set(
        scenario.regime,
        rosterOf(loadRegimeDoc(scenario)).sort().join(","),
      );
    if (new Set(rosters.values()).size > 1)
      console.error(
        `[backtest] warning: the regimes in this set have different default rosters, so agents ` +
          `appear in different numbers of regimes and their totals are not comparable ` +
          `(${[...rosters].map(([r, ids]) => `${r}:[${ids}]`).join(" ")}). ` +
          `Pass --agents <roster> to score one field across every regime`,
      );
  }
  if (Object.keys(runOverrides).length > 0 || rosterAgents !== undefined)
    console.error(
      `[backtest] overrides present (${[
        ...Object.keys(runOverrides),
        ...(rosterAgents !== undefined ? ["agents"] : []),
      ].join(
        ", ",
      )}). Runs you read results from should use regime default values (ADR 0016 §3)`,
    );

  // ---- Backtest-only anvil (--load-state) ----
  if (await isAnvilUp(rpcUrl))
    throw new Error(
      `port ${port} is in use (fail-fast to avoid dragging in the deployer anvil, etc.). ` +
        `Specify a different port with --port`,
    );
  console.error(
    `[backtest] starting anvil (--load-state ${statePath} / port ${port})`,
  );
  const anvil: ChildProcess = spawn(
    "anvil",
    [
      "--port",
      String(port),
      // Same calibration as the deployer's anvil (deployer/src/anvil.ts startAnvil) for
      // code-size and base-fee. When you change those there, match them here.
      // Two deliberate differences: --order fees aligns with production realtime, and the
      // gas limit is the competition's, not the deployer's. The deployer runs at 3,000,000,000
      // because deploying GMX needs it; this anvil loads a finished state dump and never
      // deploys, so it runs at the block size the rules publish (§2.6: 30,000,000, the value
      // Ethereum L1 and OP Mainnet ran for years and anvil's own default). Sizing it to fit
      // every agent's every transaction would remove the priority-fee auction §2.6 describes.
      "--code-size-limit",
      "50000",
      "--base-fee",
      "0",
      "--gas-limit",
      "30000000",
      "--accounts",
      "10",
      "--balance",
      "1000000",
      "--order",
      "fees",
      "--load-state",
      statePath,
    ],
    { stdio: ["ignore", "ignore", "inherit"] },
  );
  const keepAnvil = flags["keep-anvil"] === "1";
  const stopAnvil = (): void => {
    if (!anvil.killed) anvil.kill("SIGTERM");
  };
  process.on("SIGINT", () => {
    stopAnvil();
    process.exit(130);
  });

  try {
    await waitUntilAnvilUp(rpcUrl);
    // Detect a state mix-up: whether the genesis hash matches the manifest's generator (ADR 0016 §2)
    const genesis = await rpc<{ hash: string }>(
      rpcUrl,
      "eth_getBlockByNumber",
      ["0x0", false],
    );
    if (genesis.hash !== manifest.genesisHash)
      throw new Error(
        `loaded state's genesis (${genesis.hash.slice(0, 12)}…) does not match the manifest ` +
          `(${manifest.genesisHash.slice(0, 12)}…). The state dump is corrupt or a different one`,
      );

    // ---- Repeated coordinator runs ----
    // The snapshot file is backtest-anvil only (doesn't pollute the deployer anvil's .local-snapshot).
    // Each start is from a fresh anvil, so clear any leftover from last time first.
    const snapshotFile = join(stateDirAbs, `.snapshot-${port}`);
    rmSync(snapshotFile, { force: true });

    process.env.ERIS_LOCAL_DEPLOY = "1";
    // Evaluate after the constants sync (dynamically, since static imports are hoisted; same as sim-realtime.ts).
    const {
      runRealtimeSimulation,
      preflightLiveWeek,
      LIVE_WEEK_OVERRIDE,
      isLiveWeekRefusal,
    } = await import("../realtime/coordinator.js");
    // The coordinator's own overrides for every epoch of this matrix, bar the per-epoch ordinal.
    const runOverridesFor = (): Record<string, string> => ({
      ANVIL_RPC_URL: rpcUrl,
      // Guarantee config.localDeploy even for an arbitrary regime file (one that forgot to write run.localDeploy).
      ERIS_LOCAL_DEPLOY: "1",
      ERIS_LOCAL_SNAPSHOT_FILE: snapshotFile,
      ERIS_RUN_MODE: "backtest",
      ...(liveWeek ? { [LIVE_WEEK_OVERRIDE]: "1" } : {}),
    });
    // Before the first wait (--follow-schedule may sit hours before epoch 1) and once per regime: the
    // posture reads the regime's roster and sandbox, which differ between regimes only without --agents.
    if (liveWeek) {
      const checked = new Set<string>();
      for (const scenario of scenarios) {
        if (checked.has(scenario.regimePath)) continue;
        checked.add(scenario.regimePath);
        preflightLiveWeek(runOverridesFor(), [
          process.execPath,
          "sim-realtime",
          "--config",
          effectivePathFor(scenario),
        ]);
      }
    }

    // ---- The scenario matrix ----
    // One long-lived anvil; every scenario is snapshot -> run -> reconstruct -> revert (ADR 0017 §3).
    // Scoring reconstruction finishes inside runRealtimeSimulation, i.e. before the next revert
    // erases the history it reads.
    //
    // With --resume the matrix continues where a previous invocation left it (rules §4.7.1: the live
    // week is k epochs, and nothing says they run in one process). The stored scenarios that have
    // agents are complete and skipped; the rest run; the directory stays the same so there is one
    // standings.json for the competition rather than one per invocation. Refused up front when the
    // stored matrix is a different competition (set / k / reset unit / repeat), and when the set's
    // content changed under the same path (ordinal by ordinal, in mergeStoredResults).
    // The field this matrix ranks, as one value: the --agents roster, or the regimes' own rosters
    // keyed by regime when none was passed. Stored in matrix.json and checked on --resume, so the
    // epochs of one matrix cannot be run on two different fields (issue #102).
    const fieldFingerprint = rosterFingerprint(
      rosterAgents ??
        Object.fromEntries(
          scenarios.map((sc) => [sc.regime, loadRegimeDoc(sc).agents ?? []]),
        ),
    );
    let stored: StoredMatrix | undefined;
    if (resumeDir) {
      stored = readStoredMatrix(resumeDir);
      assertResumable(
        stored,
        {
          scenarioSet: flags.scenarios,
          k,
          resetUnit: "scenario",
          repeat,
          ...(agentStateRoot !== undefined ? { agentStateRoot } : {}),
          rosterFingerprint: fieldFingerprint,
          scenarioKeyCommitment: scenarioKey.commitment,
        },
        (p) => resolve(ROOT, p),
      );
      if (stored.rosterFingerprint === undefined)
        console.error(
          "[backtest] warning: the stored matrix does not record its roster (written before " +
            "issue #102); the resume cannot check that the field is the same one",
        );
      const now = gitHead(ROOT);
      if (stored.sourceCommit && now && stored.sourceCommit !== now)
        console.error(
          `[backtest] warning: resuming a matrix written at commit ${stored.sourceCommit.slice(0, 12)} ` +
            `from ${now.slice(0, 12)}. The epochs of one competition should run on one build; ` +
            "matrix.json records the current commit",
        );
    }
    const merged = stored
      ? mergeStoredResults(scenarios, stored.scenarios ?? [])
      : undefined;
    const results: ScenarioResult[] = merged ? [...merged.preloaded] : [];
    const complete = merged?.complete ?? new Set<number>();
    if (merged)
      console.error(
        `[backtest] resuming ${resumeDir}: ${complete.size} of ${scenarios.length} scenario(s) ` +
          `already complete, ${merged.rerun.length} to run`,
      );
    // Kept alongside `results` only for the --repeat spread report below; the folded record is what
    // reaches matrix.json. Indexed like `scenarios`, so a skipped scenario pushes an empty entry.
    const repeatsByScenario: AgentScore[][][] = [];
    const blocksByScenario: Array<Array<number | undefined>> = [];
    // Prepared before the loop, and rewritten after every scenario. A full private matrix is ~6 h;
    // holding the results in memory until the end means an OOM, an anvil death or a Ctrl-C at
    // scenario 29 of 30 throws away everything already computed.
    const outDir = matrixMode
      ? (resumeDir ??
        resolve(
          ROOT,
          "runs",
          `matrix-${new Date().toISOString().replace(/[:.]/g, "-")}`,
        ))
      : undefined;
    if (outDir) mkdirSync(outDir, { recursive: true });
    // The first invocation's, so a resumed matrix keeps the date the competition began; a resume
    // that runs at least one epoch stamps when it continued. A resume with nothing to run leaves
    // the stored stamp alone: it executed nothing, so it did not continue anything (issue #102).
    const createdAt = stored?.createdAt ?? new Date().toISOString();
    const resumedAt =
      resumeDir && (merged?.rerun.length ?? 0) > 0
        ? new Date().toISOString()
        : stored?.resumedAt;
    // In ordinal order whatever order they were computed in, so a resumed matrix reads like an
    // uninterrupted one. computeStandings keys by `s` and does not care.
    const ordered = (): ScenarioResult[] =>
      [...results].sort((a, b) => a.s - b.s);
    const flush = (): void => {
      if (!outDir) return;
      writeFileSync(
        join(outDir, "matrix.json"),
        `${JSON.stringify(
          {
            // schema 2 (ADR 0023): scenarios carry the ordinal `s` and per-agent P (`pnlUsdc`);
            // the M4/M9 fields and `metric` are gone with the metric they belonged to.
            schema: 2,
            createdAt,
            ...(resumedAt !== undefined ? { resumedAt } : {}),
            sourceCommit: gitHead(ROOT) ?? "unknown",
            scenarioSet: flags.scenarios,
            // A matrix is a scenario-mode run by construction (ADR 0020 §1). Written out so a later
            // comparison against a continuous run is refused rather than silently averaged.
            resetUnit: "scenario",
            ...(agentStateRoot !== undefined ? { agentStateRoot } : {}),
            // The schedule length the weights are taken over (rules §4.4.1).
            k,
            repeat,
            // The field, so a --resume on a different roster is refused (issue #102).
            rosterFingerprint: fieldFingerprint,
            // ADR 0027: the key the scenarios were realized under (public, or the commitment to the
            // operator's secret). Reproducing the matrix needs it; a --resume under another is refused.
            scenarioKey: scenarioKeyRecord(scenarioKey),
            // Complete only once every scenario has run; until then this is a partial matrix.
            scenariosPlanned: scenarios.length,
            // The plan's timetable, for the epochs not run yet: the dashboard's "next epoch starts
            // at". Ordinal and time only -- which scenario an epoch is stays with the results.
            ...(scenarios.some((sc) => sc.startsAt)
              ? {
                  schedule: scenarios.map((sc) => ({
                    s: sc.s,
                    ...(sc.startsAt ? { startsAt: sc.startsAt } : {}),
                  })),
                }
              : {}),
            // Both metrics are stored regardless of which one ranks, so the standings can be
            // recomputed under a different scoring rule without re-running anything (ADR 0017 §4).
            scenarios: ordered(),
          },
          null,
          2,
        )}\n`,
      );
      writeFileSync(
        join(outDir, "standings.json"),
        `${JSON.stringify(computeStandings(ordered(), k), null, 2)}\n`,
      );
    };
    // Issue #77: the state every scenario starts from is a function of the plan, not of what ran
    // last (backtest/resume.ts). A fresh matrix records its empty starting point; a resumed one
    // puts the root back to the end of the latest complete ordinal before each re-run.
    if (agentStateRoot !== undefined && matrixMode && !resumeDir)
      checkpointAgentState(agentStateRoot, STATE_LABEL_INITIAL);
    let index = 0;
    for (const scenario of scenarios) {
      index++;
      const label = scenarioId(scenario.regime, scenario.seed);
      if (complete.has(scenario.s)) {
        console.error(
          `[backtest] skipping s=${scenario.s} ${label}, already complete in ${outDir}`,
        );
        repeatsByScenario.push([]);
        blocksByScenario.push([]);
        continue;
      }
      // After the skip, so a resume waits only for the epochs it will run: the missed and failed
      // ones are past their start and go at once, and the next one waits for its own (ADR 0026).
      // Before the state restore, so nothing is touched while the runner sits in a wait that a
      // Ctrl-C may end.
      if (followSchedule && scenario.startsAt !== undefined) {
        const line = describeStart(
          { s: scenario.s, label, startsAt: scenario.startsAt },
          Date.now(),
        );
        if (line) console.error(`[backtest] ${line}`);
        await sleep(startDelay(scenario.startsAt, Date.now()).waitMs);
      }
      if (agentStateRoot !== undefined && resumeDir) {
        const from = stateLabelBefore(scenario.s, complete);
        if (!restoreAllAgentState(agentStateRoot, from))
          throw new Error(
            `--resume: s=${scenario.s} has to start from agent state "${from}", but ` +
              `${join(agentStateRoot, ".snapshots", from)} does not exist. The matrix being ` +
              "resumed was run before state checkpoints were written, or the checkpoint was " +
              "deleted; re-run it as a new matrix rather than continuing this one",
          );
        console.error(
          `[backtest] s=${scenario.s}: agent state restored from "${from}"`,
        );
      }
      const expectedAgents = rosterOf(loadRegimeDoc(scenario));
      // The coordinator reads this scenario's effective regime (passed as --config below). The
      // agents are handed their own config by the coordinator, not this file.
      const effectivePath = effectivePathFor(scenario);

      const perRepeat: AgentScore[][] = [];
      const runDirs: string[] = [];
      const blocksPerRepeat: Array<number | undefined> = [];
      let lastError: string | undefined;
      // With state carrying, the repeats of one scenario are not repeats unless each starts from
      // the same place: repeat 2 would otherwise begin from what repeat 1 left behind, and the
      // spread across repeats -- the reason the flag exists -- would be measuring a sequence.
      // Keyed by the epoch ordinal, not by (regime, seed): a plan may schedule the same pair twice
      // and the two are different epochs with different state behind them.
      const repeatLabel = `repeat-base-s${scenario.s}`;
      for (let i = 0; i < repeat; i++) {
        if (agentStateRoot !== undefined && repeat > 1) {
          if (i === 0) checkpointAgentState(agentStateRoot, repeatLabel);
          else if (!restoreAllAgentState(agentStateRoot, repeatLabel))
            // A repeat that silently kept the previous repeat's state would report a sequence as
            // a spread, which is the one thing the flag must not do.
            throw new Error(
              `--repeat: agent state label "${repeatLabel}" vanished between repeats`,
            );
        }
        console.error(
          `[backtest] scenario ${index}/${scenarios.length} ${label}` +
            (repeat > 1 ? ` (repeat ${i + 1}/${repeat})` : ""),
        );
        try {
          const { runDir } = await runRealtimeSimulation({
            ...runOverridesFor(),
            // ADR 0020 §1: the matrix is the only thing that resets the world between runs, so it is
            // the only thing allowed to declare the mode. A single --regime replay stays `continuous`
            // -- it is one world, whatever the snapshot/revert around it does for the *next* scenario.
            // Issue #167: with it, the epoch's scheduled ordinal and the schedule's length, which
            // reach every agent as ERIS_EPOCH_INDEX / ERIS_EPOCH_COUNT (and obs.epoch).
            ...(matrixMode ? matrixEpochOverrides(scenario.s, k) : {}),
          }, [process.execPath, "sim-realtime", "--config", effectivePath]);
          runDirs.push(runDir);
          const summary = readRunSummary(runDir);
          if (summary) {
            perRepeat.push(scoresFromSummary(summary, expectedAgents));
            blocksPerRepeat.push(summary.blocksProcessed);
          } else {
            lastError = `summary.json not found (${runDir})`;
            console.error(`[backtest] warning: ${lastError}`);
          }
        } catch (error) {
          // Except the live week's posture: recording it as an excluded epoch would run the next
          // epoch into the same refusal, and the one after, until the week had no epochs left.
          if (isLiveWeekRefusal(error)) throw error;
          // One scenario blowing up must not abandon the rest of the matrix. It is recorded as an
          // excluded scenario, which keeps it out of the aggregation instead of scoring everyone
          // zero for an environment failure (ADR 0017 §4).
          lastError = error instanceof Error ? error.message : String(error);
          console.error(`[backtest] scenario ${label} failed: ${lastError}`);
        }
      }
      if (agentStateRoot !== undefined && matrixMode && perRepeat.length > 0) {
        // The checkpoint a resume restores before the ordinal after this one.
        checkpointAgentState(agentStateRoot, stateLabelAfter(scenario.s));
        complete.add(scenario.s);
      }
      repeatsByScenario.push(perRepeat);
      blocksByScenario.push(blocksPerRepeat);
      results.push({
        s: scenario.s,
        regime: scenario.regime,
        seed: scenario.seed,
        ...(scenario.startsAt ? { startsAt: scenario.startsAt } : {}),
        ...(perRepeat.length > 0 ? { agents: foldRepeats(perRepeat) } : {}),
        ...(runDirs.length > 0 ? { runDir: runDirs[runDirs.length - 1] } : {}),
        ...(perRepeat.length === 0 && lastError !== undefined
          ? { error: lastError }
          : {}),
      });
      // An epoch nobody contested is said so at the epoch level, where a reader of the standings
      // looks, not only on each dead agent's record (issue #102).
      const last = results[results.length - 1];
      if (last.agents) {
        const epochFlags = scenarioFlags(last.agents);
        if (epochFlags.length > 0) {
          last.flags = epochFlags;
          console.error(
            `[backtest] s=${last.s} ${label}: ${epochFlags.join("; ")}`,
          );
        }
      }
      flush();
    }

    // ---- Report ----
    const standings = computeStandings(ordered(), k);
    console.log("");
    // With --repeat, show each run rather than only the fold. The point of repeating a scenario is
    // to see how far it moves run to run (ADR 0005 says to read results as a distribution), and a
    // single folded line hides both the spread and a run that ended early on fewer blocks.
    if (repeat > 1) {
      for (const [s, scenario] of scenarios.entries()) {
        const runs = repeatsByScenario[s] ?? [];
        if (runs.length === 0) continue;
        console.log(
          `  ${scenarioId(scenario.regime, scenario.seed)} — ${runs.length}/${repeat} runs:`,
        );
        for (const [i, run] of runs.entries())
          console.log(
            `    run ${i + 1} (${blocksByScenario[s]?.[i] ?? "?"} blocks): ` +
              run
                .map(
                  (a) =>
                    `${a.id}=${a.pnlUsdc?.toFixed(2) ?? "-"}${a.flags ? "(!)" : ""}`,
                )
                .join("  "),
          );
      }
      console.log("");
    }
    for (const result of ordered()) {
      const label = scenarioId(result.regime, result.seed);
      if (!result.agents) {
        console.log(`  ${label}: FAILED (${result.error})`);
        continue;
      }
      const epoch = standings.epochs.find((e) => e.s === result.s);
      const line = result.agents
        .map(
          (a) =>
            `${a.id}=${a.pnlUsdc?.toFixed(2) ?? "-"}` +
            (epoch?.tByAgent[a.id] !== undefined
              ? `(T ${epoch.tByAgent[a.id].toFixed(1)})`
              : "") +
            (a.flags ? "(!)" : ""),
        )
        .join("  ");
      console.log(
        `  s=${result.s} ${label}${epoch?.excluded ? ` [out of S: ${epoch.excluded}]` : ""}: ${line}`,
      );
    }

    if (matrixMode && outDir) {
      // Already written incrementally by flush(); this is the final, complete pass.
      flush();
      console.log("");
      console.log(
        `standings (rules §4.4 deviation score, k=${standings.k}, S=[${standings.S.join(",")}]):`,
      );
      for (const agent of standings.agents)
        console.log(
          `  ${String(agent.rank).padStart(2)}${agent.tied ? "=" : "."} ${agent.id.padEnd(20)} ` +
            `${agent.score === null ? "-" : agent.score.toFixed(2)}` +
            `  [${agent.epochs.map((e) => `s${e.s}:${e.t.toFixed(1)}`).join(" ")}]` +
            (agent.flags.length > 0 ? `  ! ${agent.flags.length} flag(s)` : ""),
        );
      const excluded = standings.epochs.filter((e) => e.excluded !== undefined);
      if (excluded.length > 0)
        console.log(
          `  out of S: ` +
            excluded
              .map(
                (e) =>
                  `s=${e.s} ${scenarioId(e.regime, e.seed)} (${e.excluded})`,
              )
              .join(", "),
        );
      for (const b of standings.benchmarks)
        console.log(
          `  benchmark ${b.id}: ` +
            Object.entries(b.pnlByEpoch)
              .map(([s, p]) => `s${s}:${p.toFixed(2)}`)
              .join(" "),
        );
      console.log("");
      console.log(`wrote ${outDir}/matrix.json and standings.json`);
    }
  } finally {
    if (keepAnvil) {
      // Detach so the child handle doesn't hold the event loop and prevent the CLI from exiting.
      anvil.unref();
      console.error(
        `[backtest] --keep-anvil: anvil stays running at ${rpcUrl} (stop it manually)`,
      );
    } else stopAnvil();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
