// participant backtest CLI (ADR 0016. B1 realtime replay).
//
//   npm run backtest -- --regime <name|path> [--agents <roster>] [--repeat N]
//                       [--port 8547] [--state backtest/state] [--keep-anvil]
//                       [--seed N] [--blocks N] [--seconds N] [--protocols a,b]
//
// Starts a dedicated anvil with a distributed state dump loaded (generated by gen:state-dump) and
// replays an official regime (config/regimes/*.yaml + seed) via the existing coordinator. --repeat N
// invokes the coordinator repeatedly in the same process, with resetFork's evm_snapshot/evm_revert
// guaranteeing a clean slice between runs (scoring reconstruction finishes at the end of each run =
// before the next revert).
//
// Dependency-light for the same reason as sim-realtime.ts: before importing sdk/constants we must set
// ERIS_LOCAL_DEPLOY=1 and finish syncing the constants.local.ts fingerprint. The coordinator is
// dynamically imported last.
import { spawn, type ChildProcess } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import {
  gitHead,
  isAnvilUp,
  missingVenues,
  parseFlags,
  readConstantsFingerprint,
  readStateManifest,
  resolveRegimePath,
  rpc,
  STATE_DIR_DEFAULT,
  waitUntilAnvilUp,
} from "../backtest/shared.js";

const ROOT = process.cwd(); // npm scripts run at the repo root

const USAGE = `usage: npm run backtest -- --regime <name|path> [options]
  --regime <name|path>   config/regimes/<name>.yaml (or a YAML path). required
  --agents <roster>      replace the regime's default agents with a roster file (YAML/JSON)
  --repeat <N>           repeat the same regime N times (snapshot/revert. default 1)
  --port <N>             port for the backtest-only anvil (default 8547)
  --state <dir>          state dump directory (default ${STATE_DIR_DEFAULT})
  --keep-anvil           keep anvil running after exit (for debugging)
  --seed/--blocks/--seconds/--protocols/--economic-gas
                         one-off overrides of regime values (for smoke tests. runs you read results from use regime defaults)`;

type AgentSummary = { id: string; alphaUsdc?: number; netPnlUsdc?: number };
type RunSummary = {
  runDir: string;
  blocksProcessed?: number;
  agents: AgentSummary[];
};

function readRunSummary(runDir: string): RunSummary | undefined {
  const path = join(runDir, "summary.json");
  if (!existsSync(path)) return undefined;
  const parsed = JSON.parse(readFileSync(path, "utf8")) as {
    blocksProcessed?: number;
    agents?: AgentSummary[];
  };
  return {
    runDir,
    blocksProcessed: parsed.blocksProcessed,
    agents: parsed.agents ?? [],
  };
}

// Sync constants.local.ts with the deployments bundled in the state manifest (ADR 0016 §2).
// On mismatch, extract deployments from the manifest and regenerate; if it still doesn't match,
// the state dump and repo version are a mismatched combination -> fail-fast.
async function syncConstants(
  manifestFingerprint: string,
  deployments: Record<string, unknown>,
  stateDirAbs: string,
): Promise<void> {
  const constantsPath = resolve(ROOT, "sdk", "src", "constants.local.ts");
  const current = readConstantsFingerprint(constantsPath);
  if (current === manifestFingerprint) return;
  console.error(
    `[backtest] constants.local.ts fingerprint does not match the state manifest ` +
      `(${current ?? "(none)"} != ${manifestFingerprint}). Regenerating from the deployments bundled in the manifest`,
  );
  const extracted = join(stateDirAbs, "deployments.extracted.json");
  writeFileSync(extracted, `${JSON.stringify(deployments, null, 2)}\n`);
  // genLocalConstants depends only on node builtins + viem + backtest/shared (it doesn't evaluate
  // sdk/constants), so it's fine to import before the coordinator.
  const { generateLocalConstants } =
    await import("../../../scripts/genLocalConstants.js");
  const { fingerprint } = generateLocalConstants(extracted);
  if (fingerprint !== manifestFingerprint)
    throw new Error(
      `fingerprint still doesn't match after regenerating constants.local.ts ` +
        `(${fingerprint} != ${manifestFingerprint}). Check the combination of the state dump and repo ` +
        `versions (ADR 0016 §2 fail-fast)`,
    );
}

async function main(): Promise<void> {
  const flags = parseFlags(process.argv);
  if (!flags.regime) {
    console.error(USAGE);
    throw new Error("--regime is required");
  }
  if (flags.config)
    throw new Error(
      "for backtest use --regime, not --config (the regime YAML is the run config itself)",
    );

  const repeat = Number(flags.repeat ?? "1");
  if (!Number.isInteger(repeat) || repeat < 1)
    throw new Error(
      `--repeat must be a positive integer (got ${flags.repeat})`,
    );
  const port = Number(flags.port ?? "8547");
  const rpcUrl = `http://127.0.0.1:${port}`;
  const stateDirAbs = resolve(ROOT, flags.state ?? STATE_DIR_DEFAULT);
  const regimePath = resolveRegimePath(ROOT, flags.regime);
  const regimeName = basename(regimePath).replace(/\.ya?ml$/, "");

  // ---- Validate the state manifest + sync constants (done before importing the coordinator) ----
  const { manifest, statePath } = readStateManifest(stateDirAbs);
  const head = gitHead(ROOT);
  if (
    head &&
    manifest.sourceCommit !== "unknown" &&
    head !== manifest.sourceCommit
  )
    console.error(
      `[backtest] note: the state dump's generating commit (${manifest.sourceCommit.slice(0, 12)}) ` +
        `differs from the current HEAD (${head.slice(0, 12)}). If you changed deployer/constants, ` +
        `rebuild it with npm run gen:state-dump`,
    );
  await syncConstants(
    manifest.deploymentsFingerprint,
    manifest.deployments,
    stateDirAbs,
  );

  // ---- Lightweight regime read + applying one-off overrides (the effective regime) ----
  // Run overrides (--protocols, etc.) aren't enough via the coordinator's cliOverrides alone: the
  // agent process reads the ERIS_CONFIG YAML directly, so we write out an "effective regime YAML" with
  // the overrides merged in, making the coordinator and agent read the same config (otherwise the agent
  // tries to observe a venue not in the state and dies on a zero-address read). The --agents roster is
  // baked into the effective YAML's inline agents for the same reason (don't add a priority branch to
  // core's roster resolution).
  type RegimeDoc = {
    run?: Record<string, unknown> & {
      seed?: number;
      protocols?: string[];
    };
    agents?: unknown;
  } & Record<string, unknown>;
  const regimeDoc = parseYaml(readFileSync(regimePath, "utf8")) as RegimeDoc;

  const runOverrides: Record<string, unknown> = {};
  if (flags.protocols)
    runOverrides.protocols = flags.protocols.split(",").map((s) => s.trim());
  if (flags.seed !== undefined) runOverrides.seed = Number(flags.seed);
  if (flags.blocks !== undefined) runOverrides.blocks = Number(flags.blocks);
  if (flags.seconds !== undefined) runOverrides.seconds = Number(flags.seconds);
  if (flags["economic-gas"] !== undefined)
    runOverrides.economicGas =
      flags["economic-gas"] === "1" || flags["economic-gas"] === "true";

  let rosterAgents: unknown;
  if (flags.agents !== undefined) {
    const rosterPath = resolve(ROOT, flags.agents);
    if (!existsSync(rosterPath))
      throw new Error(`agents roster not found: ${rosterPath} (--agents)`);
    // JSON is a subset of YAML 1.2, so parseYaml can read a .json roster too.
    // Leave content validation to the coordinator's validateAgentsFile.
    const roster = parseYaml(readFileSync(rosterPath, "utf8")) as {
      agents?: unknown;
    };
    if (!roster || !Array.isArray(roster.agents))
      throw new Error(`${rosterPath} must contain an "agents" array`);
    rosterAgents = roster.agents;
  }

  let effectiveRegimePath = regimePath;
  if (Object.keys(runOverrides).length > 0 || rosterAgents !== undefined) {
    const effective: RegimeDoc = {
      ...regimeDoc,
      run: { ...(regimeDoc.run ?? {}), ...runOverrides },
      ...(rosterAgents !== undefined ? { agents: rosterAgents } : {}),
    };
    effectiveRegimePath = join(stateDirAbs, `.effective-${regimeName}.yaml`);
    writeFileSync(
      effectiveRegimePath,
      `# AUTO-GENERATED by backtest CLI — ${regimePath} + CLI overrides. Do not edit by hand.\n` +
        stringifyYaml(effective),
    );
    const overridden = [
      ...Object.keys(runOverrides),
      ...(rosterAgents !== undefined ? ["agents"] : []),
    ];
    console.error(
      `[backtest] overrides present (${overridden.join(", ")}) -> wrote the effective regime to ${effectiveRegimePath}. ` +
        `Runs you read results from should use regime default values (ADR 0016 §3)`,
    );
  }

  // Whether the venues the regime requires are all present in the state dump. If some are missing,
  // an eth_call to a zero address gives a cryptic error, so fail-fast first.
  const effectiveProtocols =
    (runOverrides.protocols as string[] | undefined) ??
    regimeDoc?.run?.protocols ??
    [];
  const missing = missingVenues(effectiveProtocols, manifest.deployments);
  if (missing.length > 0)
    throw new Error(
      `state dump is missing venues: ${missing.join(", ")}. Either rebuild it from a full deploy ` +
        `with npm run gen:state-dump, or narrow the target venues with --protocols ` +
        `(e.g. --protocols ${effectiveProtocols.filter((p) => !missing.includes(p)).join(",")})`,
    );

  // ---- Backtest-only anvil (--load-state) ----
  if (await isAnvilUp(rpcUrl))
    throw new Error(
      `port ${port} is in use (fail-fast to avoid dragging in the deployer anvil, etc.). ` +
        `Specify a different port with --port`,
    );
  console.error(
    `[backtest] starting anvil (--load-state ${statePath} / port ${port})`,
  );
  const anvil: ChildProcess = spawn(
    "anvil",
    [
      "--port",
      String(port),
      // Same calibration as the deployer's anvil (deployer/src/anvil.ts startAnvil)
      // (code-size/base-fee/gas-limit). When you change that one, match it here.
      // Only --order fees is a deliberate addition to align with production realtime.
      "--code-size-limit",
      "50000",
      "--base-fee",
      "0",
      "--gas-limit",
      "3000000000",
      "--accounts",
      "10",
      "--balance",
      "1000000",
      "--order",
      "fees",
      "--load-state",
      statePath,
    ],
    { stdio: ["ignore", "ignore", "inherit"] },
  );
  const keepAnvil = flags["keep-anvil"] === "1";
  const stopAnvil = (): void => {
    if (!anvil.killed) anvil.kill("SIGTERM");
  };
  process.on("SIGINT", () => {
    stopAnvil();
    process.exit(130);
  });

  try {
    await waitUntilAnvilUp(rpcUrl);
    // Detect a state mix-up: whether the genesis hash matches the manifest's generator (ADR 0016 §2)
    const genesis = await rpc<{ hash: string }>(
      rpcUrl,
      "eth_getBlockByNumber",
      ["0x0", false],
    );
    if (genesis.hash !== manifest.genesisHash)
      throw new Error(
        `loaded state's genesis (${genesis.hash.slice(0, 12)}…) does not match the manifest ` +
          `(${manifest.genesisHash.slice(0, 12)}…). The state dump is corrupt or a different one`,
      );

    // ---- Repeated coordinator runs ----
    // The snapshot file is backtest-anvil only (doesn't pollute the deployer anvil's .local-snapshot).
    // Each start is from a fresh anvil, so clear any leftover from last time first.
    const snapshotFile = join(stateDirAbs, `.snapshot-${port}`);
    rmSync(snapshotFile, { force: true });

    process.env.ERIS_LOCAL_DEPLOY = "1";
    // Have both the coordinator and agent processes read the effective regime (the agent via ERIS_CONFIG).
    process.env.ERIS_CONFIG = effectiveRegimePath;
    // Evaluate after the constants sync (dynamically, since static imports are hoisted; same as sim-realtime.ts).
    const { runRealtimeSimulation } =
      await import("../realtime/coordinator.js");

    const summaries: RunSummary[] = [];
    for (let i = 0; i < repeat; i++) {
      console.error(
        `[backtest] run ${i + 1}/${repeat} (regime=${regimeName}, seed=${runOverrides.seed ?? regimeDoc?.run?.seed ?? "?"})`,
      );
      const { runDir } = await runRealtimeSimulation({
        ANVIL_RPC_URL: rpcUrl,
        // Guarantee config.localDeploy even for an arbitrary regime file (one that forgot to write run.localDeploy).
        ERIS_LOCAL_DEPLOY: "1",
        ERIS_LOCAL_SNAPSHOT_FILE: snapshotFile,
        ERIS_RUN_MODE: "backtest",
      });
      const summary = readRunSummary(runDir);
      if (summary) summaries.push(summary);
      else
        console.error(
          `[backtest] warning: summary.json not found for run ${i + 1} (${runDir})`,
        );
    }

    // ---- Aggregation (for multiple runs also print the per-agent mean. ADR 0005: read as a distribution) ----
    console.log("");
    console.log(`backtest ${regimeName}: ${summaries.length}/${repeat} runs`);
    for (const s of summaries) {
      const line = s.agents
        .map(
          (a) =>
            `${a.id} α=${a.alphaUsdc?.toFixed(2) ?? "-"} pnl=${a.netPnlUsdc?.toFixed(2) ?? "-"}`,
        )
        .join("  ");
      console.log(
        `  ${basename(s.runDir)} (${s.blocksProcessed} blocks): ${line}`,
      );
    }
    if (summaries.length > 1) {
      const byAgent = new Map<string, number[]>();
      for (const s of summaries)
        for (const a of s.agents)
          if (a.alphaUsdc !== undefined)
            byAgent.set(a.id, [...(byAgent.get(a.id) ?? []), a.alphaUsdc]);
      console.log("  mean alphaUsdc:");
      for (const [id, values] of byAgent) {
        const mean = values.reduce((x, y) => x + y, 0) / values.length;
        console.log(`    ${id}: ${mean.toFixed(2)} (n=${values.length})`);
      }
    }
  } finally {
    if (keepAnvil) {
      // Detach so the child handle doesn't hold the event loop and prevent the CLI from exiting.
      anvil.unref();
      console.error(
        `[backtest] --keep-anvil: anvil stays running at ${rpcUrl} (stop it manually)`,
      );
    } else stopAnvil();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
