// Regenerate sdk/src/methodSelectors.ts from the venue ABIs (ADR 0021 §4).
//
//   npm run gen:method-selectors
//
// The generated module has no imports, which is the whole reason it is generated: the dashboard
// decodes calldata in the browser, and importing the ABI-derived builder would ship viem's ABI
// parser and a keccak implementation to name 123 functions (measured: +15kB gzipped, plus hashing
// on every page load). test/methodNames.test.ts recomputes the table and compares, so an ABI that
// changes without this being re-run fails the test rather than losing a name in silence.
import { writeFileSync } from "node:fs";
import { buildMethodSelectors } from "@eris/sdk/methodNames.js";

const OUT = "sdk/src/methodSelectors.ts";

const table = buildMethodSelectors();
const entries = Object.entries(table).sort(([a], [b]) => a.localeCompare(b));

const body = entries
  .map(([selector, name]) => `  "${selector}": "${name}",`)
  .join("\n");

writeFileSync(
  OUT,
  `// GENERATED by scripts/genMethodSelectors.ts -- do not edit by hand.
//
// selector (the first four bytes of a tx's calldata) -> the function it calls. Built from the venue
// ABIs the sdk holds (sdk/src/methodNames.ts), because the environment deployed every contract on
// this chain and therefore knows what every selector on it means.
//
// This module deliberately imports nothing: it is loaded in the browser by the dashboard's live
// view, which decodes the calldata of blocks it reads over RPC (ADR 0021 §4).
//
// Regenerate with: npm run gen:method-selectors

export const METHOD_SELECTORS: Record<string, string> = {
${body}
};

/**
 * The function name a tx's calldata calls, or undefined when this deployment has no ABI for it.
 * Undefined rather than a guess: an unnamed method is honest, a wrong one is worse than a hex string.
 */
export function methodNameForCalldata(
  data: string | undefined | null,
): string | undefined {
  if (!data || data.length < 10 || !data.startsWith("0x")) return undefined;
  return METHOD_SELECTORS[data.slice(0, 10).toLowerCase()];
}
`,
);

console.error(`[gen] wrote ${OUT} — ${entries.length} selectors`);
