// `npm run gen:practice-episodes` -- write the practice period's episodes, one of every kind per day
// (core/src/practiceEpisodes.ts has why).
//
//   npm run gen:practice-episodes -- --start 2026-10-01T10:00:00+09:00   the period from that start to run.endsAt
//   npm run gen:practice-episodes -- --hours 26                           a rehearsal of that length
//   [--config config/practice.yaml] [--print]
//
// Run it for the start the coordinator is about to have: `windowFrac` is a fraction of the run and
// the run is measured from the moment the coordinator starts, so a plan written for 10:00 and started
// at 11:00 is an hour off everywhere. Up to EDGE_MARGIN_HOURS off still leaves every day with exactly
// one of each kind.
import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "yaml";
import {
  dailyEpisodePlan,
  EDGE_MARGIN_HOURS,
  KINDS_PER_DAY,
  renderEventLines,
  replaceStressEvents,
} from "../core/src/practiceEpisodes.js";

function flag(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i < 0 ? undefined : (process.argv[i + 1] ?? "");
}

const path = flag("config") ?? "config/practice.yaml";
const text = readFileSync(path, "utf8");
const run = ((parse(text) as { run?: Record<string, unknown> }).run ??
  {}) as Record<string, unknown>;
const segmentHours = Number(run.segmentHours ?? 24);

let hours: number;
let basis: string;
const hoursFlag = flag("hours");
if (hoursFlag !== undefined) {
  hours = Number(hoursFlag);
  basis = `a run of ${hours} h (--hours)`;
} else {
  const endsAt = run.endsAt;
  if (typeof endsAt !== "string")
    throw new Error(
      `${path} has no run.endsAt; pass --hours for a run stated in blocks`,
    );
  const startFlag = flag("start");
  if (!startFlag)
    throw new Error(
      "pass --start <ISO 8601 with a time zone>: the moment the coordinator will start",
    );
  const start = Date.parse(startFlag);
  const end = Date.parse(endsAt);
  if (!Number.isFinite(start) || !Number.isFinite(end))
    throw new Error(
      `cannot read --start ${startFlag} / run.endsAt ${endsAt} as dates`,
    );
  hours = (end - start) / 3_600_000;
  basis = `a start at ${startFlag}, run.endsAt ${endsAt} (${hours.toFixed(2)} h)`;
}

const plan = dailyEpisodePlan(hours, segmentHours);
const header = [
  `Generated by \`npm run gen:practice-episodes\` for ${basis}.`,
  `${plan.length} day(s) x ${KINDS_PER_DAY} episodes. Edit core/src/practiceEpisodes.ts, not these lines;`,
  `start the coordinator within ${EDGE_MARGIN_HOURS} h of the start above, or regenerate.`,
];
const out = replaceStressEvents(text, renderEventLines(plan, header));
if (process.argv.includes("--print")) {
  process.stdout.write(out);
} else {
  writeFileSync(path, out);
  console.error(
    `[gen:practice-episodes] ${path}: ${plan.length} day(s) x ${KINDS_PER_DAY} episodes for ${basis}`,
  );
}
