import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { pythonSchemas, snakeCase } from "./pythonSdkSchema.js";

const { action, observation, members } = pythonSchemas();
mkdirSync("sdk-py/schema", { recursive: true });
mkdirSync("sdk-py/eris", { recursive: true });
for (const [name, schema] of Object.entries({ action, observation })) {
  const input = `sdk-py/schema/${name}.json`;
  const output = `sdk-py/eris/${name}.py`;
  writeFileSync(input, JSON.stringify(schema, null, 2) + "\n");
  execFileSync(
    process.env.ERIS_DATAMODEL_CODEGEN ?? "datamodel-codegen",
    [
      "--input",
      input,
      "--input-file-type",
      "jsonschema",
      "--output",
      output,
      "--output-model-type",
      "pydantic_v2.BaseModel",
      "--target-python-version",
      "3.11",
      "--snake-case-field",
      "--allow-population-by-field-name",
      "--use-title-as-name",
      "--use-one-literal-as-default",
      "--enum-field-as-literal",
      "all",
      "--use-standard-collections",
      "--use-union-operator",
      "--field-constraints",
      "--disable-timestamp",
      "--collapse-root-models",
    ],
    { stdio: "inherit" },
  );
  // The tool includes the input filename, but no date or machine-dependent paths.
  if (
    !readFileSync(output, "utf8").includes("# generated by datamodel-codegen:")
  )
    throw new Error(`generator did not produce ${output}`);
}
writeFileSync(
  "sdk-py/eris/actions.py",
  [
    "# Generated by npm run gen:python-sdk; do not edit.",
    "from .action import (",
    ...members.map(
      (m) => `    ${m.title} as ${snakeCase(m.properties.type.const)},`,
    ),
    ")",
    "",
    `__all__ = ${JSON.stringify(members.map((m) => snakeCase(m.properties.type.const)))}`,
    "",
  ].join("\n"),
);
type Property = { type?: string; anyOf?: Property[] };
function pythonType(property: Property): string {
  if (property.anyOf) return [...new Set(property.anyOf.map(pythonType))].join(" | ");
  return ({ string: "str", integer: "int", number: "float", boolean: "bool", object: "dict", array: "list", null: "None" } as Record<string, string>)[property.type ?? ""] ?? "Any";
}
writeFileSync(
  "sdk/src/pythonVocabulary.ts",
  [
    "// Generated by npm run gen:python-sdk from actionSchema.ts; do not edit.",
    `export const PYTHON_ACTION_VOCABULARY: Readonly<Record<string, string>> = ${JSON.stringify(
      Object.fromEntries(
        members.map((m) => {
          const properties = m.properties as Record<
            string,
            Property
          >;
          return [
            m.properties.type.const,
            `${snakeCase(m.properties.type.const)}(*, ${Object.entries(properties)
              .filter(([k]) => k !== "type")
              .map(([key, p]) => `${snakeCase(key)}: ${pythonType(p)}${m.required?.includes(key) ? "" : " | None = None"}`)
              .join(", ")})`,
          ];
        }),
      ),
      null,
      2,
    )};`,
    "",
  ].join("\n"),
);
